### ISSUE TITLE
6주차 과제 - 비밀 모임 사이트 만들기 (Devise 응용)

### ISSUE THREAD

**Issue by woonjangahn** [NEXT-LIKELION/Assignment#10]
안녕하세요~ 우리 이번 학기 수업이 한 달도 채 남지 않았네요 8ㅅ8 
늘 고생해주셔서 감사합니다. 사실 지난번에 비하면 어렵지 않은 과제입니다 ㅎㅎ

요구사항)

1. 새로운 Rails 프로젝트를 만들되, Scaffold로 게시판 역시 만들어 주세요.
2. Devise를 설치 후 적용하고, 교안을 참고하여 devise-i18n gem을 이용해 한글화 해주세요.
3. Bootstrap (또는 Semantic UI나 Materialize CSS 등 모두 괜찮습니다)을 이용해 페이지를 그럴듯하게 만들어주세요. (Navbar, 게시판, 로그인 및 회원가입 form 등..)
4. Navbar에는 로그인 된 상태에서는 로그아웃 버튼을, 로그아웃 상태에서는 로그인 버튼이 나타나게 코드를 추가해주세요.
5. 게시판에 접근 할때 로그인 상태가 아니라면 로그인 페이지를 불러와주세요. 로그인 상태에는 정상적으로 게시판이 나타나야 합니다. 이 부분은 devise documentation을 참고하시면 답이 나옵니다.
6. 페이지를 모두 만든 후 github에 devise_homework 라는 이름의 새로운 repository를 만들어주시고 Rails 프로젝트 전체를 push 해주시기 바랍니다.
7. 그리고 지난번과 같이 스크린샷을 올려주세요! (샘플 스크린샷을 첨부합니다.)

![6-1](https://user-images.githubusercontent.com/26523571/39908570-a5ad5de6-5529-11e8-9dea-fdef5ea549d0.PNG)
![6-2](https://user-images.githubusercontent.com/26523571/39908571-a5defc84-5529-11e8-9876-ffad78cbc5bb.PNG)
![6-3](https://user-images.githubusercontent.com/26523571/39908572-a607a404-5529-11e8-8c69-b4d42dc02eb8.PNG)

**Comment by woonjangahn** [comment]
"그리고 마지막에 성공적으로 로그인 되었습니다." 문구가 2번이나 나오는 이유는 무엇일까요? 해결하시는 분이 계실꺼라 믿습니다! 저도 열심히 구글링 할게욥 ㅎㅅㅎ

**Comment by gyeol1212** [comment]
신한결
![2018-05-11 5 27 53](https://user-images.githubusercontent.com/37537201/39914710-d2a06b7e-5540-11e8-93c5-2a65e95e77f5.png)
![2018-05-11 5 28 02](https://user-images.githubusercontent.com/37537201/39914714-d43d0f5a-5540-11e8-880b-ee05ff1c71bd.png)
![2018-05-11 5 28 09](https://user-images.githubusercontent.com/37537201/39914717-d62002fa-5540-11e8-995a-6ac6b9c38bce.png)
![2018-05-11 5 28 30](https://user-images.githubusercontent.com/37537201/39914720-d70e5536-5540-11e8-8ad1-7336c8a04205.png)

**Comment by seona-yu** [comment]
유선아

<img width="919" alt="21" src="https://user-images.githubusercontent.com/37537217/39930125-cd0fcb1c-5574-11e8-968a-cec64956c733.png">
<img width="936" alt="22" src="https://user-images.githubusercontent.com/37537217/39930133-d1ec86c0-5574-11e8-98b1-5be3baec2c6d.png">
<img width="920" alt="23" src="https://user-images.githubusercontent.com/37537217/39930135-d47754ec-5574-11e8-94fc-0f8427b2073e.png">
<img width="921" alt="24" src="https://user-images.githubusercontent.com/37537217/39930139-d7dbfb2e-5574-11e8-9dd2-5b742c88c721.png">
<img width="933" alt="25" src="https://user-images.githubusercontent.com/37537217/39930144-dae5f5c2-5574-11e8-83d2-ecc9977045d2.png">

**Comment by X3PY** [comment]
전준표
![1](https://user-images.githubusercontent.com/37537209/39939738-2dd89998-5592-11e8-8880-e7df8a614308.PNG)
![2](https://user-images.githubusercontent.com/37537209/39939739-2dfeb6e6-5592-11e8-8e70-0b71875404fc.PNG)
![3](https://user-images.githubusercontent.com/37537209/39939740-2e25a062-5592-11e8-9acd-35589f84de3a.PNG)
![4](https://user-images.githubusercontent.com/37537209/39939741-2e4cad10-5592-11e8-9603-45514f75752b.PNG)

**Comment by hyunjaeyou** [comment]
유현재입니다
![1](https://user-images.githubusercontent.com/37537210/39953425-9116eaba-55e6-11e8-8ab6-66ad3d964a5d.png)
![2](https://user-images.githubusercontent.com/37537210/39953426-92d607a0-55e6-11e8-89e6-c412faded7a3.png)
![3](https://user-images.githubusercontent.com/37537210/39953428-948ec654-55e6-11e8-8a49-7b0f58f08807.png)

**Comment by dkor3** [comment]
안성수 
![6](https://user-images.githubusercontent.com/37537204/39954799-1277278c-5600-11e8-836f-d14f4a243ff8.png)
![7](https://user-images.githubusercontent.com/37537204/39954800-12bc86ec-5600-11e8-94bd-f1c93bc83f1b.png)

**Comment by sangw0804** [comment]
오상우
![image](https://user-images.githubusercontent.com/37537207/39957511-1e08b14a-562f-11e8-9a2e-7c2bde143b57.png)
![image](https://user-images.githubusercontent.com/37537207/39957516-35a665fe-562f-11e8-9e14-0698c22022f9.png)
<img width="1280" alt="2018-05-12 4 55 49" src="https://user-images.githubusercontent.com/37537207/39955189-bd1d9fc2-5605-11e8-84cd-03c312035190.png">
![image](https://user-images.githubusercontent.com/37537207/39955219-102c3386-5606-11e8-8bd1-0eb38ab0d2da.png)

**Comment by norrard148** [comment]
장영재
![1](https://user-images.githubusercontent.com/37537262/39956134-be5e80a8-5615-11e8-9b19-dec28c798c81.PNG)
![2](https://user-images.githubusercontent.com/37537262/39957832-54891c00-5634-11e8-8893-82c0f2f2662f.PNG)
![3](https://user-images.githubusercontent.com/37537262/39957849-c6edfba8-5634-11e8-9af0-5b65375c87f2.PNG)

**Comment by soonjune** [comment]
박승준
<img width="1277" alt="2018-05-12 10 06 44" src="https://user-images.githubusercontent.com/37537242/39957639-2df12130-5631-11e8-9165-203965543ade.png">
<img width="1179" alt="2018-05-12 10 07 47" src="https://user-images.githubusercontent.com/37537242/39957640-342fb9f8-5631-11e8-9587-dfdedc8cea26.png">
<img width="1279" alt="2018-05-12 10 08 17" src="https://user-images.githubusercontent.com/37537242/39957641-387e8fac-5631-11e8-95f4-9cb1a6637539.png">
<img width="1280" alt="2018-05-12 10 08 44" src="https://user-images.githubusercontent.com/37537242/39957642-3f298cc6-5631-11e8-9fbe-1e36b89c045c.png">

**Comment by qlqnf16** [comment]
이정민

<img width="960" alt="2018-05-13" src="https://user-images.githubusercontent.com/37537216/39959238-ce7f79fe-5649-11e8-9133-f17fb7bde351.png">
<img width="960" alt="2018-05-13 1" src="https://user-images.githubusercontent.com/37537216/39959236-ce2f50e6-5649-11e8-8818-f09ae1fcf6df.png">
<img width="960" alt="2018-05-13 2" src="https://user-images.githubusercontent.com/37537216/39959237-ce588768-5649-11e8-841c-9a846ac863d9.png">

**Comment by ghost** [comment]
장민규입니다 !
<img width="960" alt="1" src="https://user-images.githubusercontent.com/37537219/39959761-a2bf6d26-5651-11e8-91a3-bacf00c8c17d.PNG">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/37537219/39959763-a3b5f06a-5651-11e8-8d2c-f638ae5a67b7.PNG">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/37537219/39959764-a4b85110-5651-11e8-90d4-a51f221481bd.PNG">

**Comment by PoSungKim** [comment]
김보성
![_ _](https://user-images.githubusercontent.com/37537227/39969204-bb4f8c46-5713-11e8-9037-01898e1d2c2b.PNG)
![_ _ 3](https://user-images.githubusercontent.com/37537227/39969207-c05e1bb2-5713-11e8-9165-efb6129dc34e.PNG)
![_ _ 2](https://user-images.githubusercontent.com/37537227/39969212-c4157520-5713-11e8-84a2-36f216ad57fa.PNG)
![_ _ 4](https://user-images.githubusercontent.com/37537227/39969214-c5e46e88-5713-11e8-981d-f9d25ba2038b.PNG)

**Comment by Cecilia-L** [comment]
이윤비
<img width="960" alt="default" src="https://user-images.githubusercontent.com/37537232/39973732-277cf0da-575e-11e8-9d32-0c9431edc90f.PNG">
<img width="960" alt="default" src="https://user-images.githubusercontent.com/37537232/39973733-27a9dce4-575e-11e8-9969-3073d1091cae.PNG">
<img width="960" alt="default" src="https://user-images.githubusercontent.com/37537232/39973734-27d3e0ac-575e-11e8-8ba2-1799dbd77cac.PNG">

**Comment by jiwonny** [comment]
![image](https://user-images.githubusercontent.com/37537213/39978805-99e31d88-577d-11e8-8c7e-591b7ec150fa.png)
![image](https://user-images.githubusercontent.com/37537213/39978863-d7c325e4-577d-11e8-8e3b-21bd3b1442b7.png)

**Comment by Yerim2695** [comment]
![1](https://user-images.githubusercontent.com/37537200/39980109-27b2b20c-5785-11e8-97b4-75d28fe11502.jpg)
![11](https://user-images.githubusercontent.com/37537200/39980114-2904ad7c-5785-11e8-89b4-4390347da4c1.jpg)
![2](https://user-images.githubusercontent.com/37537200/39980110-27d9d1f2-5785-11e8-95d0-67b42818f09b.jpg)
![3](https://user-images.githubusercontent.com/37537200/39980111-27fc926e-5785-11e8-97a9-a94c45f7187a.jpg)
![4](https://user-images.githubusercontent.com/37537200/39980112-28af6b8c-5785-11e8-968a-f46055179494.jpg)
![5](https://user-images.githubusercontent.com/37537200/39980113-28e0a896-5785-11e8-956f-eb6dea91633a.jpg)

**Comment by daisybae** [comment]
배영현입니다.. 
![image](https://user-images.githubusercontent.com/37537214/39985543-e56acfc8-5799-11e8-95d4-8d26032d57db.png)
![image](https://user-images.githubusercontent.com/37537214/39985578-fc9939d2-5799-11e8-9db4-eb1608c1f13b.png)
![image](https://user-images.githubusercontent.com/37537214/39986068-82f3a160-579b-11e8-994c-c4d891d1cc2c.png)
![image](https://user-images.githubusercontent.com/37537214/39985645-2853e8c4-579a-11e8-90ba-fad451473c06.png)

**Comment by Hyezzi** [comment]
![image](https://user-images.githubusercontent.com/37537222/39990816-8ba66060-57a8-11e8-8b8e-37e481e0fa29.png)

![image](https://user-images.githubusercontent.com/37537222/39990734-549e47ae-57a8-11e8-9ede-88ce1c141853.png)
원혜진

**Comment by jihyuunn** [comment]
![2018-05-14 10 01 30](https://user-images.githubusercontent.com/37537223/39999461-1d7db144-57c4-11e8-955f-c57e6939c37f.png)
![2018-05-14 10 00 52](https://user-images.githubusercontent.com/37537223/39999465-20399cc2-57c4-11e8-8633-932c04348aeb.png)
![2018-05-14 10 13 37](https://user-images.githubusercontent.com/37537223/39999538-406a61d4-57c4-11e8-9441-7facb9652462.png)
![2018-05-14 10 09 27](https://user-images.githubusercontent.com/37537223/39999514-36c061ce-57c4-11e8-87dd-c067674c2334.png)

이지현
로그인 안되어있고 보드를 누르면 바로 로그인 페이지로 가욤

**Comment by ingyuseong** [comment]
성인규
![hw_devise2](https://user-images.githubusercontent.com/37537248/40002241-0d38c966-57cb-11e8-94c6-27b9d5910bcf.JPG)

**Comment by Jack2ee** [comment]
허재혁
git: https://github.com/Jack2ee/page/tree/master/page
![login](https://user-images.githubusercontent.com/37537235/40003148-879bcfbc-57cd-11e8-9732-85133324b4e4.PNG)

**Comment by preeminent77** [comment]
https://github.com/preeminent77/devise_homework
![image](https://user-images.githubusercontent.com/37537194/40004206-29a2e492-57d0-11e8-98e4-2951ac2cc6f4.png)

**Comment by YeChan1030** [comment]
![1](https://user-images.githubusercontent.com/37537205/40063785-0e734102-5899-11e8-83a3-6c064f6356f6.PNG)
![2](https://user-images.githubusercontent.com/37537205/40063787-0eb4b952-5899-11e8-8cda-62d3ed96dc3f.PNG)
![3](https://user-images.githubusercontent.com/37537205/40063788-0ef96d86-5899-11e8-9d4f-8dd1c047cb54.PNG)

**Comment by jason2133** [comment]
이재승

![6 1](https://user-images.githubusercontent.com/37537208/40133443-c59beb2c-597a-11e8-88f9-620f5ab8f61e.png)
![6 2](https://user-images.githubusercontent.com/37537208/40133445-c657a420-597a-11e8-992b-c07da332b92c.png)
![6 3](https://user-images.githubusercontent.com/37537208/40133446-c79e7426-597a-11e8-9cfd-c534ab50a265.png)

이재승

**Comment by lsy044** [comment]
![image](https://user-images.githubusercontent.com/37537202/40156785-914c617e-59d6-11e8-8850-cba9ee3b712f.png)
![image](https://user-images.githubusercontent.com/37537202/40156810-a9f61788-59d6-11e8-84be-7f7378d493db.png)

**Comment by lsy044** [comment]
![image](https://user-images.githubusercontent.com/37537202/40156853-d355c90c-59d6-11e8-8e96-a1959c0a83da.png)
![image](https://user-images.githubusercontent.com/37537202/40156865-df63fd4a-59d6-11e8-8e4d-7833771776ee.png)
이수영

**Comment by swimmie0** [comment]
![image](https://user-images.githubusercontent.com/37537202/40156905-161351c4-59d7-11e8-81ee-7b216d8c3591.png)
![image](https://user-images.githubusercontent.com/37537202/40157051-dd57b68a-59d7-11e8-9845-64cb908c38b1.png)

이수영
