### ISSUE TITLE
Special Session 1부 마무리

### ISSUE THREAD

**Issue by woonjangahn** [NEXT-LIKELION/Assignment#11]
Instagram Mock Page
스크린샷을 올려주세요!
![adsf](https://user-images.githubusercontent.com/26547475/39963797-cc90963e-56b0-11e8-9aa0-3fd162f8eabd.png)

**Comment by gyeol1212** [comment]
신한결
![2018-05-13 2 05 14](https://user-images.githubusercontent.com/37537201/39964067-b49bd4c0-56b6-11e8-9e89-8eced79364f8.png)

**Comment by X3PY** [comment]
전준표
![c](https://user-images.githubusercontent.com/37537209/39964165-059d9c6c-56b9-11e8-8b84-cd6e80754960.PNG)

**Comment by ghost** [comment]
장민규입니다 !
<img width="960" alt="2" src="https://user-images.githubusercontent.com/37537219/39963810-21447434-56b1-11e8-9aa0-d3c894b85d41.PNG">

**Comment by Hyezzi** [comment]
![image](https://user-images.githubusercontent.com/37537222/39963906-9ae99e98-56b3-11e8-9c06-38d5027866e5.png)
원혜진

**Comment by jiwonny** [comment]
![image](https://user-images.githubusercontent.com/37537213/39963913-d0dfca4a-56b3-11e8-8b79-19b117eae78b.png)

**Comment by swimmie0** [comment]
![image](https://user-images.githubusercontent.com/37537202/39963930-373cdf8a-56b4-11e8-8cb6-19ec1dc75298.png)

**Comment by soonjune** [comment]
박승준
<img width="1279" alt="2018-05-13 1 53 34" src="https://user-images.githubusercontent.com/37537242/39963990-4179cb88-56b5-11e8-8c7a-6c8ab7aaa68f.png">

**Comment by daisybae** [comment]
![image](https://user-images.githubusercontent.com/37537214/39964034-12c77726-56b6-11e8-9bbc-99d96ccb4907.png)

**Comment by daisybae** [comment]
![image](https://user-images.githubusercontent.com/37537214/39964174-43349134-56b9-11e8-896b-6b0cbde6fe5d.png)

**Comment by qlqnf16** [comment]
이정민

<img width="960" alt="2018-05-13 4" src="https://user-images.githubusercontent.com/37537216/39964048-5b313ea2-56b6-11e8-828f-0cf4d4674344.png">

**Comment by ingyuseong** [comment]
성인규
![image](https://user-images.githubusercontent.com/37537248/39964052-7889e76a-56b6-11e8-9d74-a7a1c4928285.png)

**Comment by Jack2ee** [comment]
허재혁
![default](https://user-images.githubusercontent.com/37537235/39964055-8913666a-56b6-11e8-8bf9-d3a6f84d9d65.PNG)

**Comment by hy970723** [comment]
<img width="1440" alt="2018-05-13 2 04 14" src="https://user-images.githubusercontent.com/37537254/39964062-9913ab88-56b6-11e8-9f53-08f16533110f.png">

**Comment by JIHYUN1110** [comment]
![special_1](https://user-images.githubusercontent.com/37537212/39964071-bc95d9e6-56b6-11e8-94ec-a35a411080d8.PNG)

**Comment by seona-yu** [comment]
유선아
<img width="947" alt="likelion instagram" src="https://user-images.githubusercontent.com/37537217/39964706-64c1ad4e-56c5-11e8-8f14-9582ff3855a1.png">

**Comment by jason2133** [comment]
이재승

위치조정하고 크기만 조절하면 되는... 곧 보완하겠습니다ㅜ-ㅜ

수정 중

이재승

**Comment by hyunjaeyou** [comment]
유현재입니다
![insta1](https://user-images.githubusercontent.com/37537210/39964233-01172530-56bb-11e8-8abb-1af0d9adfc37.png)
![insta2](https://user-images.githubusercontent.com/37537210/39964234-02228f78-56bb-11e8-9571-dd4c208954e6.png)

**Comment by preeminent77** [comment]
![image](https://user-images.githubusercontent.com/37537194/39964086-18ac9f80-56b7-11e8-9f84-c0e0067f1404.png)

**Comment by emilyson** [comment]
![image](https://user-images.githubusercontent.com/37537203/39964132-4078b1b0-56b8-11e8-94e7-9f41a40fcd25.png)

**Comment by YeChan1030** [comment]
![1](https://user-images.githubusercontent.com/37537205/39964244-527d7622-56bb-11e8-874b-7f9caade0949.PNG)
![2](https://user-images.githubusercontent.com/37537205/39964245-52a712a2-56bb-11e8-8282-eea650130eb9.PNG)



신예찬

**Comment by mhbest** [comment]
![image](https://user-images.githubusercontent.com/37537238/39964345-7794ef24-56bd-11e8-9eb3-891882de13a9.png)

**Comment by PoSungKim** [comment]
김보성
![instagram](https://user-images.githubusercontent.com/37537227/39965362-446f1416-56d2-11e8-95c5-bdfb576f9bbb.jpg)
