### ISSUE TITLE
Special Session 2부 마무리

### ISSUE THREAD

**Issue by woonjangahn** [NEXT-LIKELION/Assignment#12]
스페셜 세션 2부 때 진행했던 로또 알고리즘, 연습문제 등의 프로그램을 캡쳐해서 올려주시기 바랍니다.
Special Session 2부 출석체크 대용으로 진행됩니다.

**Comment by gyeol1212** [comment]
신한결
https://github.com/gyeol1212/lotto

**Comment by Jack2ee** [comment]
허재혁
https://github.com/Jack2ee/specialsession

**Comment by jihyuunn** [comment]
![2018-05-21 6 37 37](https://user-images.githubusercontent.com/37537223/40301122-128e4d36-5d26-11e8-9ac9-5df842f8b14b.png)
이지현

**Comment by JIHYUN1110** [comment]
김지현

![default](https://user-images.githubusercontent.com/37537212/40301341-ca8f502e-5d26-11e8-9d18-c784f9b64407.PNG)

**Comment by YeChan1030** [comment]
![1](https://user-images.githubusercontent.com/37537205/40304423-ac7c3e98-5d31-11e8-9ad5-850291d6b341.PNG)

**Comment by qlqnf16** [comment]
이정민

<img width="708" alt="2018-05-21 2" src="https://user-images.githubusercontent.com/37537216/40307043-fd3b2de4-5d3b-11e8-8f43-56c4bc74e191.png">

**Comment by seona-yu** [comment]
유선아
<img width="486" alt="lotto1" src="https://user-images.githubusercontent.com/37537217/40358743-4106a246-5dfb-11e8-8c63-10bcbdafcd48.png">
<img width="572" alt="lotto2" src="https://user-images.githubusercontent.com/37537217/40358745-4646dff0-5dfb-11e8-8278-48e716e4bda2.png">

**Comment by ssng123** [comment]
태엽 님의 도움으로 우분투 환경설정 했습니다..! 이제 아주 잘 돌아가네요 @.@
![image](https://user-images.githubusercontent.com/37537241/40436074-1a7c3198-5eed-11e8-953a-4ca2ed0ffd44.png)

**Comment by ingyuseong** [comment]
성인규
![specialsession](https://user-images.githubusercontent.com/37537248/40440290-a03b89fe-5ef8-11e8-8a51-7a793e112878.JPG)
![specialsession2](https://user-images.githubusercontent.com/37537248/40440291-a30bab6e-5ef8-11e8-85a3-567ac5c11ecf.JPG)

**Comment by X3PY** [comment]
![default](https://user-images.githubusercontent.com/37537209/40462295-4f7167a8-5f4a-11e8-89a4-90baab2100c2.PNG)
![2](https://user-images.githubusercontent.com/37537209/40462296-4fa1759c-5f4a-11e8-9ff6-af3fc25a21cb.PNG)

**Comment by Hyejoojjang** [comment]
https://github.com/Hyejoojjang/lottery.git
