### ISSUE TITLE
미니 해커톤 마무리

### ISSUE THREAD

**Issue by woonjangahn** [NEXT-LIKELION/Assignment#13]
1. 각 팀들의 대표는 각 팀의 서비스 화면 캡쳐 + 서비스 소개 정리해서 올려주세요.
2. 서비스 소개랑 들어간 기술들을 bullet point로 써주세요. (ex.) Ajax, 해시 소팅, 로그인 devise 등)

**Comment by gyeol1212** [comment]
6조 아마겟돈 (신예찬, 신한결, 이수영, 이재승, 최희윤)

![2018-05-21 2 00 59](https://user-images.githubusercontent.com/37537201/40293527-4b7695d2-5d0c-11e8-8c6f-a9b695a406d9.png)
![2018-05-21 2 02 29](https://user-images.githubusercontent.com/37537201/40293531-4ffe52e8-5d0c-11e8-8364-ad6e8e6c7ac8.png)
![2018-05-21 2 01 22](https://user-images.githubusercontent.com/37537201/40293530-4ec057fa-5d0c-11e8-8a32-a97198b7e1e4.png)

'아마겟돈'은 '아마도 우리는 돈을 Get할 것이다' 라는 뜻으로, 여러 단체에서 활동하고 있는 총무들을 위한 웹 서비스입니다. 
대부분의 단체에서 필수적인 존재인 총무들은 비록 눈에 보이지 않을지라도 각종 행사의 예산, 결산을 짜서 행사를 기획하고, 각종 뒤풀이 또는 회식에서 계산을 담당하는 등 단체를 위해 열심히 일하고 있습니다. 이런 총무들이 주로 맡는 예결산 기획, 뒤풀이 정산과 같은 일은 어렵고 복잡하다기 보단, 비슷한 양식의 반복적인 작성과 인원 별로 입금 여부를 확인하는 다소 귀찮은 일입니다. 
저희는 이런 총무들이 어떻게 하면 조금 더 일을 편하고 쉽게 할 수 있을까 고민한 끝에 '아마겟돈'을 만들었습니다.
'아마겟돈'은 크게 두개의 파트로 나뉘어 있습니다. 먼저 'Dutch Pay'에서는  먼저 계산을 한 뒤 인원 수로 나누어 돈을 입금받는 경우, 입금 여부의 확인을 쉽게 하기위한 기능을 만들었습니다. 그리고 'Budget Plan'에서는 행사 기획을 할 때 필요한 양식을 제공하여, 항상 엑셀에 양식을 만들어 작성하는 귀찮음을 해소하고자 하였습니다.

• Ruby on rails 를 이용하여 전체적인 페이지 제작
아마겟돈은 'Ruby on rails' 를 이용하여 전체적인 페이지를 제작하였습니다. Scaffold를 이용한 게시판시스템 구현 및 1:N 모델을 다수 이용하여 파트별 게시물내에 Table과 댓글, 명단을 각각 적용하였습니다. 'Dutch Pay'파트에서는 편의성을 좀 더 증대시키기 위해 이름을 입력할 때, 공백여부와 상관없이 ' , ' 를 기준으로 이름을 구분하여 자동으로 리스트에 추가하도록 모델을 구성하였고, One Button Click으로 입금여부를 기록할 수 있도록 만들었습니다. 'Budget Plan'파트에서는 상단의 입력창에 내용을 기입하면 자동으로 아래의 Table에 채워지도록 모델을 구성하였고, 각 항목별 총액과 전체 총액 그리고 인원별 금액이 자동으로 계산 되도록 만들었습니다. 그리고 게시판 내 검색 기능 또한 rails를 이용하여 제작하였습니다

• Devise gem을 이용하여 로그인 시스템 구현 
Devise gem을 적용하여 페이지의 기능을 이용하기 위해서 선 로그인이 필수적이도록 만들었습니다. 또한 로그인한 ㅅ용자를 인식하여 자신이 쓴 글만 우선적으로 보이도록 하였으며, 모든 사용자의 글을 모아보는 페이지를 따로 만들었습니다. 그리고 자신이 쓴 글만 수정, 삭제가 가능하도록 하였습니다.

• Javascript를 이용하여 특정부분 Show/Hidden기능 버튼 구현
'Budget Plan'파트의 Table을 작성하는 페이지에서 필요에 따라 입력하는 폼을 포함하여 불필요한 부분을 숨겨 좀더 깔끔한 모양으로 캡쳐할 수 있도록 하기 위하여, 'Javascript'를 이용해 버튼 클릭으로 특정 부분을 숨기는 기능을 구현하였습니다.

**Comment by soonjune** [comment]
3조 KUSKET (박승준, 유현재, 유정아, 원혜진, 장민규)

다음 2학기부터 우리학교 수강신청 제도가 바뀝니다.
http://www.kunews.ac.kr/news/articleView.html?idxno=25000
내가 수강희망과목으로 등록한 강의가 해당 강의의 수강 제한 인원보다 작거나 같으면 자동으로 수강신청이 되고 초과하는 과목에 대해서만 수강신청을 하는 것이 새 수강신청 제도의 골자입니다.

새로운 수강신청 제도 하에서는 과목의 경쟁률을 파악해서 수강희망 인원이 정원을 초과할 것인지 확인하는 것이 매우 중요하다고 할 수 있습니다. 저희 KUSKET 팀은 이러한 필요성에 착안하여 수강희망과목 신청을 미리해보고 경쟁률을 알려주는 서비스를 고안했습니다.

<img width="1279" alt="2018-05-21 6 27 19" src="https://user-images.githubusercontent.com/37537242/40300856-6cac161e-5d25-11e8-9f58-1dfa96aa3258.png">
<img width="1280" alt="2018-05-21 6 28 07" src="https://user-images.githubusercontent.com/37537242/40300866-74abdb7e-5d25-11e8-84e6-158cae5aa18d.png">
<img width="1280" alt="2018-05-21 6 28 19" src="https://user-images.githubusercontent.com/37537242/40300874-771e3a00-5d25-11e8-909f-269270d4a8df.png">
<img width="1280" alt="2018-05-21 6 28 43" src="https://user-images.githubusercontent.com/37537242/40300879-78f8a090-5d25-11e8-8178-3162fee3a77e.png">

회원가입을 하고 내가 듣고자 하는 과목을 담은 뒤 확정 버튼을 누르면 내가 선택한 과목의 경쟁률을 마이페이지에서 확인할 수 있습니다. 아주 간단하면서도 꼭 필요한 서비스가 아닐 수 없습니다.

• MVC framework를 이용한 페이지 구현
Ruby on rails를 이용하여 페이지를 제작하였습니다.

• Devise gem을 이용한 회원가입 및 로그인 시스템 구현
Devise gem을 이용하여 회원가입을 하고 사용자 모델을 수정하여 로그인한 사용자가 수강신청한 과목을 담을 수 있도록 하였습니다.

• Nokogiri gem을 이용한 수강신청 로스터 크롤링
Nokogiri gem을 이용하여 고려대학교 수강신청 사이트의 과목 정보를 크롤링하여 모델에 담은 뒤 경쟁률 페이지에 표시하였습니다.

**Comment by dkor3** [comment]
1조 (안성수, 이정민, 김보성, 허예림, 이지원, 주기현) 

두손은 짐보관 플랫폼으로서 여행자들의 편의를 위한 웹서비스입니다. 
각 가게들의 유휴 공간을 활용하여 여행자들의 편의를 도모함과 동시에 가게의 부가수익 창출에 기여할 수 있는 혁신적인 모델입니다. 
![image](https://user-images.githubusercontent.com/37537204/40307241-ae25fd8c-5d3c-11e8-9f2c-3f2b20ee329b.png)


• MVC framework를 이용한 페이지 구현
Ruby on rails를 이용하여 페이지를 제작하였습니다.

• Devise gem을 이용한 회원가입 및 로그인 시스템 구현
Devise gem을 이용하여 회원가입을 하고 사용자 모델을 수정하여 로그인한 사용자가 수강신청한 과목을 담을 수 있도록 하였습니다.

• 구글맵 API를 사용하여 원하는 지역에 PIN 설치 가능 

• 날짜를 기반으로 게시판 내에 검색 가능한 기능 

• 승인된 자만 게시판을 사용할 수 있는 기능과 게시판에 있는 특정내용을 볼 수 있는 기능

**Comment by sangw0804** [comment]
4조 (김지현, 방혜주, 손지연, 오상우, 전재현)

반려견들을 위한 데이트, 친구매칭 서비스입니다!

![image](https://user-images.githubusercontent.com/37537207/40312863-00f275d8-5d4f-11e8-913d-402178d01616.png)
![image](https://user-images.githubusercontent.com/37537207/40312879-0bd5423c-5d4f-11e8-97ab-70fa5355089a.png)
![image](https://user-images.githubusercontent.com/37537207/40312884-1429d6dc-5d4f-11e8-99cc-ee33fa53090f.png)
![image](https://user-images.githubusercontent.com/37537207/40312809-ec132626-5d4e-11e8-8495-31f7d465712f.png)

1. ror 프레임워크로 사이트 설계
2. 유저 매칭 시스템을 위한 데이터베이스 랜덤/필터 추출
3. Ajax를 이용한 쪽지 ui
4. 자동 매칭 확인 시스템

**Comment by seona-yu** [comment]
2조 (김지현, 배영현, 성인규, 유선아, 허재혁)

평범한 사람도 특별해 보이고 싶은 날이 있다!
메이크업 전문가가 아니지만 메이크업을 잘하는 주변 사람들이 많은 요즘.
메이크업이 필요한 사람과 메이크업을 잘하는 일반인을 연결해줍니다.
1:1 메이크업 매칭 사이트입니다!

<img width="958" alt="miniton2" src="https://user-images.githubusercontent.com/37537217/40361144-4f4c945c-5e03-11e8-9195-aca76443dd47.png">

<img width="949" alt="miniton4" src="https://user-images.githubusercontent.com/37537217/40361167-5b981de4-5e03-11e8-84c9-65126b0406e2.png">

<img width="917" alt="miniton8" src="https://user-images.githubusercontent.com/37537217/40361500-7d80911a-5e04-11e8-99e1-9bd2c78bd8bc.png">

<img width="883" alt="miniton6" src="https://user-images.githubusercontent.com/37537217/40361191-73c8f6d6-5e03-11e8-9d31-2fff88244665.png">
<img width="935" alt="miniton7" src="https://user-images.githubusercontent.com/37537217/40361197-7787b000-5e03-11e8-82d5-b0a2e1f17214.png">

• MVC framework를 이용한 페이지 구현
Ruby on rails를 이용하여 CHAL DDUCK, Follow, Message, Review, Post, Post_Tag, Tag, User 모델 구현,
페이지를 제작하였습니다.

• Devise gem을 이용한 회원가입 및 로그인 시스템 구현
Devise gem을 이용하여 회원가입을 하고 사용자 모델을 수정하여 로그인한 사용자가 
메이크업 서비스를 이용할 수 있도록 하였습니다.

• Carrierwave, mini_magick Gem을 이용한 이미지 포스팅 기능 구현하였습니다.

• Hashtag 기능 구현
 포스팅에 대한 내용을 Hashtag로 간편하게 요약하고 검색 &
 Post, Post_Tag, Tag모델을 기반으로 User들이 전체 포스팅 내에서 가장 많이 Tag한 Top5 Hashtag 를 가져오는 기능 구현하였습니다.

•  좋아요 기능 &구글 지도와 캘린더 구현하였습니다.

• 승인된 자만 쪽지함을 사용할 수 있는 기능과 쪽지함에 있는 내용을 볼 수 있는 기능이 있습니다.

**Comment by norrard148** [comment]
![5](https://user-images.githubusercontent.com/37537262/40398997-dcea3fc2-5e75-11e8-8e44-db5b28784af4.PNG)
![1](https://user-images.githubusercontent.com/37537262/40398998-dd273c06-5e75-11e8-9ddd-52f81a20c9a8.PNG)
![2](https://user-images.githubusercontent.com/37537262/40398999-dd522c18-5e75-11e8-8f30-a553573b91e5.PNG)
![3](https://user-images.githubusercontent.com/37537262/40399000-ddaefb3c-5e75-11e8-9545-5c39aa1930fb.PNG)
![4](https://user-images.githubusercontent.com/37537262/40399013-fa81c91a-5e75-11e8-841c-5ac05debc018.PNG)
![7](https://user-images.githubusercontent.com/37537262/40399139-9ac701f6-5e76-11e8-8177-dff95b28e172.PNG)


늦어서 죄송합니다~!!!

1. 검색 기능 구현
 메인 페이지에 검색하고 싶은 키워드나 태그 네임을 치면 알아서 검색을 해줍니다.

2.  좋아요 기능 구현
글마다 좋아요를 누르면 좋아요 개수가 표시되고 하트가 채워집니다.

3. Carrierwave 및 magick 젬을 이용한 이미지 업로드 역시 가능하도록 하였습니다.

4. Devise젬을 통해 로그인 시스템 역시 담았습니다.

5. 여러분에 대한 사랑 역시 담았습니다~ ㅎㅎ
