### ISSUE TITLE
7주차 과제

### ISSUE THREAD

**Issue by skywoo1994** [NEXT-LIKELION/Assignment#14]
안녕하세요!
모두들 미니톤 끝나고 계속해서 잘 따라와주셔서 감사합니다 :)
이번 과제는 많이 어렵지 않을거에요~ 소스코드를 바탕으로 만드시면 되겠습니다.
우선 올려드릴 자료는
1. 오늘 강의안
2. 작년 크롤링 강의안
3. 작년 크롤링 강의안_코드
입니다.
여러분이 하실 일은 바로 안암학사의 식단표를 긁어오는 것인데요,
작년 강의안을 보시면 산학관의 식단표를 긁어온 것을 확인할 수 있어요.
작년 강의안 산학관 식단표와 동일한 형태로 안암학사의 식단표를 크롤링해오시면 되겠습니다.
하신 이후에는 로컬에서 돌아가는 페이지를 스크린샷해서 올리시면 되겠습니다. 작년 강의안을 보면 산학관 식단표를 어떻게 가져왔는지 확인할 수 있습니다.
**강의안_코드, 그리고 강의안에 토요일 "오류"라는 부분이 있습니다. 바로 중간에 형태가 바뀌는 날짜가 있으니 그 부분을 유의해서 고쳐서 해야한다는 내용으로 이해하시면 되겠습니다.
[2017 크롤링 강의안_코드.pdf](https://github.com/NEXT-LIKELION/Assignment/files/2023714/2017._.pdf)
[2017 크롤링 강의안.pdf](https://github.com/NEXT-LIKELION/Assignment/files/2023715/2017.pdf)
[7주차 세션_크롤링 강의.pdf](https://github.com/NEXT-LIKELION/Assignment/files/2023716/7._.pdf)

화이팅!!

**Comment by soonjune** [comment]
박승준
<img width="1278" alt="2018-05-22 3 03 31" src="https://user-images.githubusercontent.com/37537242/40344786-5b20cfe6-5dd1-11e8-9308-26ac9c2f28b7.png">

**Comment by gyeol1212** [comment]
신한결
![2018-05-23 1 37 39](https://user-images.githubusercontent.com/37537201/40403699-892eb818-5e8e-11e8-8fca-44f3b852f112.png)

**Comment by seona-yu** [comment]
유선아
<img width="940" alt="crawling1" src="https://user-images.githubusercontent.com/37537217/40403156-f6daf920-5e8a-11e8-8616-bd66af5de9b3.png">

**Comment by JIHYUN1110** [comment]
김지현

![_](https://user-images.githubusercontent.com/37537212/40410653-53158f52-5ea9-11e8-8b01-1e796252858a.PNG)

**Comment by norrard148** [comment]
장영재
![sdsd](https://user-images.githubusercontent.com/37537262/40421581-5e5a1c0c-5ec7-11e8-9011-7db25969d497.PNG)

**Comment by kihyunjoo** [comment]
주기현 [
<img width="1648" alt="screen shot 2018-05-23 at 8 41 47 pm" src="https://user-images.githubusercontent.com/37537229/40422281-d6085fe6-5ec9-11e8-8217-d06a61ba524c.png">
](url)

**Comment by Jack2ee** [comment]
허재혁
![menu](https://user-images.githubusercontent.com/37537235/40425165-85f78190-5ed2-11e8-8924-66e0cab9c20d.PNG)

**Comment by ingyuseong** [comment]
성인규
![hw_crawiling](https://user-images.githubusercontent.com/37537248/40440866-2d085514-5efa-11e8-82d6-67fcb9908b69.JPG)

**Comment by qlqnf16** [comment]
이정민

<img width="960" alt="2018-05-24 4" src="https://user-images.githubusercontent.com/37537216/40442059-b0f0efdc-5efd-11e8-968e-103be273d8a7.png">

**Comment by jihyuunn** [comment]
![2018-05-24 2 03 43](https://user-images.githubusercontent.com/37537223/40465419-867c333e-5f5b-11e8-8e52-61d873b83716.png)
이지현

**Comment by ghost** [comment]
장민규
<img width="960" alt="1" src="https://user-images.githubusercontent.com/37537219/40469784-92cc31be-5f6c-11e8-9f70-55e1f4cb8595.PNG">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/37537219/40469788-944218f6-5f6c-11e8-81b4-d7eeb923b46e.PNG">

**Comment by Cecilia-L** [comment]
이윤비
완료한건 3시간전인데 아무리 코드를 다시봐도 표가....절대 안떠요.......ㅠㅠㅠㅠㅠㅠㅠ
<img width="960" alt="default" src="https://user-images.githubusercontent.com/37537232/40471511-e3732e42-5f71-11e8-9273-b02e053ca3e3.PNG">

**Comment by hyunjaeyou** [comment]
유현재입니다
![default](https://user-images.githubusercontent.com/37537210/40471945-1a2c0a48-5f73-11e8-98c3-3ed26d94bdb9.png)

**Comment by X3PY** [comment]
![14](https://user-images.githubusercontent.com/37537209/40475310-404e62ee-5f7c-11e8-9842-7bc630e15ae6.png)


전준표

**Comment by ashufflepuff** [comment]
유정아
<img width="807" alt="default" src="https://user-images.githubusercontent.com/37537211/40475003-63bd63ca-5f7b-11e8-81c9-44134ce8176b.PNG">

**Comment by swimmie0** [comment]
![image](https://user-images.githubusercontent.com/37537202/40475948-c7968e42-5f7d-11e8-8b2d-95e1df1e5547.png)
이수영

**Comment by PoSungKim** [comment]
김보성
![_ _ 1](https://user-images.githubusercontent.com/37537227/40476521-3593f032-5f7f-11e8-9fa3-f6bb0cdfaebc.PNG)

**Comment by preeminent77** [comment]
![image](https://user-images.githubusercontent.com/37537194/40477755-335441fc-5f82-11e8-9251-df61c1b39c77.png)
전재현입니다.

**Comment by sangw0804** [comment]
오상우
![image](https://user-images.githubusercontent.com/37537207/40497580-894ffd82-5fb7-11e8-889c-b845025bf845.png)

**Comment by Yerim2695** [comment]
허예림

![image](https://user-images.githubusercontent.com/37537200/40480963-f088ba7a-5f8a-11e8-8013-141dd1138cdf.png)

**Comment by YeChan1030** [comment]
![1](https://user-images.githubusercontent.com/37537205/40480907-cc561472-5f8a-11e8-9bc8-708c52e85770.PNG)

신예찬

**Comment by Hyejoojjang** [comment]
<img width="1280" alt="2018-05-28 1 49 20" src="https://user-images.githubusercontent.com/37541410/40588523-747e548a-6219-11e8-9b5b-caf86950b91b.png">

**Comment by daisybae** [comment]
배영현 rails db:drop에게 이 공을 돌립니다...
![image](https://user-images.githubusercontent.com/37537214/40589593-dd1fccc4-622a-11e8-9e5f-e32bb66f861f.png)

**Comment by mhbest** [comment]
김민형
- 밥이 없나봐요 ㅎㅎㅎ
![image](https://user-images.githubusercontent.com/37537238/40592014-0d50cd92-6255-11e8-807a-7c04616dffcf.png)

**Comment by jason2133** [comment]
![default](https://user-images.githubusercontent.com/37537208/40597288-7e2a7c4a-627b-11e8-9b1f-b05f9da79216.png)

이재승

아 신난다 1시간만에 클리어 드디어 됐드아~~~~~~

**Comment by jiwonny** [comment]
이지원
![image](https://user-images.githubusercontent.com/37537213/40599412-18c80ab8-6288-11e8-89ff-a26842c9e157.png)

**Comment by emilyson** [comment]
![image](https://user-images.githubusercontent.com/37537203/40599724-8dd3c922-6289-11e8-9869-74792df9cd34.png)
손지연

**Comment by Hyezzi** [comment]
![image](https://user-images.githubusercontent.com/37537222/40600269-c72dd026-628b-11e8-9221-def73b78d974.png)

원혜진

**Comment by dkor3** [comment]
![2](https://user-images.githubusercontent.com/37537204/40600503-9f4238c6-628c-11e8-8d2c-50a6c9c64e14.png)
