### ISSUE TITLE
8주차 과제(2) - API 활용하기

### ISSUE THREAD

**Issue by woonjangahn** [NEXT-LIKELION/Assignment#15]
세션 때 설명했듯 (불참자는 단톡방이나 친구들한테 물어보세요.)
API를 이용해 유의미한 데이터를 찾아 응용하는 것이 과제입니다.

1. 1개 이상의 API를 활용하고, (공공데이터포탈 이용을 추천합니다. 사용법도 숙지할 겸!)
2. 이를 이용해 Rails 프로젝트를 만들어주세요.
3. API 출처와 데이터를 어떻게 활용했는지에 대한 설명을 덧붙여주시고
4. 언제나 그랬듯 캡쳐화면을 올려주시기 바랍니다.
4-1. Git에 업로드 하는 경우 API KEY를 figaro gem을 써서 gitignore 되게 해주시기 바랍니다.
5. 기한은 5월 31일 목요일 세션 전까지입니다.
6. 추가 공지: 이번 과제는 특별히 3인 이하 팀을 허용하겠습니다. 단, 팀의 각각 개인이 어떤 부분에서 어떤 역할을 했는지 과제 제출 시 추가로 작성해주시기 바랍니다.

+ Windows 유저들은 WSL을 이용해 Ubuntu를 설치하고 ruby와 rails 역시 설치해주시기 바랍니다.

**Comment by gyeol1212** [comment]
신한결
![2018-05-26 1 42 26](https://user-images.githubusercontent.com/37537201/40556190-b7e8f9ee-6086-11e8-9dba-9a49f01d0327.png)
![2018-05-26 1 42 41](https://user-images.githubusercontent.com/37537201/40556195-bae482b2-6086-11e8-9db5-187482717d67.png)
![2018-05-26 1 42 47](https://user-images.githubusercontent.com/37537201/40556197-bc7b4ae8-6086-11e8-9178-726bbe9a7b9d.png)

라이엇에서 제공하는 api를 활용하여 현재 랭크 Top3의 최근 다섯경기 전적을 가져와 간단하게 게임참여자들과 픽한 챔피언 KDA 평점을 보여주는... OP.GG의 발끝에도 못미치는 사이트 입니다.

api 출처는 riotgames에서 제공해주는 api를 사용했고
1.현재 챌린저리그의 player_name을 불러오는 api
2. player_name을 통해 player_id를 찾기 위한 플레이어정보 api
3. player_id를 통해 최근 전적을 불러오는 api
4. game_id를 통해 해당 게임의 정보를 불러오는 api
5. champion_id를 통해 챔피언이름을 찾기 위한 챔피언정보 api
의 api를 이용했습니다.

**Comment by norrard148** [comment]
장영재


![vvvcvccx](https://user-images.githubusercontent.com/37537262/40612186-7cadfaca-62b4-11e8-87f1-dc56adb33676.PNG)

![cccccdd](https://user-images.githubusercontent.com/37537262/40598028-40f46af2-6280-11e8-8964-ec65132155f2.PNG)

듣거나 보고싶은 음악만 치면 바로 들을 수 있도록!  귀찮게 목록을 찾아서 봐야 한다면 불편하잖습니까. 계속 업그레이드해서 올리겠습니다.

1. youtube의 IFrame player API와 data API v3를 사용했습니다.
검색을 하면 바로 내용에 따라 가장 많이 검색된 1순위의 내용이 자동으로 시연되도록 했습니다.

**Comment by sangw0804** [comment]
오상우
![image](https://user-images.githubusercontent.com/37537207/40573331-0dc34da0-60fb-11e8-879d-fc6f024cbabd.png)
![image](https://user-images.githubusercontent.com/37537207/40573383-bae00e60-60fb-11e8-80bc-48bc618a0b07.png)

위기의 순간에 당신을 구해드립니다!

1. 구글 맵 api
2. 서울시 공중화장실 위치정보 데이터 api

위치를 검색 할 때마다 공중화장실 데이터에서 해당 범위내의 화장실만을 마커로 보여줍니다.

**Comment by PoSungKim** [comment]
김보성
1. 네이버 API를 사용하여, 네이버 지식iN 검색 기능을 구현해 보았습니다.
2. 실제로, 검색 시 나오는 질문 글들이 네이버 지식iN에서 검색 시 나오는 질문 글들과 동일하다는 것을 알 수 있습니다.
3. 질문에 대한 답변을 확인하고 싶으면, 각 글 하단의 링크를 클릭하면 됩니다.

![_naver api_ 2](https://user-images.githubusercontent.com/37537227/40621695-d79d9688-62d8-11e8-9c49-fd7e980c63d7.PNG)
![_naver api_ 3](https://user-images.githubusercontent.com/37537227/40621697-d99f517e-62d8-11e8-985e-0f22bf38e014.PNG)
![_naver api_ 6](https://user-images.githubusercontent.com/37537227/40621701-dcf9f1da-62d8-11e8-983f-9717fb826289.PNG)
![_naver api_ 4](https://user-images.githubusercontent.com/37537227/40621706-e088a56c-62d8-11e8-841f-17b640c47a7c.PNG)

**Comment by seona-yu** [comment]
유선아 

<img width="965" alt="api_homework2" src="https://user-images.githubusercontent.com/37537217/40659191-7be1b42c-6388-11e8-8670-f17a05346e00.png">


힐링되는 한국의 한옥을 여행의 숙소로 원하는 사람들을 위해! 

1. 공공데이터포털의 국내 관광정보 서비스 api
    중 <한옥 숙박> api 를 이용했습니다.

**Comment by qlqnf16** [comment]
이정민

<img width="959" alt="2018-05-30 2" src="https://user-images.githubusercontent.com/37537216/40677516-dcab51d4-63b8-11e8-9d6a-0293354d4226.png">
<img width="959" alt="2018-05-30 3" src="https://user-images.githubusercontent.com/37537216/40677517-dcd7fd92-63b8-11e8-837c-3b1a208573b0.png">

<일간 박스오피스 10위까지 모아보기>
1. 날짜를 통해 박스오피스 순위를 가져오는 API 사용
2. 영화코드로 영화 정보를 가져오는 API 사용
3. 날짜검색기능

**Comment by jason2133** [comment]
![api 1](https://user-images.githubusercontent.com/37537208/40705144-15a1dfaa-6425-11e8-8215-442a62105e81.png)
![api 2](https://user-images.githubusercontent.com/37537208/40705145-1639d152-6425-11e8-863d-4750207170f0.png)

이재승

1. 경기도 수원시 평생학습강좌 정보 데이터 api
수원시 평생교육학습강좌 공공데이터 api를 가져와서
그 강좌에 대한 정보를 제공해주는 것을 만들어보았습니다.

**Comment by Jack2ee** [comment]
박승준 허재혁

![default](https://user-images.githubusercontent.com/37537235/40759132-a10b36e4-64cb-11e8-97c6-01b41419fbec.PNG)
![default](https://user-images.githubusercontent.com/37537235/40759356-ada2a80a-64cc-11e8-99b4-266986c12b50.PNG)

![3](https://user-images.githubusercontent.com/37537235/40759137-a3bf86ce-64cb-11e8-9fc8-f384cd50d3a5.PNG)

자신이 위치해있는 위도와 경도만 알면 자신의 표준시간대와 세계표준시를 알 수 있는 서비스입니다.

구글 timezone api를 이용하였습니다.

**Comment by sangw0804** [comment]
전재현 유현재 오상우

![image](https://user-images.githubusercontent.com/37537207/40762454-f0643280-64db-11e8-8429-099f968e6756.png)
![image](https://user-images.githubusercontent.com/37537207/40762457-f3c1ea30-64db-11e8-8a3e-ad8857501ff1.png)
![image](https://user-images.githubusercontent.com/37537207/40762463-f6ced40e-64db-11e8-96d2-9f848a72e846.png)
![image](https://user-images.githubusercontent.com/37537207/40762471-fa3fca08-64db-11e8-83e6-9f530bccb2a4.png)

서울시 데이터광장의 신규통신판매사업자등록 API를 이용해 회원들에게 제공하는 웹 서비스입니다.

**Comment by ghost** [comment]
장민규
정부3.0에서 제공하는 예측진료정보조회서비스 api 이용하였습니다.
<img width="960" alt="1" src="https://user-images.githubusercontent.com/37537219/40763805-307f9b70-64e1-11e8-8a46-c2b2f1083fc3.PNG">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/37537219/40763806-30c31ba2-64e1-11e8-9151-b4fe684e48d9.PNG">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/37537219/40763807-30ebf950-64e1-11e8-93b4-7bb685ec7f09.PNG">

**Comment by ingyuseong** [comment]
성인규
![hw_api](https://user-images.githubusercontent.com/37537248/40764164-e6b38f90-64e2-11e8-90d8-b586087d35a7.JPG)
트루스 오어 데어 진짜 핵노잼인데 네이버 평점이 8점대고 다 꿀잼이고 무서웠다는 댓글이더라고요..
평점알바들 짓인거 같아서 좀 제대로된 일반 관객들의 평점을 볼 수 있도록 알바들 다 거르고 새로 평점매기는 프로그램을 만들어봤습니다 그런데..
![hw_api3](https://user-images.githubusercontent.com/37537248/40764277-6aa467ca-64e3-11e8-8e92-55a63629b2a3.JPG)
![hw_api6](https://user-images.githubusercontent.com/37537248/40764284-6e893938-64e3-11e8-910b-a00186ce86a3.JPG)
![hw_api5](https://user-images.githubusercontent.com/37537248/40764308-84f90004-64e3-11e8-9405-5a3fd0f4f8c6.JPG)
일반인도 다 걸러지더라고요 ㅎ 평점도 많이 낮아지길 기대했는데 ㅠㅠ 그리고 마지막 페이지 렌더링되는 시간이 너무 오래걸려요.. 평점매긴사람이 몇천명 되서 그런가봐요 ㅠ 
직접쓰려고 만들어봤는데 망했네용 ㅎㅎ
네이버 영화 api랑 크롤링 썼습니다!

**Comment by JIHYUN1110** [comment]
김지현

![_api_1](https://user-images.githubusercontent.com/37537212/40766148-7a44f28e-64e9-11e8-93c8-453382d4dec2.PNG)

![_api_2](https://user-images.githubusercontent.com/37537212/40766155-7dc99b08-64e9-11e8-854e-5e55b4aac94a.PNG)

공휴일이 궁금해?
공공데이터포털의 특일 정보제공 서비스 api를 가져와서
공휴일 정보를 활용해 2018년의 남은 공휴일을 월별로 분류했습니다.

**Comment by JIHYUN1110** [comment]
김지현

![_api_1](https://user-images.githubusercontent.com/37537212/40766688-50b9ddec-64eb-11e8-9a77-8b355800ed4d.PNG)

![_api_2](https://user-images.githubusercontent.com/37537212/40766694-54484a5c-64eb-11e8-8229-8dda5fd8245c.PNG)

공휴일이 궁금해?
공공데이터포털의 특일 정보제공 서비스 api를 가져와서
공휴일 정보를 활용해 2018년의 남은 공휴일을 월별로 분류했습니다.

**Comment by Hyezzi** [comment]
![image](https://user-images.githubusercontent.com/37537222/40769062-fafce410-64f1-11e8-8ff3-e0bb9cab2f69.png)
원혜진

공공포털사이트에서 대기오염 api를 가져와서 사용햇습니다 :0
서울의 측정소별 미세먼지 현황을 알 수 있어욥

**Comment by X3PY** [comment]
![ass15](https://user-images.githubusercontent.com/37537209/40771237-c9593020-64f7-11e8-8442-288b2d56addb.png)

전준표 

공공데이터 포털의 한국 수출입은행 환율정보 API를 활용하여
실시간으로 환율을 확인할 수 있는 페이지를 만들었습니다.

**Comment by Hyejoojjang** [comment]
<img width="1280" alt="2018-05-31 6 38 45" src="https://user-images.githubusercontent.com/37541410/40774984-f16b1fc4-6501-11e8-84ea-4366dba327fe.png">

* 사용 자료: 인천공항 여객편 주간 운항 현황

진짜 떠나고 싶어서 만들어버린 실시간 인천공항발 운항 현황입니다.
떠나고 싶은 자는 가독성에 상관 없이 이 페이지를 좋아할 것입니다.

special thanks to. Heeham

**Comment by YeChan1030** [comment]
신예찬, 허예림


![1](https://user-images.githubusercontent.com/37537205/40775808-f03faa64-6503-11e8-984f-79fd02f233be.PNG)


![2](https://user-images.githubusercontent.com/37537205/40775809-f076d4c6-6503-11e8-83b9-e92675f5efa2.PNG)

![kakaotalk_20180531_185910179](https://user-images.githubusercontent.com/37537205/40776105-c3eca39e-6504-11e8-9ed1-298634aebe6e.png)



*영화검색 사이트 
1. 영화검색 페이지
-> 검색 form 구현

2. 영화검색 결과 페이지
-> 영화진흥위원회 open API 사용, 영화 검색 리스트 페이지 구현
-> 검색 버튼 누르면 index 같은 페이지에 결과창 나옴

3. 영화 상세 정보 페이지
-> 영화 결과 페이지에서 영화코드를 받아서 영화 코드로 영화 상세정보 검색. 
-> API 가져와서 영화  이미지와 함께 구현

**Comment by jiwonny** [comment]
![image](https://user-images.githubusercontent.com/37537213/40776272-44517640-6505-11e8-832f-304d0a36d523.png)
인천공항에서의 항공편
출발시간이 예정시간과 달라질 경우 출력하여 목록을 보여줌
바뀐 시간과 항공편 명을 알려줌

**Comment by swimmie0** [comment]
![image](https://user-images.githubusercontent.com/37537202/41086348-be97ce1c-6a74-11e8-8f86-1bc216231c20.png)
![image](https://user-images.githubusercontent.com/37537202/41086354-c2e67644-6a74-11e8-86c0-e43575bb045d.png)
