### ISSUE TITLE
 9주차 실습(2) 해설 및 과제 - AJAX

### ISSUE THREAD

**Issue by woonjangahn** [NEXT-LIKELION/Assignment#16]
1학기의 마지막 세션까지 마치신 여러분, 모두 수고하셨습니다.
세션 때 진행한 실습(2) jQuery 부분 해설을 첨부합니다.
![capture](https://user-images.githubusercontent.com/26547475/40935659-c1b5de2a-6873-11e8-8368-98fe7b326368.PNG)

9주차 과제 안내드립니다.

1. AJAX 개념을 찾아서 이해하고
2. jQuery API Documentation과 구글링을 통해 AJAX을 어떻게 사용하는지 알아보고
3. https://dog.ceo/api/breeds/image/random 의 JSON 파일을 이용해
4. 버튼을 누르면 새로운 멍멍이 사진을 가져오는 index.html 하나를 만들고
5. github에 새로운 repository를 만들어 push 해주시고 링크를 올려주시기 바랍니다.

**Comment by ingyuseong** [comment]
성인규
https://github.com/staycozyboy/AJAX_review

**Comment by qlqnf16** [comment]
이정민
https://github.com/qlqnf16/0604ajaxpractice

**Comment by gyeol1212** [comment]
신한결
https://github.com/gyeol1212/ajax

**Comment by JIHYUN1110** [comment]
김지현

https://github.com/JIHYUN1110/0605_AJAX

**Comment by sangw0804** [comment]
오상우
https://github.com/sangw0804/ajaxPractice

**Comment by norrard148** [comment]
장영재
https://github.com/norrard148/ajaax.git

**Comment by jihyuunn** [comment]
이지현
https://github.com/jihyuunn/AJAX-hw

**Comment by ghost** [comment]
장민규
https://github.com/MinkyuJ/ajax.git

**Comment by Hyezzi** [comment]
원혜진

https://github.com/Hyezzi/randomDogAjax

**Comment by Jack2ee** [comment]
허재혁
https://github.com/Jack2ee/ajax

**Comment by emilyson** [comment]
손지연
https://github.com/emilyson/B0607.git

**Comment by soonjune** [comment]
https://github.com/jamie7060/dogphoto

**Comment by hyunjaeyou** [comment]
https://github.com/hyunjaeyou/ajaxfuck

**Comment by mhbest** [comment]
김민형
https://github.com/mhbest/last-homework.git

**Comment by ashufflepuff** [comment]
유정아
https://github.com/ashufflepuff/ajax0607.git

**Comment by X3PY** [comment]
전준표
https://github.com/X3PY/AJAX

**Comment by swimmie0** [comment]
이수영
https://github.com/lsy044/ajax.git

**Comment by PoSungKim** [comment]
김보성
https://github.com/PoSungKim/AJAX_Practice.git

**Comment by seona-yu** [comment]
유선아
https://github.com/seona-yu/ajax_practice

**Comment by YeChan1030** [comment]
신예찬
https://github.com/YeChan1030/ajax.git

**Comment by Yerim2695** [comment]
허예림
https://github.com/Yerim2695/ajaxpractice.git
