### ISSUE TITLE
여름방학 Team Project 과제 (1): NEXT 홈페이지 만들기 (~7/19)

### ISSUE THREAD

**Issue by woonjangahn** [NEXT-LIKELION/Assignment#17]
안녕하세요, 여러분.

아이디어톤 및 중앙 해커톤 대비 팀은 만들어졌지만, 아직까지 서로의 역량이나 협업 능력을 확인하지는 못하셨을 것이라 예상됩니다. 그래서 Team으로서 수행할 과제들을 수행하며 여러가지 시행착오를 겪어보시고 실전 능력을 기르기 위해 과제를 드립니다.

방학 때 주어지는 몇 차례의 Team Project 과제에서는 세션 때 주어지는 개인 과제와 별개로 진행되며, 반드시 모든 팀원들이 참가하고 그 과정 (GitHub 협업 등의 기록 등)에 나타나야합니다.

첫번째 Team Project 과제는 <NEXT 공식 홈페이지> 입니다.

반드시 들어가야 하는 사항은 다음과 같습니다. (http://www.mccku.org/w/#/main 를 참고하였습니다.)
    - About : 단체에 대한 소개를 해주는 공간
    - Members : 기수별로 누가 있는지를 나타내는 공간. 사진과 간단한 자기소개 등이 있으면 좋습니다.
    - Recruit : 매년 또는 매학기 진행되는 리쿠르팅에 대한 안내
    - Member Lounge : 가입되어 있는 정회원들만 들어갈 수 있는 게시판

기획, UI/UX, Front-end, Back-end 등 각각의 분야를 나누어 지금까지 배운 모든 기술들 + 개인적으로 공부해서 배운 기술들을 모두 사용하여 최고의 작품을 위해 노력해주시기 바랍니다.

기한은 7월 19일 자정까지 팀장이 Github Repository를 만들어서 README.md 에 어떤 기술을 적용하였는지, 스크린샷 등을 포함해서 설명을 올려주신 후 과제 댓글에 링크를 달아주시면 됩니다.

궁금한 것이 있으면 스스로 공부해보고, 새롭게 알게 된 사실은 팀원들끼리 공유하며 모두가 발전하는 과제가 될 수 있길 바랍니다.

화이팅!

**Comment by norrard148** [comment]
http://18.222.132.5/

**Comment by norrard148** [comment]
팀 : KU성애

http://18.222.132.5

**Comment by norrard148** [comment]
4조 KU 성애

http://18.222.132.5

**Comment by Yerim2695** [comment]
5조 
http://13.209.97.156/
https://github.com/lsy044/homepage

**Comment by hyunjaeyou** [comment]
1조입니다
유현재 배영현 안운장 이지현 전재현 오상우
http://18.218.207.97/

**Comment by YeChan1030** [comment]
3조 입니다
신예찬 신한결 주기현 김지현 이정민 성인규
http://13.58.66.76/

**Comment by ghost** [comment]
2조 입니다
장민규 박승준 이윤비 유선아 유정아 전준표 허재혁
http://18.233.97.89
사진이 안보이네요 ㅠㅠ 계속 수정하겠습니다 !
