### ISSUE TITLE
AWS Deploy 과제

### ISSUE THREAD

**Issue by poongnewga** [NEXT-LIKELION/Assignment#18]
***본인의 AWS 인스턴스 IP를 댓글로 달아주세요.***

기한 : 7/19 세션 전까지

**Comment by jason2133** [comment]
이재승
13.125.119.0

성공!

**Comment by jihyuunn** [comment]
이지현
13.125.20.55

강의 잘 봤습니당

**Comment by soonjune** [comment]
박승준
http://13.209.48.31/

체리 먹고 싶다

**Comment by Jack2ee** [comment]
재혁
http://18.207.188.72/

**Comment by seona-yu** [comment]
유선아
http://18.219.184.86/

"아따 힘들다" 강의 고맙습니다아! :)

**Comment by Cecilia-L** [comment]
이윤비
http://52.87.165.74/
강의 감사합니당 수고하셨어요!!

**Comment by PoSungKim** [comment]
김보성

http://13.125.217.131/

와 희재형, 진짜 너무 수고하셨어요 ^^ !!
maplestory_launcher.exe 완전 졸귀!!

**Comment by ashufflepuff** [comment]
유정아
http://18.218.83.190/

희재오빠 감사합니다!!!

**Comment by ghost** [comment]
장민규
http://18.233.97.89/
수고하셨습니당~

**Comment by Yerim2695** [comment]
허에림
http://13.209.70.90/

**Comment by YeChan1030** [comment]
http://13.58.66.76/
신예찬

NEXT 홈페이지 과제로 연동했습니다!

**Comment by ssng123** [comment]
한승희
13.209.13.26
![image](https://user-images.githubusercontent.com/37537241/42936636-947356cc-8b87-11e8-8a6a-93c37fbf6f84.png)
좀따 다시 해보고 올릴게요!-!

**Comment by gyeol1212** [comment]
신한결
http://54.237.197.39/

**Comment by qlqnf16** [comment]
이정민
http://13.125.242.207/

**Comment by X3PY** [comment]
전준표
http://34.207.125.133/

**Comment by JIHYUN1110** [comment]
김지현
http://35.173.220.216/

강의 고마오요 ㅎㅎ
