### ISSUE TITLE
여름방학 Team Project 과제 (2): 웹서비스 실전 기술 훈련 (~8/9)

### ISSUE THREAD

**Issue by woonjangahn** [NEXT-LIKELION/Assignment#19]
안녕하세요, 여러분.

첫번째 팀 프로젝트에서 각각 좋은 결과를 내주셔서 정말 감사합니다.

두번째 과제는 웹서비스 실전 기술 훈련이라는 거창한 이름을 가지고 있지만, 사실 우리가 여러 서비스에서 흔하게 볼 수 있는 사용자 친화적 기술을 알아보고, 구현해보는 과제입니다.

지난번 프로젝트가 디자인, 창의성, 웹 구현에 초점을 두었다면, 이번에는 특정 기술을 활용할 능력을 배양하기 위해 과제를 한 다는 것을 알아주셨으면 합니다.

다음 기술들 중에 **4가지 이상을 선택하여 최대한 구현**해보는 것이 이번 과제입니다.

- Responsive Web Design (Grid / Flexbox 이용)
- 일반 회원가입 메일 인증 (Rails 내장 ActiveMailer, 또는 다른 RubyGem 활용)
- Facebook / Google / Kakao 등의 Open Auth API를 이용한 소셜 로그인
- Google / Kakao / Map 등 Open Map API를 이용 (+ 위치기반서비스: LBS)
- 홈페이지 관리자 시스템 페이지 (RailsAdmin / ActiveAdmin)
- AJAX Infinite Scroll
- 온라인 접객 서비스 (https://channel.io/ko 등)

(쉬운 것만 골라서 하지 말고 정말 사용해보고 싶은 모듈들을 선택하셔서 구현해보세요 ^^)

기존에 작업중인 프로젝트도 괜찮고, 새로 빈 프로젝트를 만들어서 구현하셔도 괜찮습니다.
각자 파트를 나눠서 기술들을 연습해보고, 최대한 구현하여 실전 해커톤 때 유의미한 기술로 활용할 수 있는 기회가 되었으면 좋겠습니다.

기한은 8월 9일 세션 전까지 팀장이 Deploy 하여 링크를 올려주시면 됩니다.

화이팅!

**Comment by gyeol1212** [comment]
3조
http://54.237.197.39/
이전 과제 NEXT 페이지에 추가했습니다
- 일반 회원가입 메일 인증
- Google 소셜 로그인
- 홈페이지 관리자 시스템 페이지
- AJAX Infinite Scroll (in WHAT WE DO)

**Comment by Hyezzi** [comment]
5조
http://18.208.198.80

- 관리자 페이지
- 구글 맵 api
- channel.io 서비스
- responsive web design

**Comment by Hyejoojjang** [comment]
4조
http://52.91.13.234/

- 구글 맵 api
- channel.io 서비스
