### ISSUE TITLE
1주차 과제(1-2) - CSS

### ISSUE THREAD

**Issue by kulikelion** [NEXT-LIKELION/Assignment#2]
## Codecademy - CSS
- [x] 김민형
- [x] 김보성
- [x] 김지현
- [x] 박승준
- [x] 방혜주
- [x] 배영현
- [x] 성인규
- [x] 손지연
- [x] 신예찬
- [x] 신한결
- [x] 안성수
- [x] 엄가람
- [x] 오상우
- [x] 원혜진
- [x] 유선아
- [x] 유정아
- [x] 유현재
- [x] 이수영
- [x] 이윤비
- [x] 이재승
- [x] 이정민
- [x] 이지원
- [x] 이지현
- [x] 장민규
- [x] 장영재
- [x] 전재현
- [x] 전준표
- [x] 주기현
- [x] 최희윤
- [x] 한승희
- [x] 허예림
- [x] 허재혁

---

- 32 / 32 명 완료

**Comment by poongnewga** [comment]
채희재 (샘플입니다.)

![unnamed](https://user-images.githubusercontent.com/15710904/37710052-c635e062-2d4f-11e8-9703-6cc32264de64.jpg)

**Comment by mhbest** [comment]
사진이 안올라가져서 링크로 올릴게요
SG31GB

**Comment by Yerim2695** [comment]
![default](https://user-images.githubusercontent.com/37537200/37714841-e0ca25e2-2d5d-11e8-98f7-ea373d983428.PNG)
허예림

**Comment by jason2133** [comment]
이재승
![learn css](https://user-images.githubusercontent.com/37537208/37748725-46da15b2-2dc8-11e8-86a2-14ea9ced8d05.jpg)


이재승

**Comment by kulikelion** [comment]
@mhbest 

카메라로 찍는 게 아니라 화면을 컴퓨터에서 캡쳐하면 용량이 작아서 올릴 수 있을 거에요~

아래를 참고해주세요!

[#Link1 윈도우에서 캡쳐하는 법](http://mainia.tistory.com/5135)

[#Link2 맥에서 캡쳐하는 법](http://macnews.tistory.com/498)

캡쳐해서 본인의 이름과 함께 다시 올려주세요 :) 숙제~

**Comment by PoSungKim** [comment]
김보성
![_ 1-2 _learn css_](https://user-images.githubusercontent.com/37537227/37758510-d3b7bc52-2df3-11e8-8ae6-8ce185948a07.GIF)

**Comment by X3PY** [comment]
![1-2](https://user-images.githubusercontent.com/37537209/37815594-cd860f4a-2eb2-11e8-9951-327071383a98.PNG)
전준표

**Comment by dkor3** [comment]
안성수
![css completed](https://user-images.githubusercontent.com/37537204/37815703-3ffbbf70-2eb3-11e8-9202-4ade35b7a650.png)

**Comment by dkor3** [comment]
안성수
![css completed](https://user-images.githubusercontent.com/37537204/37815736-6465eb7e-2eb3-11e8-8913-a1e3bb9b9c09.png)

**Comment by seona-yu** [comment]
![css completed](https://user-images.githubusercontent.com/37537217/37818916-14d2e0ce-2ebf-11e8-8418-0e525ffc1eca.png)

유선아

**Comment by Cecilia-L** [comment]
이윤비
<img width="960" alt="css" src="https://user-images.githubusercontent.com/37537232/37819519-12df2c4e-2ec1-11e8-8a67-99fa91ec5890.png">

**Comment by JIHYUN1110** [comment]
김지현

![1](https://user-images.githubusercontent.com/37537212/37824529-4c6a8f76-2ed0-11e8-9a1f-adf3990b5a6e.PNG)

**Comment by JIHYUN1110** [comment]
김지현

![1](https://user-images.githubusercontent.com/37537212/37824559-638235a6-2ed0-11e8-948f-0a1ed943c7be.PNG)

**Comment by gyeol1212** [comment]
신한결
![2018-03-23 11 33 10](https://user-images.githubusercontent.com/37537201/37835061-9dd6a71a-2ef2-11e8-806e-3bba10c622c0.png)

**Comment by Hyezzi** [comment]
<img width="960" alt="css" src="https://user-images.githubusercontent.com/37537222/37859901-c6643dc0-2f5e-11e8-881a-68d54da9a0fa.png">


원혜진

**Comment by preeminent77** [comment]
![2018-03-24_135224](https://user-images.githubusercontent.com/37537194/37860545-a36d8e8c-2f6a-11e8-845e-80478a23fc62.jpg)
전재현

**Comment by jamie7060** [comment]
<img width="1278" alt="2018-03-20 4 29 31" src="https://user-images.githubusercontent.com/37537242/37860741-6a93f95c-2f6f-11e8-9652-a7da2a61bd3d.png">
박승준

**Comment by soonjune** [comment]
<img width="1276" alt="2018-03-24 2 26 01" src="https://user-images.githubusercontent.com/37537242/37860746-834ce5c6-2f6f-11e8-881c-b480d767f859.png">
박승준

**Comment by Jack2ee** [comment]
![image](https://user-images.githubusercontent.com/37537235/37861893-ee5c3d28-2f86-11e8-8600-9568977e479b.png)
허재혁

**Comment by ghost** [comment]
장민규
<img width="960" alt="2" src="https://user-images.githubusercontent.com/37537219/37862169-d831ebba-2f8b-11e8-9434-ee99da02d087.PNG">

**Comment by ingyuseong** [comment]
![1-2](https://user-images.githubusercontent.com/37537248/37863987-4074e410-2fab-11e8-9f75-faa6fbe6547a.png)
성인규입니다

**Comment by jihyuunn** [comment]
![2018-03-24 10 22 11](https://user-images.githubusercontent.com/37537223/37864437-0bd364e6-2fb2-11e8-8b76-d3a20cb2b9c9.png)
이지현

**Comment by norrard148** [comment]
장영재
![d](https://user-images.githubusercontent.com/37537262/37864785-977a4d4e-2fb6-11e8-9ae9-8011a165ee72.PNG)

**Comment by sangw0804** [comment]
![image](https://user-images.githubusercontent.com/37537207/37865181-29cef21c-2fbc-11e8-9cf6-62a02f314363.png)
오상우

**Comment by jiwonny** [comment]
이지원
![image](https://user-images.githubusercontent.com/37537213/37865684-6cc8b970-2fc3-11e8-823b-f076938e5bd6.png)

**Comment by daisybae** [comment]
배영현
![image](https://user-images.githubusercontent.com/37537214/37867785-5c7b19ce-2fe0-11e8-9f3f-6a308988d006.png)

**Comment by mhbest** [comment]
2018-03-25 3:55 GMT+09:00 daisybae <notifications@github.com>:

**Comment by ssng123** [comment]
한승희
![image](https://user-images.githubusercontent.com/37537241/37871234-4b74472e-3024-11e8-918b-578bbd49e0a7.png)

**Comment by hyunjaeyou** [comment]
![css](https://user-images.githubusercontent.com/37537210/37872154-b4a1de2e-303c-11e8-9113-651f60c5d23b.png)
유현재입니다

**Comment by swimmie0** [comment]
![image](https://user-images.githubusercontent.com/37537202/37873586-9ffbad1a-305a-11e8-8add-b53d6c6d66a9.png)

이수영

**Comment by karamie** [comment]
![_ 2](https://user-images.githubusercontent.com/37537206/37874147-41493d00-3064-11e8-8c9a-6fe58362e14f.PNG)

엄가람:)

**Comment by emilyson** [comment]
<img width="805" alt="default" src="https://user-images.githubusercontent.com/37537203/37874797-054e09a4-3071-11e8-8611-eae520410249.PNG">
손지연입니다:)

**Comment by YeChan1030** [comment]
신예찬입니다 :)
![default](https://user-images.githubusercontent.com/37537205/37875480-1dea4c16-307b-11e8-842d-ddd493cee6df.PNG)

**Comment by ashufflepuff** [comment]
![css_done_capture](https://user-images.githubusercontent.com/37537211/37875601-cf9b5e0e-307c-11e8-8ae3-044a391f52cb.JPG)

유정아

**Comment by Hyejoojjang** [comment]
<img width="1280" alt="2018-03-25 9 36 48" src="https://user-images.githubusercontent.com/37541410/37875614-f34e69fe-307c-11e8-9683-9a94a05005c7.png">

**Comment by kihyunjoo** [comment]
주기현 [
![kh](https://user-images.githubusercontent.com/37537229/37875707-162585f6-307e-11e8-81ad-787aa41503e6.jpeg)
](url)

**Comment by qlqnf16** [comment]
이정민
![d](https://user-images.githubusercontent.com/37537216/37876526-7ef22c88-3088-11e8-975c-a5bcd870e25e.png)

**Comment by hy970723** [comment]
<img width="1073" alt="2018-03-26 12 02 42" src="https://user-images.githubusercontent.com/37537254/37876558-1d29fb7e-3089-11e8-9900-2278de20c362.png">

최희윤입니다
