### ISSUE TITLE
[3/20 Python Codecademy Assignment]

### ISSUE THREAD

**Issue by sangw0804** [NEXT-LIKELION/Assignment#20]
**[Learn Python3 과제 공지]**
-원활한 수업 진행을 위해 Codecademy에 가입하여 해당 강좌를 정해진 날짜까지 수강하셔야 합니다
-각 강좌는 Codecademy에 가입하신 이후 상단 배너의 Catalog에서 검색하실 수 있습니다 (Python : Learn Python 3) 
-Codecademy에 가입하신 이후 1주일 이내에만 수강이 가능합니다 (1주일이 지나면 유료화됩니다)
-Interactive Lesson을 전부 수강하셔야 합니다!

**#강좌 수강 인증샷 올리기 (마감 : 3/20 자정)**
-**Learn Python3**의 **"모든" Interactive Lesson** 강좌를 수강하신 후 아래와 같은 형태의 진행률 인증샷을 **본인 이름과 함께** 댓글로 달아주세요! 
**-모든 Interactive Lesson을 다 들으시면 40% 정도 될 겁니다** 아래 사진처럼 98%를 채우실 필요는 없어요!

*****수업 시작 전에 과제 제출 여부 확인할 거에요! : )**

![뉴](https://user-images.githubusercontent.com/37537210/54574115-641db700-4a32-11e9-95c8-147e11daa0ba.png)

**남재용**
**조성우**
**김승태**
**최주원**
**안태경**
**이정우**
**김준오**
**장주희**
**김재훈**
**박선영**
**권중훈**
**조형제**
김세연
**김동제**
**최세은**
**이인우**
**안수혜**
**우지학**
**박지환**
**이경연**
**김미라**
**김준태**
**최상하**
**이채연**
**김강연**
**이유나**

**Comment by woojeee** [comment]
따봉

**Comment by elksha** [comment]
김준태

![IMG_0055](https://user-images.githubusercontent.com/43684130/54578691-05f9cf80-4a44-11e9-8b86-da5ade04c4ca.png)

**Comment by Gjunghoon** [comment]
권중훈
![K-002](https://user-images.githubusercontent.com/44766030/54613592-4be38180-4a9e-11e9-88ed-655352ebfe80.png)

**Comment by ghost** [comment]
이정우
![이정우 과제](https://user-images.githubusercontent.com/48678295/54618480-72a5b600-4aa6-11e9-9144-90203288df7a.jpg)

**Comment by RyanKor** [comment]
![image](https://user-images.githubusercontent.com/40455392/54620156-198b5180-4aa9-11e9-9248-3638acc867ef.png)

거의 3일만에 점프 투 파이썬을 완독한 느낌 아닌 느낌..!

**Comment by hoiJuwon** [comment]
최주원
<img width="1597" alt="스크린샷 2019-03-20 오후 6 06 52" src="https://user-images.githubusercontent.com/47557351/54672222-f7daaa80-4b3a-11e9-87f0-2af1bcbf23a7.png">

**Comment by SoniaComp** [comment]
박선영
<img width="1680" alt="스크린샷 2019-03-20 오후 7 20 15" src="https://user-images.githubusercontent.com/45381486/54676990-52790400-4b45-11e9-9240-d8dbc203c446.png">

**Comment by SoniaComp** [comment]
박선영
<img width="1680" alt="스크린샷 2019-03-20 오후 7 26 16" src="https://user-images.githubusercontent.com/45381486/54677401-21e59a00-4b46-11e9-85b1-af5db38c951a.png">

**Comment by antlikelion** [comment]
이인우
<img width="473" alt="파이썬3" src="https://user-images.githubusercontent.com/48678284/54677757-ea2b2200-4b46-11e9-9171-ab713c77757d.png">

**Comment by miramira227** [comment]
김미라
(첨에 잘못 이해하는 바람에 interactive말고 다른거도 들어서 진행률이..달라요..)
<img width="960" alt="캡처" src="https://user-images.githubusercontent.com/48576190/54680462-41cc8c00-4b4d-11e9-90b8-b800e54e47c2.PNG">

**Comment by SeeunChoi1** [comment]
![KakaoTalk_20190320_183418025](https://user-images.githubusercontent.com/37589355/54680967-8c9ad380-4b4e-11e9-8a71-38601565ccc6.png)
최세은

**Comment by swcho9919** [comment]
![캡처](https://user-images.githubusercontent.com/46709390/54681987-0e8bfc00-4b51-11e9-85c1-e263748d8247.PNG)
조성우

**Comment by YUNALEEEE** [comment]
이유나
![파이썬인증](https://user-images.githubusercontent.com/48678302/54682736-0f259200-4b53-11e9-9d46-8e4dcac62e8f.JPG)

**Comment by juno1028** [comment]
김준오
<img width="1430" alt="Screen Shot 2019-03-20 at 9 27 42 PM" src="https://user-images.githubusercontent.com/45659499/54684244-177fcc00-4b57-11e9-9324-a2fa4a61df61.png">

**Comment by jojoboy2212** [comment]
<img width="1285" alt="스크린샷 2019-03-20 오후 9 55 51" src="https://user-images.githubusercontent.com/43463542/54685769-f9b46600-4b5a-11e9-8da1-24b544c43c69.png">
조형제

**Comment by gaetokk** [comment]
안태경
![파이썬](https://user-images.githubusercontent.com/46814961/54687735-a09b0100-4b5f-11e9-812a-b7be2b44afa4.jpg)

**Comment by KimKangYeon** [comment]
김강연
![image](https://user-images.githubusercontent.com/48678290/54688741-90842100-4b61-11e9-85df-c14ddbfca08a.png)

**Comment by wSuhye** [comment]
안수혜

![캡처](https://user-images.githubusercontent.com/48678364/54689120-40f22500-4b62-11e9-8938-05afbc5a1d2a.JPG)

**Comment by jihakwoo** [comment]
우지학
![image](https://user-images.githubusercontent.com/44742935/54689244-78f96800-4b62-11e9-87c1-e33dca3898e7.png)

**Comment by Gentleman37** [comment]
이경연
<img width="960" alt="스크린샷 2019-03-20 오후 11 04 38" src="https://user-images.githubusercontent.com/35323749/54690448-c2e34d80-4b64-11e9-9eb9-ec0e1dc4671d.png">

**Comment by parkjihwanjay** [comment]
박지환
<img width="944" alt="과제1(파이썬)" src="https://user-images.githubusercontent.com/48053238/54690552-ff16ae00-4b64-11e9-8183-91603746d3af.PNG">

**Comment by updownC** [comment]
최상하

![최상하](https://user-images.githubusercontent.com/48586856/54690844-9b40b500-4b65-11e9-89d7-05ab17655a46.jpg)

**Comment by vhvha** [comment]
장주희

![2019-03-20 (2)](https://user-images.githubusercontent.com/46235386/54691577-d394c300-4b66-11e9-8638-85dee6652c3a.png)

**Comment by NamJaeyong** [comment]
남재용

![dddddddd](https://user-images.githubusercontent.com/48678278/54692346-3470cb00-4b68-11e9-9d8b-42c089450bfc.png)

**Comment by chaeyeonie** [comment]
이채연
<img width="918" alt="파이썬 캡쳐" src="https://user-images.githubusercontent.com/48678352/54694360-76e7d700-4b6b-11e9-99e4-d5943392ac7e.PNG">

**Comment by 10kdkd** [comment]
김동제 
![제목 adfasd](https://user-images.githubusercontent.com/48678281/54695587-94b63b80-4b6d-11e9-8186-cd4780d5b42c.png)

**Comment by kimjaehun96** [comment]
김재훈
![image](https://user-images.githubusercontent.com/48678264/54737040-62e6b880-4bf1-11e9-8ebe-ca8bb7437b11.png)

**Comment by FriedPotato-hash** [comment]
![캡처](https://user-images.githubusercontent.com/48678324/54741053-85340280-4c00-11e9-8a43-ded60a65e6a6.PNG)

**Comment by FriedPotato-hash** [comment]
김세연....ㅎ
