### ISSUE TITLE
[3/25 HTML Codecademy Assignment]

### ISSUE THREAD

**Issue by qlqnf16** [NEXT-LIKELION/Assignment#21]
[Introduction to HTML 과제 공지]
-원활한 수업 진행을 위해 Codecademy에 가입하여 해당 강좌를 정해진 날짜까지 수강하셔야 합니다
-각 강좌는 Codecademy에 가입하신 이후 상단 배너의 Catalog에서 검색하실 수 있습니다
-Interactive Lesson을 전부 수강하셔야 합니다!

### 강좌 수강 인증샷 올리기 (마감 : 3/25 세션 전까지)
-Introduction to HTML의 "모든" Interactive Lesson 강좌를 수강하신 후 아래와 같은 형태의 진행률 인증샷을 본인 이름과 함께 댓글로 달아주세요!

<img width="1792" alt="Screen Shot 2019-03-19 at 16 07 39" src="https://user-images.githubusercontent.com/37537216/54586682-25532580-4a61-11e9-831f-b97d0c7e7836.png">

**Comment by elksha** [comment]
김준태

![KakaoTalk_20190318_222426308](https://user-images.githubusercontent.com/43684130/54598804-a79d1300-4a7c-11e9-915b-0639a48a6d5f.png)

**Comment by Gjunghoon** [comment]
권중훈
![K-003](https://user-images.githubusercontent.com/44766030/54618396-4f7b0680-4aa6-11e9-9003-3dec16f685b8.png)

**Comment by swcho9919** [comment]
![html과제](https://user-images.githubusercontent.com/46709390/54730419-37050c00-4bcc-11e9-9290-c9744da4f70d.PNG)
조성우

**Comment by jojoboy2212** [comment]
<img width="1590" alt="스크린샷 2019-03-22 오후 7 45 06" src="https://user-images.githubusercontent.com/43463542/54817752-01027d80-4cdb-11e9-88af-104c7571d726.png">
조형제

**Comment by parkjihwanjay** [comment]
박지환
<img width="948" alt="과제2(html)" src="https://user-images.githubusercontent.com/48053238/54822028-44fb7f80-4ce7-11e9-9f0d-3b5711483fa4.PNG">

**Comment by SoniaComp** [comment]
박선영
<img width="1680" alt="스크린샷 2019-03-22 오후 11 06 17" src="https://user-images.githubusercontent.com/45381486/54828318-3ddc6d80-4cf7-11e9-9032-b730d7fef817.png">

**Comment by juno1028** [comment]
김준오
<img width="1429" alt="Screen Shot 2019-03-23 at 3 56 11 AM" src="https://user-images.githubusercontent.com/45659499/54846616-a3445480-4d1f-11e9-95a7-7e683cefccf9.png">

**Comment by hoiJuwon** [comment]
최주원 
<img width="1640" alt="스크린샷 2019-03-23 오후 5 09 37" src="https://user-images.githubusercontent.com/47557351/54863637-86933580-4d8e-11e9-8f5c-ee2883195146.png">

**Comment by wSuhye** [comment]
안수혜
![캡처](https://user-images.githubusercontent.com/48678364/54866800-d63c2600-4dbb-11e9-8805-12dbf6cde2e0.JPG)

**Comment by Gentleman37** [comment]
이경연
<img width="1125" alt="스크린샷 2019-03-23 오후 10 41 14" src="https://user-images.githubusercontent.com/35323749/54866866-f1f3fc00-4dbc-11e9-9e7b-e221ad08eb9d.png">

**Comment by antlikelion** [comment]
이인우
<img width="474" alt="HTML" src="https://user-images.githubusercontent.com/48678284/54869701-e9f98380-4ddf-11e9-9f4d-f9dac12ad39d.png">

**Comment by ghost** [comment]
이정우
![3 25 HTML 과제](https://user-images.githubusercontent.com/48678295/54875094-62d9f900-4e3b-11e9-82e9-1e1da109ae72.jpg)

**Comment by KimKangYeon** [comment]
![image](https://user-images.githubusercontent.com/48678290/54875142-2ce94480-4e3c-11e9-81ec-593e33ba4ec6.png)

김강연

**Comment by 10kdkd** [comment]
김동제
![HTML 끝](https://user-images.githubusercontent.com/48678281/54877315-16ed7b00-4e60-11e9-9fed-5326d2747716.png)

**Comment by RyanKor** [comment]
김승태
![image](https://user-images.githubusercontent.com/40455392/54878458-b7e43200-4e70-11e9-9e1c-297e39ffb95a.png)

직접 코드는 설계하는 것이 아니라서 재밌게 글 읽으면서 학습했습니다

**Comment by YUNALEEEE** [comment]
이유나
![html과제](https://user-images.githubusercontent.com/48678302/54878714-ce3fbd00-4e73-11e9-9141-63988acf3b6f.JPG)

**Comment by updownC** [comment]
최상하

![html_최상하](https://user-images.githubusercontent.com/48586856/54881312-00601780-4e92-11e9-94a3-9d3f645db225.jpg)

**Comment by chaeyeonie** [comment]
<img width="861" alt="444" src="https://user-images.githubusercontent.com/48678352/54882675-c85fd100-4e9f-11e9-9a96-b022ecc2cf6c.PNG">
이채연

**Comment by chaeyeonie** [comment]
이채연
<img width="861" alt="444" src="https://user-images.githubusercontent.com/48678352/54882697-fcd38d00-4e9f-11e9-9bd5-d5f1c5b0e047.PNG">

**Comment by SeeunChoi1** [comment]
![image](https://user-images.githubusercontent.com/37589355/54883117-538f9580-4ea5-11e9-9aa1-5aab13a058a5.png)
최세은

**Comment by vhvha** [comment]
장주희
![2019-03-25 (1)](https://user-images.githubusercontent.com/46235386/54884110-5e9bf300-4eb0-11e9-840f-95b5014ff107.png)

**Comment by NamJaeyong** [comment]
남재용
![image](https://user-images.githubusercontent.com/48678278/54890384-785b2b80-4eec-11e9-94cb-b37dbf64ff86.png)

**Comment by FriedPotato-hash** [comment]
![html capture](https://user-images.githubusercontent.com/48678324/54890814-5d89b680-4eee-11e9-9724-7110c12682b3.PNG)
김세연연

**Comment by kimjaehun96** [comment]
김재훈
![html 진도](https://user-images.githubusercontent.com/48678264/54897271-0fcf7700-4f0b-11e9-8405-c25fad5e1a1a.png)

**Comment by jihakwoo** [comment]
우지학학
![image](https://user-images.githubusercontent.com/44742935/54898801-ec0f2f80-4f10-11e9-8c7d-e49a0ce1c291.png)

**Comment by gaetokk** [comment]
![html](https://user-images.githubusercontent.com/46814961/54904300-7cee0700-4f21-11e9-9964-3cd5aed88423.jpg)
안태경

**Comment by miramira227** [comment]
김미라
![image](https://user-images.githubusercontent.com/48576190/54909157-e1629380-4f2c-11e9-9f1c-6bd2a3091722.png)
