### ISSUE TITLE
[3/25 CSS Codecademy Assignment]

### ISSUE THREAD

**Issue by qlqnf16** [NEXT-LIKELION/Assignment#22]
[Learn CSS 과제 공지]
-원활한 수업 진행을 위해 Codecademy에 가입하여 해당 강좌를 정해진 날짜까지 수강하셔야 합니다
-각 강좌는 Codecademy에 가입하신 이후 상단 배너의 Catalog에서 검색하실 수 있습니다
-Interactive Lesson을 전부 수강하셔야 합니다!

### 강좌 수강 인증샷 올리기 (마감 : 3/25 세션 전까지)
-Learn CSS의 **_모든_** Interactive Lesson 강좌를 수강하신 후 아래와 같은 형태의 진행률 인증샷을 본인 이름과 함께 댓글로 달아주세요

<img width="1792" alt="Screen Shot 2019-03-19 at 15 53 21" src="https://user-images.githubusercontent.com/37537216/54586784-706d3880-4a61-11e9-8289-5db67026222c.png">

**Comment by elksha** [comment]
김준태

![KakaoTalk_20190318_222425807](https://user-images.githubusercontent.com/43684130/54598843-c00d2d80-4a7c-11e9-8fcb-c461d3395409.png)

**Comment by SoniaComp** [comment]
박선영
<img width="1680" alt="스크린샷 2019-03-22 오후 4 02 25" src="https://user-images.githubusercontent.com/45381486/54805965-00a6ba00-4cbc-11e9-9055-d22c6d8f6451.png">

**Comment by Gjunghoon** [comment]
권중훈
![K-020](https://user-images.githubusercontent.com/44766030/54862063-1974a580-4d78-11e9-847d-902c21c991d6.png)

**Comment by jojoboy2212** [comment]
<img width="1587" alt="스크린샷 2019-03-23 오후 3 37 09" src="https://user-images.githubusercontent.com/43463542/54862677-935d5c80-4d81-11e9-9183-4327b5cd8cd7.png">
조형제

**Comment by Gentleman37** [comment]
이경연
<img width="1125" alt="스크린샷 2019-03-23 오후 10 40 53" src="https://user-images.githubusercontent.com/35323749/54866868-02a47200-4dbd-11e9-9b8d-3b60687e13df.png">

**Comment by ghost** [comment]
이정우
![3 25 CSS 과제](https://user-images.githubusercontent.com/48678295/54875086-4a69de80-4e3b-11e9-964c-f8104937b260.jpg)

**Comment by KimKangYeon** [comment]
![image](https://user-images.githubusercontent.com/48678290/54877620-561dcb00-4e64-11e9-9e20-6672b88c9738.png)

김강연

**Comment by YUNALEEEE** [comment]
이유나
![css 과제](https://user-images.githubusercontent.com/48678302/54878765-8b321980-4e74-11e9-8a99-9783fb0395a7.JPG)

**Comment by RyanKor** [comment]
김승태
![image](https://user-images.githubusercontent.com/40455392/54879080-45775000-4e78-11e9-9b76-08cebcbc28e3.png)

**Comment by parkjihwanjay** [comment]
박지환
<img width="942" alt="과제3(css)" src="https://user-images.githubusercontent.com/48053238/54879533-38109480-4e7d-11e9-9049-04ce89283614.PNG">

**Comment by wSuhye** [comment]
안수혜
![css](https://user-images.githubusercontent.com/48678364/54881211-00abe300-4e91-11e9-88d7-21d0a37e1865.JPG)

**Comment by chaeyeonie** [comment]
<img width="892" alt="333" src="https://user-images.githubusercontent.com/48678352/54882662-a9613f00-4e9f-11e9-83b2-cc37fe5f8605.PNG">

이채연

**Comment by juno1028** [comment]
김준오
<img width="1342" alt="Screen Shot 2019-03-25 at 2 37 40 AM" src="https://user-images.githubusercontent.com/45659499/54883231-0a404580-4ea7-11e9-8b9d-f00b43215b41.png">

**Comment by vhvha** [comment]
장주희
![2019-03-25 (2)](https://user-images.githubusercontent.com/46235386/54884126-88edb080-4eb0-11e9-8eb1-6cbc277ae532.png)

**Comment by antlikelion** [comment]
이인우
<img width="472" alt="CSS" src="https://user-images.githubusercontent.com/48678284/54884779-27314480-4eb8-11e9-9f5d-bf36581565fd.png">

**Comment by swcho9919** [comment]
![css](https://user-images.githubusercontent.com/46709390/54889612-c837f380-4ee8-11e9-9ecd-43828d681b5e.PNG)
조성우

**Comment by NamJaeyong** [comment]
남재용
![image](https://user-images.githubusercontent.com/48678278/54890359-5e214d80-4eec-11e9-92de-6c4361fa18a7.png)

**Comment by FriedPotato-hash** [comment]
![css 캡처](https://user-images.githubusercontent.com/48678324/54890796-49de5000-4eee-11e9-91e6-5a7fc88de7f7.PNG)
김세연

**Comment by updownC** [comment]
최상하

![css_최상하](https://user-images.githubusercontent.com/48586856/54895526-4c977000-4f03-11e9-86da-86b0b391c434.jpg)

**Comment by hoiJuwon** [comment]
최주원

<img width="1592" alt="스크린샷 2019-03-25 오후 2 19 22" src="https://user-images.githubusercontent.com/47557351/54896779-15c45880-4f09-11e9-9c58-8941df396959.png">

**Comment by kimjaehun96** [comment]
김재훈
![html 진도](https://user-images.githubusercontent.com/48678264/54897165-9fc0f100-4f0a-11e9-8043-9c796510c326.png)

**Comment by jihakwoo** [comment]
우지학
![image](https://user-images.githubusercontent.com/44742935/54898760-ca15ad00-4f10-11e9-9697-9900289c2917.png)

**Comment by SeeunChoi1** [comment]
최세은
![image](https://user-images.githubusercontent.com/37589355/54901076-c0904300-4f18-11e9-9f69-75f6103ef03f.png)

**Comment by 10kdkd** [comment]
김동제
![CSS 끝!!](https://user-images.githubusercontent.com/48678281/54902591-35657c00-4f1d-11e9-948f-3f40b7f4de27.png)

**Comment by gaetokk** [comment]
![css](https://user-images.githubusercontent.com/46814961/54904351-a0b14d00-4f21-11e9-8733-16f86927a09d.jpg)
안태경

**Comment by miramira227** [comment]
김미라
![image](https://user-images.githubusercontent.com/48576190/54909248-17077c80-4f2d-11e9-9ca4-e88850811c4f.png)
