### ISSUE TITLE
[4/1 Python Basic 과제 & Github 업로드]

### ISSUE THREAD

**Issue by hyunjaeyou** [NEXT-LIKELION/Assignment#24]
**[파이썬 베이직 과제 깃허브 업로드]** 
- **마감 : 4/1 수업 전까지**
- 3/21 교안에 포함된 **연습문제**와 **과제**의 완성본 소스코드를 깃허브에 업로드해주세요!
- 본인의 소스코드를 업로드한 **깃허브 링크를 이름**과 함께 댓글에 달아주세요!
- 댓글로 과제 제출 여부 확인합니다 : )

*깃허브 업로드는 3/18 상우님 교안, 파이썬 문제풀이는 3/21 현재님 교안을 참고하시면 됩니다.
*모르시는 부분이 있다면 언제든 운영진분들께 연락주시거나 파이빌에 찾아오시면 됩니다!

**Comment by jojoboy2212** [comment]
https://github.com/jojoboy2212/Likelion-Assignment/blob/master/homework.py
조형제

**Comment by antlikelion** [comment]
이인우
https://github.com/antlikelion/html_css

**Comment by elksha** [comment]
김준태
https://github.com/elksha/Python_Exercise
(안에 assignment.py가 과제한 파일입니다!)

**Comment by jojoboy2212** [comment]
조형제
https://github.com/jojoboy2212/Likelion-Assignment

**Comment by RyanKor** [comment]
김승태
https://github.com/RyanKor/Next-x-Likelion/blob/master/python_exercies/assignment1.py

**Comment by Gentleman37** [comment]
이경연
https://github.com/mangod037/first_repo.git
homework.py입니다

**Comment by hoiJuwon** [comment]
최주원 
https://github.com/hoiJuwon/likelion_assignment

**Comment by swcho9919** [comment]
조성우
https://github.com/swcho9919/first_repository/blob/master/hw_python.py

**Comment by updownC** [comment]
최상하
https://github.com/sanghaC/Assignment

**Comment by parkjihwanjay** [comment]
박지환
https://github.com/parkjihwanjay/first_repo

**Comment by juno1028** [comment]
김준오
https://github.com/juno1028/assignment

**Comment by Gjunghoon** [comment]
권중훈
https://github.com/Gjunghoon/LIKELION-Assignment/blob/master/%EA%B6%8C%EC%A4%91%ED%9B%88%EA%B3%BC%EC%A0%9C.py

**Comment by FriedPotato-hash** [comment]
김세연
https://github.com/080101/homework

**Comment by SoniaComp** [comment]
박선영
https://github.com/SoniaComp/NEXT/blob/master/python_exercise/hw.py

**Comment by ghost** [comment]
이정우
https://github.com/jwibanes/assignment

**Comment by jihakwoo** [comment]
우지학
https://github.com/woojeee/python-ass1

**Comment by vhvha** [comment]
장주희
https://github.com/vhvha/assignment_likelion

pyas.py 파일입니다.

**Comment by chaeyeonie** [comment]
이채연
https://github.com/chaeyeonie/python_homework-190330-.git

**Comment by wSuhye** [comment]
안수혜
https://github.com/wSuhye/SU/blob/master/hw.py

**Comment by KimKangYeon** [comment]
김강연
https://github.com/KimKangYeon/homework1

**Comment by 10kdkd** [comment]
김동제
homework1.py 파일입니다.
https://github.com/10kdkd/first_repo

**Comment by gaetokk** [comment]
안태경
https://github.com/gaetokk/LIKELION_2019/blob/master/0321hw.py

**Comment by YUNALEEEE** [comment]
이유나
https://github.com/YUNALEEEE/python_assignment

**Comment by SeeunChoi1** [comment]
최세은
https://github.com/SeeunChoi1/homework_python

**Comment by gaetokk** [comment]
안태경
https://github.com/gaetokk/LIKELION_2019

**Comment by miramira227** [comment]
김미라 
https://github.com/miramira227/gwaje_mira

**Comment by NamJaeyong** [comment]
https://github.com/NamJaeyong/pythonNam

**Comment by NamJaeyong** [comment]
https://github.com/NamJaeyong/pythonNam.git

**Comment by kimjaehun96** [comment]
김재훈
https://github.com/kimjaehun96/first_repository
