### ISSUE TITLE
[3/28 CSS 과제]

### ISSUE THREAD

**Issue by qlqnf16** [NEXT-LIKELION/Assignment#25]
## CSS과제 공지: 3/28 세션 전까지

오늘 세션에서 배운 것들을 이용해서 내 카카오톡 프로필을 그대로 만들어봅시다!
완성한 사진을 찍어서 이름과 함께 댓글로 달아주세요

![Screen Shot 2019-03-25 at 21 40 19](https://user-images.githubusercontent.com/37537216/54920720-49be6e80-4f47-11e9-9baf-9e9649626fd7.png)

Hint- absolute, flex, border, ...
너무너무 모르겠다, 또는 질문이 있다 하는 분들은 언제든지! **파이빌 306호**를 찾아주세요
운영진이 상주하면서 도와드립니다 😊😊😊

**Comment by elksha** [comment]
김준태

![과제](https://user-images.githubusercontent.com/43684130/54925575-e8e86380-4f51-11e9-85f4-b73273d4b6c9.png)

원래는 제 프로필을 만드는거였던거 같긴 한데... 제 프사를 올리기는 좀 뭐해서 그냥 또치로 해봤습니다!

**Comment by SoniaComp** [comment]
박선영
<img width="500" alt="html_css" src="https://user-images.githubusercontent.com/45381486/54928729-b93c5a00-4f57-11e9-99cf-95d2b15ccb19.png">

**Comment by parkjihwanjay** [comment]
박지환
<img width="258" alt="과제4(html)" src="https://user-images.githubusercontent.com/48053238/54973095-c8f88480-4fd1-11e9-8951-8bc704926cff.PNG">
상당히 허접합니다 ㅜ.ㅜ

**Comment by antlikelion** [comment]
이인우
<img width="217" alt="css과제" src="https://user-images.githubusercontent.com/48678284/54973404-10334500-4fd3-11e9-8f43-ebbc2e7234cc.png">

**Comment by sanghaC** [comment]
최상하

![Kakao_profile](https://user-images.githubusercontent.com/48586856/54973400-0dd0eb00-4fd3-11e9-9c11-5c1790b61637.jpg)

**Comment by sanghaC** [comment]
최상하

![kakao_prof](https://user-images.githubusercontent.com/48586856/54973536-ad8e7900-4fd3-11e9-8395-615b8293fe73.jpg)

**Comment by updownC** [comment]
최상하
![kakao_prof](https://user-images.githubusercontent.com/48586856/54973681-3efdeb00-4fd4-11e9-8d12-b2197a5c7874.jpg)

**Comment by swcho9919** [comment]
![final](https://user-images.githubusercontent.com/46709390/54991577-91ed9780-5000-11e9-9b93-2ca4f35822d5.PNG)

조성우

**Comment by qlqnf16** [comment]
> 박지환
> <img alt="과제4(html)" width="258" src="https://user-images.githubusercontent.com/48053238/54973095-c8f88480-4fd1-11e9-8951-8bc704926cff.PNG">
> 상당히 허접합니다 ㅜ.ㅜ

**Comment by SeeunChoi1** [comment]
최세은
![image](https://user-images.githubusercontent.com/37589355/54986602-4c2bd180-4ff6-11e9-8ac2-cb047505f243.png)

**Comment by chaeyeonie** [comment]
이채연
![image](https://user-images.githubusercontent.com/48678352/54999724-3927fa00-5014-11e9-8e27-6187fc52b6be.png)

**Comment by ghost** [comment]
이정우
![도파](https://user-images.githubusercontent.com/48678295/55005089-bbb5b700-501e-11e9-94b7-29d898278c7a.jpg)

**Comment by RyanKor** [comment]
김승태
![image](https://user-images.githubusercontent.com/40455392/55043405-7ffc0b00-5079-11e9-91e6-92b0282aaa79.png)

https://github.com/RyanKor/Next-x-Likelion/tree/master/assignment2

**Comment by mangod037** [comment]
<img width="421" alt="스크린샷 2019-03-27 오후 3 00 03" src="https://user-images.githubusercontent.com/35323749/55053940-450dcd80-50a1-11e9-8b66-7d81a27b6a7a.png">
이경연입니다

**Comment by Gentleman37** [comment]
<img width="421" alt="스크린샷 2019-03-27 오후 3 04 22" src="https://user-images.githubusercontent.com/35323749/55054028-a3d34700-50a1-11e9-96ac-4c70b3eacaee.png">

이경연입니다

**Comment by jihakwoo** [comment]
마블리 아니고 우지학
![kakao_exercise_jihak](https://user-images.githubusercontent.com/44742935/55054094-cfeec800-50a1-11e9-8768-1be0d331fcf8.png)

https://github.com/woojeee/html-css

**Comment by hoiJuwon** [comment]
최주원
<img width="493" alt="스크린샷 2019-03-27 오후 4 27 11" src="https://user-images.githubusercontent.com/47557351/55057672-35948180-50ad-11e9-9ac6-a08236562e85.png">

**Comment by gaetokk** [comment]
안태경
![html커버사진](https://user-images.githubusercontent.com/46814961/55061201-7fce3080-50b6-11e9-9bdc-a62e8abb02d8.jpg)
다덜 파이빌 오세여~~!!

**Comment by NamJaeyong** [comment]
남재용
![image](https://user-images.githubusercontent.com/48678278/55063793-1ea95b80-50bc-11e9-81b5-99481f5ccf01.png)

**Comment by YUNALEEEE** [comment]
이유나
![카카오톡 프로필](https://user-images.githubusercontent.com/48678302/55065320-f4a56880-50be-11e9-8b4a-595fbb8c475f.JPG)

**Comment by vhvha** [comment]
장주희
![css과제_카톡](https://user-images.githubusercontent.com/46235386/55068612-9c259980-50c5-11e9-976d-4750ea0b5af0.PNG)

**Comment by Gjunghoon** [comment]
권중훈
![K-001](https://user-images.githubusercontent.com/44766030/55092992-e8d59880-50f6-11e9-9f7d-c0b2bdd2ca8e.png)
![K-001](https://user-images.githubusercontent.com/44766030/55137236-ca61b280-5173-11e9-9f6e-294879286ced.png)

**Comment by 10kdkd** [comment]
김동제
![캡처](https://user-images.githubusercontent.com/48678281/55097040-6224b980-50fe-11e9-99a3-4225c00f916b.PNG)

**Comment by jojoboy2212** [comment]
<img width="604" alt="스크린샷 2019-03-28 오전 2 11 43" src="https://user-images.githubusercontent.com/43463542/55097354-01e24780-50ff-11e9-87ba-0be72f796e85.png">
조형제

**Comment by juno1028** [comment]
김준오
<img width="484" alt="Screen Shot 2019-03-28 at 2 13 28 AM" src="https://user-images.githubusercontent.com/45659499/55097777-e75c9e00-50ff-11e9-9c1c-dd5b955931b9.png">

**Comment by FriedPotato-hash** [comment]
![과제_@](https://user-images.githubusercontent.com/48678324/55134323-ccc00e80-516b-11e9-897c-84427d130a1f.PNG)
김세연

**Comment by wSuhye** [comment]
안수혜
![assignment](https://user-images.githubusercontent.com/48678364/55136983-1a8c4500-5173-11e9-8ba7-84a418768571.JPG)

**Comment by miramira227** [comment]
김미라 
![image](https://user-images.githubusercontent.com/48576190/55146717-72817680-5188-11e9-938b-e56411802e83.png)

**Comment by kimjaehun96** [comment]
![또치](https://user-images.githubusercontent.com/48678264/55146837-a492d880-5188-11e9-9882-cc9651a016a0.png)

김재훈

**Comment by KimKangYeon** [comment]
![image](https://user-images.githubusercontent.com/48678290/55147420-b163fc00-5189-11e9-909d-6e0622c15680.png)

김강연

**Comment by KimKangYeon** [comment]
![image](https://user-images.githubusercontent.com/48678290/55147768-57b00180-518a-11e9-8051-163880354189.png)
김강연
