### ISSUE TITLE
[4/1 CSS 실습 과제]

### ISSUE THREAD

**Issue by qlqnf16** [NEXT-LIKELION/Assignment#26]
### [CSS 실습 과제 github 업로드]

마감 : 4/1 수업 전까지
3/28 세션에서 진행한 '인스타그램 만들기' 를 완성하고 github에 업로드해주세요.
본인의 소스코드를 업로드한 github 링크와 완성 스크린샷을 이름과 함께 댓글에 달아주세요!

* 깃허브 업로드는 3/18 상우님 교안을 참고하시면 됩니다.
* 모르시는 부분이 있다면 언제든 운영진에게 연락주시거나 파이빌에 찾아오세요!

**Comment by juno1028** [comment]
https://github.com/juno1028/FAKE_instagram
<img width="1437" alt="fake_instagram" src="https://user-images.githubusercontent.com/45659499/55235060-e8acd880-526f-11e9-8694-29edbc289e4a.png">
김준오

**Comment by updownC** [comment]
최상하
![instagram_jpg](https://user-images.githubusercontent.com/48586856/55238353-a8e9ef00-5277-11e9-96c8-c70343813047.jpg)

https://github.com/sanghaC/Assignment

**Comment by elksha** [comment]
김준태

![HTML,CSS과제_김준태](https://user-images.githubusercontent.com/43684130/55252873-325ce980-5297-11e9-8b1e-416ec06df05c.png)
https://github.com/elksha/Next/tree/master/html_extreme

**Comment by parkjihwanjay** [comment]
박지환
https://github.com/parkjihwanjay/NEXTLION_assignment
<img width="918" alt="과제5(instagram)" src="https://user-images.githubusercontent.com/48053238/55269939-4a0a9100-52dc-11e9-9fbd-777312af137a.PNG">

**Comment by jojoboy2212** [comment]
https://github.com/jojoboy2212/Likelion-Assignment
<img width="981" alt="스크린샷 2019-03-30 오후 3 06 48" src="https://user-images.githubusercontent.com/43463542/55272276-7682d500-52fd-11e9-8a5c-4b260f264a05.png">

**Comment by jojoboy2212** [comment]
조형제
https://github.com/jojoboy2212/Likelion-Assignment
<img width="1028" alt="스크린샷 2019-03-30 오후 3 16 14" src="https://user-images.githubusercontent.com/43463542/55272358-d037cf00-52fe-11e9-93fe-566d1e6feab3.png">

**Comment by antlikelion** [comment]
이인우
https://github.com/antlikelion/first_repo
<img width="758" alt="html_css" src="https://user-images.githubusercontent.com/48678284/55272738-776b3500-5304-11e9-84ae-ae3255a43f51.png">

**Comment by jihakwoo** [comment]
<img width="444" alt="cap1" src="https://user-images.githubusercontent.com/44742935/55272985-6f14f900-5308-11e9-9bd7-95a5a36e026b.PNG">
<img width="443" alt="cap2" src="https://user-images.githubusercontent.com/44742935/55272987-6f14f900-5308-11e9-8226-a1ad67aca334.PNG">

https://github.com/woojeee/web-instagram

마블리♡

**Comment by vhvha** [comment]
장주희
https://github.com/vhvha/assignment_likelion
![insta](https://user-images.githubusercontent.com/46235386/55273050-36c1ea80-5309-11e9-8991-99d7ba19ea7a.PNG)

**Comment by chaeyeonie** [comment]
이채연
![image](https://user-images.githubusercontent.com/48678352/55273624-375e7f00-5311-11e9-9c58-4695548ac5fd.png)



https://github.com/chaeyeonie/instag.git

**Comment by wSuhye** [comment]
안수혜
https://github.com/wSuhye/SU
![인스타그램](https://user-images.githubusercontent.com/48678364/55274133-0cc3f480-5318-11e9-9ed9-b2ad3c48fcf9.JPG)

**Comment by RyanKor** [comment]
김승태
![image](https://user-images.githubusercontent.com/40455392/55278815-a27d7500-5354-11e9-8394-b98f1c1e1791.png)

![image](https://user-images.githubusercontent.com/40455392/55278818-ac9f7380-5354-11e9-9614-0d7bebee773a.png)

Github 소스코드: https://github.com/RyanKor/Next-x-Likelion/tree/master/assignment3

화면 배율을 조정해서 캡쳐하려니 만들어놓은 CSS 이미지 비율이 깨져서 2장으로 나눠 캡쳐해 업로드 합니다.

**Comment by Gjunghoon** [comment]
권중훈
https://github.com/Gjunghoon/LIKELION-Assignment
![K-001](https://user-images.githubusercontent.com/44766030/55284475-7690dc80-53b2-11e9-8e24-7d4f693eae22.png)

**Comment by ghost** [comment]
이정우
https://github.com/jwibanes/insta_assignment
![HTML 과제](https://user-images.githubusercontent.com/48678295/55284668-3895b780-53b6-11e9-83ed-b8334047a954.png)

**Comment by 10kdkd** [comment]
김동제
https://github.com/10kdkd/first_repo
![image](https://user-images.githubusercontent.com/48678281/55286556-05fcb680-53d8-11e9-849c-7e889e788a92.png)

**Comment by swcho9919** [comment]
https://github.com/swcho9919/first_repository
![instagram_bootsrap](https://user-images.githubusercontent.com/46709390/55286631-2711d700-53d9-11e9-9a49-6b4b9a981dd1.PNG)

**Comment by SoniaComp** [comment]
박선영(뚝배기를 피해서, 인라인스타일 다 class로 바꿨습니당!)
<img width="1336" alt="스크린샷 2019-04-01 오전 8 08 28" src="https://user-images.githubusercontent.com/45381486/55296512-7eee2380-5455-11e9-8145-bee020d010cb.png">
https://github.com/SoniaComp/NEXT/tree/master/html_advanced_exercise

**Comment by SeeunChoi1** [comment]
https://github.com/SeeunChoi1/homework_instagram
![인스타그램](https://user-images.githubusercontent.com/37589355/55299921-309a4e00-5470-11e9-9aee-cf3a39b530ba.png)
최세은

**Comment by KimKangYeon** [comment]
![image](https://user-images.githubusercontent.com/48678290/55302383-eb7c1900-547b-11e9-8d5d-27acde1b08da.png)

https://github.com/KimKangYeon/homework1

**Comment by YUNALEEEE** [comment]
이유나
https://github.com/YUNALEEEE/Instagram_exercise
![instagram_css](https://user-images.githubusercontent.com/48678302/55303140-6e52a300-547f-11e9-8dc9-761fbeb8611b.JPG)

**Comment by gaetokk** [comment]
안태경
https://github.com/gaetokk/LIKELION_2019
![0328css](https://user-images.githubusercontent.com/46814961/55304733-ed4bd980-5487-11e9-92db-3b3e23e45f69.jpg)

**Comment by hoiJuwon** [comment]
https://github.com/hoiJuwon/instagramAssignment/tree/master
<img width="1558" alt="instagram" src="https://user-images.githubusercontent.com/47557351/55306145-09eb1000-548e-11e9-987c-ee8aadd9820c.png">

**Comment by NamJaeyong** [comment]
https://github.com/NamJaeyong/instaNam.git
![인스타](https://user-images.githubusercontent.com/48678278/55308178-dbbcfe80-5494-11e9-9c29-09479d634f19.png)

**Comment by Gentleman37** [comment]
<img width="1253" alt="스크린샷 2019-04-01 오후 2 17 54" src="https://user-images.githubusercontent.com/35323749/55308918-1aec4f00-5497-11e9-9d23-8ca5df1e9946.png">

https://github.com/mangod037/first_repo/tree/master/insta
이경연입니다

**Comment by FriedPotato-hash** [comment]
https://github.com/080101/homework
![image](https://user-images.githubusercontent.com/48678324/55311302-820d0200-549d-11e9-8cd7-a27f7f3d5ae6.png)

김세연~!

**Comment by miramira227** [comment]
김미라 
![image](https://user-images.githubusercontent.com/48576190/55313181-1d07db00-54a2-11e9-99b7-06c87fcca126.png)

https://github.com/miramira227/gwaje_mira2.git

**Comment by kimjaehun96** [comment]
김재훈
https://github.com/kimjaehun96/first_repository
![jhstagram](https://user-images.githubusercontent.com/48678264/55313937-02366600-54a4-11e9-9cb6-4a151ddb45d0.png)
