### ISSUE TITLE
[4/4 Python 심화 과제]

### ISSUE THREAD

**Issue by hyunjaeyou** [NEXT-LIKELION/Assignment#27]
- 4/1 수업 교안에 나와 있는 과제입니다
**마감일 : 4/4 수업 전까지**

1. 모듈, 클래스, 함수를 이용한 계산기를 만들고 본인 깃허브에 업로드 후 댓글로 링크를 남겨주세요
2. hackerrank.com에서 문제를 푸신 후에 스크린샷을 캡쳐해서 댓글로 달아주세요

- 댓글에는 **본인 이름, 링크, 스크린샷**이 있어야 합니다
  화이팅!

**Comment by RyanKor** [comment]
김승태
![image](https://user-images.githubusercontent.com/40455392/55369327-183e3800-5531-11e9-8ad9-79ed9278b642.png)
이미지 1 (위) Hackerrank 과제 완료


![image](https://user-images.githubusercontent.com/40455392/55380950-bdbad100-555c-11e9-8091-33f544691b5b.png)

이미지 2(위) 모듈을 활용한 파이썬 계산기 과제 완료

과제 수정사항 반영해서 업로드 합니다.

Github URL : https://github.com/RyanKor/Next-x-Likelion/tree/master/python_module

**Comment by swcho9919** [comment]
![hackerrank](https://user-images.githubusercontent.com/46709390/55374711-6e68a680-5544-11e9-942e-80c64f86b69e.PNG)
![renew_calculator](https://user-images.githubusercontent.com/46709390/55380375-f78ad800-555a-11e9-9960-78145bf0132f.PNG)

https://github.com/swcho9919/first_repository
조성우

**Comment by elksha** [comment]
김준태
https://github.com/elksha/Next/tree/master/python_exercise2/python_module
(폴더 내의 calculator.py, module.py 입니다)

![E131A2F4-694B-438E-A6C2-E3BAC2B03796](https://user-images.githubusercontent.com/43684130/55378229-12594e80-5553-11e9-9d63-b17cefa0d26e.jpeg)

**Comment by Gentleman37** [comment]
이경연
https://github.com/mangod037/first_repo/tree/master/python_module
<img width="400" alt="스크린샷 2019-04-02 오후 2 58 19" src="https://user-images.githubusercontent.com/35323749/55379449-19cf2680-5558-11e9-88ae-56eb45d004d3.png">

<img width="448" alt="스크린샷 2019-04-02 오후 3 01 21" src="https://user-images.githubusercontent.com/35323749/55379488-3703f500-5558-11e9-9993-751d04f5b5fa.png">

**Comment by ghost** [comment]
이정우
https://github.com/jwibanes/assignment (calculator, module 파일)
![hackerrank](https://user-images.githubusercontent.com/48678295/55406162-836e2580-5596-11e9-83f5-e58462106e70.png)

**Comment by antlikelion** [comment]
이인우
https://github.com/antlikelion/python_practice
<img width="278" alt="파이썬" src="https://user-images.githubusercontent.com/48678284/55476634-1324da00-5652-11e9-8649-6ec0d5ee066f.png">

**Comment by vhvha** [comment]
장주희
https://github.com/vhvha/assignment_likelion
![캡처1](https://user-images.githubusercontent.com/46235386/55510571-843bb000-5699-11e9-994f-2b7ab05e48fd.PNG)
![캡처2](https://user-images.githubusercontent.com/46235386/55510573-856cdd00-5699-11e9-96f4-02b5296ddf51.PNG)

**Comment by juno1028** [comment]
김준오
https://github.com/juno1028/python_calculator
<img width="330" alt="Screen Shot 2019-04-04 at 9 52 35 AM" src="https://user-images.githubusercontent.com/45659499/55522434-f1623c00-56bf-11e9-92f1-4a86e0766ad6.png">
<img width="459" alt="Screen Shot 2019-04-04 at 9 55 53 AM" src="https://user-images.githubusercontent.com/45659499/55522440-f7581d00-56bf-11e9-8f85-4f293e9fd0a9.png">

**Comment by jihakwoo** [comment]
우지학
![image](https://user-images.githubusercontent.com/44742935/55526708-ff6c8880-56d0-11e9-8a0e-0701871226b1.png)


https://github.com/woojeee/python_ass2_calculator

**Comment by Gjunghoon** [comment]
권중훈
https://github.com/Gjunghoon/python_assignment
![K-002](https://user-images.githubusercontent.com/44766030/55528960-d00e4980-56d9-11e9-8194-1260ac547b80.png)
![K-003](https://user-images.githubusercontent.com/44766030/55528962-d00e4980-56d9-11e9-930a-15bac8472e16.png)

**Comment by SeeunChoi1** [comment]
최세은
https://github.com/SeeunChoi1/python_module
![image](https://user-images.githubusercontent.com/37589355/55529418-50ce4500-56dc-11e9-965a-447b04d01270.png)

**Comment by parkjihwanjay** [comment]
박지환
https://github.com/parkjihwanjay/python_assignment
<img width="312" alt="과제6(hackerrank)" src="https://user-images.githubusercontent.com/48053238/55531541-c7237500-56e5-11e9-8e58-842135fb0d94.PNG">

**Comment by YUNALEEEE** [comment]
이유나
https://github.com/YUNALEEEE/Calculator_exercise
![hackerrank 인증](https://user-images.githubusercontent.com/48678302/55531866-c63f1300-56e6-11e9-9c03-70cc46b34960.JPG)

**Comment by 10kdkd** [comment]
김동제, 계산기는 calculator.py입니다!
https://github.com/10kdkd/first_repo
![image](https://user-images.githubusercontent.com/48678281/55535228-7fa2e600-56f1-11e9-8d02-b22b2408ac8f.png)

**Comment by SoniaComp** [comment]
박선영
https://github.com/SoniaComp/NEXT/tree/master/python_module
<img width="614" alt="스크린샷 2019-04-04 오후 4 29 27" src="https://user-images.githubusercontent.com/45381486/55537367-fabacb00-56f6-11e9-8b15-bc3ac4bd0d03.png">
<img width="485" alt="스크린샷 2019-04-04 오전 11 13 05" src="https://user-images.githubusercontent.com/45381486/55537370-fbebf800-56f6-11e9-8567-d98554145b09.png">

**Comment by jojoboy2212** [comment]
https://github.com/jojoboy2212/Likelion-Assignment
조형제
<img width="584" alt="스크린샷 2019-04-04 오후 4 55 05" src="https://user-images.githubusercontent.com/43463542/55539731-5471c400-56fc-11e9-9478-1aa6764be70f.png">
<img width="606" alt="스크린샷 2019-04-03 오후 9 11 15" src="https://user-images.githubusercontent.com/43463542/55539734-56d41e00-56fc-11e9-9b51-f4b9a88bb81b.png">

**Comment by wSuhye** [comment]
안수혜
https://github.com/wSuhye/SU/blob/master/mod.py
![캡처](https://user-images.githubusercontent.com/48678364/55540485-12498200-56fe-11e9-8142-5bbd8ce34e72.JPG)

**Comment by miramira227** [comment]
김미라 
![image](https://user-images.githubusercontent.com/48576190/55541343-cdbee600-56ff-11e9-80b5-90bbe0f00300.png)
https://github.com/miramira227/calculator.git

**Comment by kimjaehun96** [comment]
김재훈
(1)모듈을 이용한 파이썬 계산기
![calculator](https://user-images.githubusercontent.com/48678264/55540824-b92e1e00-56fe-11e9-9e7a-0f5ef994fc3b.png)
https://github.com/kimjaehun96/calculator 중에 calculator2.py입니당~
(2)
![해커랭크](https://user-images.githubusercontent.com/48678264/55547013-63ac3e00-570b-11e9-87a4-1f66bf7056db.png)

**Comment by KimKangYeon** [comment]
김강연
https://github.com/KimKangYeon/homework1
![image](https://user-images.githubusercontent.com/48678290/55543822-c9e19280-5704-11e9-91f0-3416aeaead1d.png)
![image](https://user-images.githubusercontent.com/48678290/55543840-d108a080-5704-11e9-9ce1-8d54db849cb1.png)
![image](https://user-images.githubusercontent.com/48678290/55543853-d534be00-5704-11e9-9489-e2712f0bcd5a.png)

**Comment by gaetokk** [comment]
https://github.com/gaetokk/LIKELION_2019
(mod랑 calculator파일입니당)
안태경

![0401과제](https://user-images.githubusercontent.com/46814961/55544110-5d1ac800-5705-11e9-91d8-e45891fac918.jpg)

**Comment by NamJaeyong** [comment]
남재용
1. 계산기
https://github.com/NamJaeyong/calculatorNam
2. 해커랭크
![image](https://user-images.githubusercontent.com/48678278/55544853-ef6f9b80-5706-11e9-952f-9e8dda9d9a00.png)

**Comment by chaeyeonie** [comment]
이채연
![image](https://user-images.githubusercontent.com/48678352/55543803-bfbf9400-5704-11e9-80ea-786e168048aa.png)

https://github.com/chaeyeonie/eeeee.git

**Comment by updownC** [comment]
최상하
1. calculator https://github.com/sanghaC/Assignment
2.<img width="312" alt="과제" src="https://user-images.githubusercontent.com/48586856/55545546-678a9100-5708-11e9-8cf0-391070f9c3bd.png">

**Comment by hoiJuwon** [comment]
1. python_calculator : https://github.com/hoiJuwon/python_module

2.
<img width="1120" alt="스크린샷 2019-04-04 오후 6 59 12" src="https://user-images.githubusercontent.com/47557351/55547198-c271b780-570b-11e9-94d7-728f495336d3.png">
