### ISSUE TITLE
[4/8 django 실습 과제]

### ISSUE THREAD

**Issue by jihyuunn** [NEXT-LIKELION/Assignment#28]
- 마감 : 4월 8일 월요일 세션 전까지
- 구글 드라이브에 올라와있는 4월 4일 교안에 과제 설명 있습니다
- 모르는 것 있으면 파이빌로 오시거나 언제든 카톡으로 물어봐주세요 !
- 소스코드를 자신의 깃헙에 올리고, result화면을 캡쳐하여 올려주세요(이름도..)

**Comment by juno1028** [comment]
김준오
https://github.com/juno1028/django_practice
<img width="726" alt="Screen Shot 2019-04-04 at 11 06 08 PM" src="https://user-images.githubusercontent.com/45659499/55562754-91a37980-572f-11e9-884d-b77bde852e83.png">

**Comment by elksha** [comment]
김준태
https://github.com/elksha/Next/tree/master/django_exercise

![assignment](https://user-images.githubusercontent.com/43684130/55563653-4d18dd80-5731-11e9-9b43-2c84ce28764e.png)

**Comment by Gjunghoon** [comment]
권중훈
https://github.com/Gjunghoon/django_practice
![K-001](https://user-images.githubusercontent.com/44766030/55606164-ba208780-57b2-11e9-8834-f500f1647c7b.png)

**Comment by Gentleman37** [comment]
이경연입니다
https://github.com/mangod037/first_repo/tree/master/04.04

<img width="705" alt="스크린샷 2019-04-05 오후 3 22 22" src="https://user-images.githubusercontent.com/35323749/55607331-dde5cc80-57b6-11e9-80f8-a2d83ae7024e.png">

**Comment by swcho9919** [comment]
조성우
![django_1](https://user-images.githubusercontent.com/46709390/55616328-8c483c80-57cc-11e9-8634-f9b5bda7c90d.PNG)
https://github.com/swcho9919/django-first.git

**Comment by SoniaComp** [comment]
박선영
<img width="448" alt="django1_1" src="https://user-images.githubusercontent.com/45381486/55638331-e7485680-5801-11e9-9f8a-1e8691562253.png">
<img width="506" alt="django1_2" src="https://user-images.githubusercontent.com/45381486/55638351-edd6ce00-5801-11e9-9ac6-29b51eb576e7.png">
https://github.com/SoniaComp/NEXT/tree/master/django_2/countinghw

**Comment by jojoboy2212** [comment]
조형제
https://github.com/jojoboy2212/LikeLion-Django
<img width="820" alt="스크린샷 2019-04-07 오후 4 07 13" src="https://user-images.githubusercontent.com/43463542/55680005-3bad1c80-594f-11e9-83a4-4d489b18a947.png">

**Comment by KimKangYeon** [comment]
김강연
https://github.com/KimKangYeon/NEXT_2
![image](https://user-images.githubusercontent.com/48678290/55682505-99e9f780-596f-11e9-9526-cd7bf5c6b4e5.png)

**Comment by wSuhye** [comment]
안수혜
https://github.com/wSuhye/Django_wordcount
![캡처](https://user-images.githubusercontent.com/48678364/55682848-b425d480-5973-11e9-8b3c-87985fa865b5.JPG)

**Comment by RyanKor** [comment]
김승태

![image](https://user-images.githubusercontent.com/40455392/55687270-11d31480-59a6-11e9-8822-1ede43c90b9c.png)



git URL: https://github.com/RyanKor/Next-x-Likelion/tree/master/assignment4

**Comment by SoniaComp** [comment]
박선영
<img width="490" alt="스크린샷 2019-04-08 오전 12 00 41" src="https://user-images.githubusercontent.com/45381486/55685461-83549800-5991-11e9-9a97-6420c42a4f74.png">

**Comment by antlikelion** [comment]
이인우
https://github.com/antlikelion/django_practice
<img width="941" alt="killme" src="https://user-images.githubusercontent.com/48678284/55687199-42ff1500-59a5-11e9-9262-e56104eaa7f6.png">

**Comment by 10kdkd** [comment]
김동제
![어무이](https://user-images.githubusercontent.com/48678281/55689209-c0824f80-59bc-11e9-8faf-d1f464e1eeb2.png)
https://github.com/10kdkd/first_repo/tree/master/Django

**Comment by ghost** [comment]
이정우
https://github.com/jwibanes/assignment/tree/master/Pipenv

![인생](https://user-images.githubusercontent.com/48678295/55696680-11179e00-59f9-11e9-8dac-beedc1b848c3.png)

**Comment by SeeunChoi1** [comment]
최세은
https://github.com/SeeunChoi1/Django_counting_sametext
![image](https://user-images.githubusercontent.com/37589355/55701261-7c6b6b00-5a0d-11e9-8fd6-e1ea2680fc01.png)

**Comment by hoiJuwon** [comment]
최주원
https://github.com/hoijuwoncodes/django_assignment

<img width="640" alt="스크린샷 2019-04-08 오후 2 55 54" src="https://user-images.githubusercontent.com/47557351/55701772-69f23100-5a0f-11e9-9654-a508d2825535.png">

**Comment by miramira227** [comment]
김미라 

![image](https://user-images.githubusercontent.com/48576190/55703912-e2f48700-5a15-11e9-97b9-0743d9842e65.png)

https://github.com/miramira227/miramara.git

**Comment by jihakwoo** [comment]
우지학

![image](https://user-images.githubusercontent.com/44742935/55704347-cad13780-5a16-11e9-835f-4845ee5d0b1f.png)


![image](https://user-images.githubusercontent.com/44742935/55704234-99586c00-5a16-11e9-8004-a1619486fe6d.png)

https://github.com/woojeee/django_WordCounting

**Comment by gaetokk** [comment]
https://github.com/gaetokk/LIKELION_2019

![image](https://user-images.githubusercontent.com/46814961/55704620-8befb180-5a17-11e9-8b18-612367bf114b.png)
안태경

**Comment by parkjihwanjay** [comment]
박지환
https://github.com/parkjihwanjay/django_assignment
<img width="394" alt="과제7(입력)" src="https://user-images.githubusercontent.com/48053238/55708949-2228d500-5a22-11e9-85c4-ff1a690268a7.PNG">
<img width="939" alt="과제8(출력)" src="https://user-images.githubusercontent.com/48053238/55708958-2523c580-5a22-11e9-9af4-02c775973d4f.PNG">

**Comment by NamJaeyong** [comment]
남재용
https://github.com/NamJaeyong/wordcountingNam.git
![image](https://user-images.githubusercontent.com/48678278/55711329-6bc7ee80-5a27-11e9-955f-4d248e297786.png)

**Comment by YUNALEEEE** [comment]
이유나
https://github.com/YUNALEEEE/words_counter_exercise
![쟝고 과제](https://user-images.githubusercontent.com/48678302/55712832-67510500-5a2a-11e9-93e2-cb9a6177a86d.JPG)

**Comment by vhvha** [comment]
장주희
https://github.com/vhvha/django1
![캡처3](https://user-images.githubusercontent.com/46235386/55714235-3faf6c00-5a2d-11e9-8eeb-9902081365de.PNG)

**Comment by FriedPotato-hash** [comment]
김세연

https://github.com/080101/homework/tree/master/django_hw1/hwhwhw

**Comment by updownC** [comment]
https://github.com/sanghaC/django_assignment
![wordcount](https://user-images.githubusercontent.com/48586856/55714742-2824b300-5a2e-11e9-8a41-66c1a21bb248.jpg)

**Comment by chaeyeonie** [comment]
이채연
https://github.com/chaeyeonie/4-8.git
![image](https://user-images.githubusercontent.com/48678352/55791833-57a0f180-5afa-11e9-90b4-29e12b762450.png)
