### ISSUE TITLE
[4/11 Django CRUD 과제]

### ISSUE THREAD

**Issue by jihyuunn** [NEXT-LIKELION/Assignment#29]
- 마감 : 4월 11일 목요일 세션 전까지
- 구글 드라이브에 올라와있는 4월 8일 교안에 과제 설명 있습니다
- 모르는 것 있으면 파이빌로 오시거나 언제든 카톡으로 물어봐주세요 !
- 소스코드를 자신의 깃헙에 올리고, detail페이지와 new페이지를 캡쳐해서 올려주세요(이름도..)

**Comment by swcho9919** [comment]
![newww](https://user-images.githubusercontent.com/46709390/55795701-5e803200-5b03-11e9-9f9e-a1a04875dff5.PNG)
조성우
https://github.com/swcho9919/django_bookreviewblog
![끼리네책방](https://user-images.githubusercontent.com/46709390/55795054-db121100-5b01-11e9-9f59-6d85c66e1102.PNG)

**Comment by antlikelion** [comment]
이인우
https://github.com/antlikelion/django

<img width="381" alt="detail" src="https://user-images.githubusercontent.com/48678284/55820574-63aaa480-5b36-11e9-88b9-3bbcd29230dd.png">

<img width="312" alt="new" src="https://user-images.githubusercontent.com/48678284/55820587-673e2b80-5b36-11e9-8cad-c04d0a97c98a.png">

**Comment by vhvha** [comment]
장주희
https://github.com/vhvha/bookreview/tree/master/bookrv
![캡처0](https://user-images.githubusercontent.com/46235386/55845651-bb203300-5b7d-11e9-9089-9b21b76faad1.PNG)
![캡처00](https://user-images.githubusercontent.com/46235386/55845652-bc516000-5b7d-11e9-9523-26bf2e003e6c.PNG)
![캡처000](https://user-images.githubusercontent.com/46235386/55845653-bd828d00-5b7d-11e9-9a58-79351f8422d7.PNG)

**Comment by Gentleman37** [comment]
https://github.com/mangod037/first_repo/tree/master/04.08
이경연입니다
<img width="369" alt="스크린샷 2019-04-10 오후 2 00 40" src="https://user-images.githubusercontent.com/35323749/55854156-c899e500-5b9e-11e9-89e5-af8a81cfccef.png">
<img width="369" alt="스크린샷 2019-04-10 오후 2 05 07" src="https://user-images.githubusercontent.com/35323749/55854160-cfc0f300-5b9e-11e9-97a9-53c35090f08d.png">
<img width="369" alt="스크린샷 2019-04-10 오후 2 05 17" src="https://user-images.githubusercontent.com/35323749/55854169-d64f6a80-5b9e-11e9-876d-aa20bb42c6da.png">

**Comment by YUNALEEEE** [comment]
이유나
https://github.com/YUNALEEEE/bookreview_exercise
![책리뷰home](https://user-images.githubusercontent.com/48678302/55860864-2256db00-5bb0-11e9-924a-d2a622658c6c.JPG)
![책리뷰쓰기](https://user-images.githubusercontent.com/48678302/55860871-24209e80-5bb0-11e9-905c-65c20fa91036.JPG)

**Comment by juno1028** [comment]
김준오
https://github.com/juno1028/4_8
<img width="427" alt="Screen Shot 2019-04-10 at 4 50 29 PM" src="https://user-images.githubusercontent.com/45659499/55861418-4ff05400-5bb1-11e9-81bf-ab6ed1357864.png">
<img width="296" alt="Screen Shot 2019-04-10 at 4 51 11 PM" src="https://user-images.githubusercontent.com/45659499/55861424-54b50800-5bb1-11e9-81d5-6f9bc7336f96.png">

**Comment by jojoboy2212** [comment]
조형제
https://github.com/jojoboy2212/Django_prac0408
<img width="477" alt="스크린샷 2019-04-10 오후 5 06 36" src="https://user-images.githubusercontent.com/43463542/55862445-70b9a900-5bb3-11e9-8335-2a30b280a377.png">
<img width="374" alt="스크린샷 2019-04-10 오후 5 06 23" src="https://user-images.githubusercontent.com/43463542/55862452-744d3000-5bb3-11e9-9d8b-1ba4266cc008.png">
<img width="293" alt="스크린샷 2019-04-10 오후 5 06 30" src="https://user-images.githubusercontent.com/43463542/55862457-76af8a00-5bb3-11e9-98b8-11c3c124e636.png">

**Comment by chaeyeonie** [comment]
이채연
https://github.com/chaeyeonie/crud.git
![image](https://user-images.githubusercontent.com/48678352/55870522-ba11f480-5bc3-11e9-8344-d0c77f3569f3.png)
![image](https://user-images.githubusercontent.com/48678352/55870675-0bba7f00-5bc4-11e9-99b6-5f3b9f5a38aa.png)
![image](https://user-images.githubusercontent.com/48678352/55870697-1543e700-5bc4-11e9-916c-499c8a7aac03.png)

**Comment by SeeunChoi1** [comment]
최세은
https://github.com/SeeunChoi1/Django_bookrate
![image](https://user-images.githubusercontent.com/37589355/55871245-3953f800-5bc5-11e9-9eef-2e25e4ee57ba.png)
![image](https://user-images.githubusercontent.com/37589355/55871264-41ac3300-5bc5-11e9-9570-ac2bf03c284a.png)
![image](https://user-images.githubusercontent.com/37589355/55871351-6bfdf080-5bc5-11e9-8bfb-ef22c7966250.png)

**Comment by Gjunghoon** [comment]
권중훈
https://github.com/Gjunghoon/django_crud_practice
![K-001](https://user-images.githubusercontent.com/44766030/55874100-593aea00-5bcc-11e9-928e-b9075193d0d6.png)
![K-002](https://user-images.githubusercontent.com/44766030/55874104-5b9d4400-5bcc-11e9-8c34-973847cabf55.png)
![K-003](https://user-images.githubusercontent.com/44766030/55874107-5d670780-5bcc-11e9-9fec-9223c75aebde.png)

**Comment by hoiJuwon** [comment]
최주원
https://github.com/hoiJuwon/CRUD_assignment
<img width="515" alt="스크린샷 2019-04-10 오후 8 24 41" src="https://user-images.githubusercontent.com/47557351/55874984-d9624f00-5bce-11e9-9fdc-7ae92e686424.png">
<img width="407" alt="스크린샷 2019-04-10 오후 8 25 35" src="https://user-images.githubusercontent.com/47557351/55874990-dcf5d600-5bce-11e9-80bf-608df7981413.png">
<img width="313" alt="스크린샷 2019-04-10 오후 8 25 45" src="https://user-images.githubusercontent.com/47557351/55874992-df583000-5bce-11e9-989c-aa648c3631e2.png">

**Comment by parkjihwanjay** [comment]
박지환
https://github.com/parkjihwanjay/django_assignment2

<img width="216" alt="과제(장고1)" src="https://user-images.githubusercontent.com/48053238/55875653-8a1d1e00-5bd0-11e9-814c-b2529283b4a6.PNG">
<img width="338" alt="과제(장고2" src="https://user-images.githubusercontent.com/48053238/55875657-8be6e180-5bd0-11e9-98a0-d5360d05d65a.PNG">

**Comment by elksha** [comment]
김준태
https://github.com/elksha/Next/tree/master/crud_assignment
![이미지 001](https://user-images.githubusercontent.com/43684130/55888867-1ccab680-5beb-11e9-89e0-e3453f7ce5c5.png)
![이미지 002](https://user-images.githubusercontent.com/43684130/55888869-1d634d00-5beb-11e9-9319-1d5e466d3f3b.png)
![이미지 003](https://user-images.githubusercontent.com/43684130/55888870-1dfbe380-5beb-11e9-83ff-9928f3f42052.png)

**Comment by KimKangYeon** [comment]
김강연
![image](https://user-images.githubusercontent.com/48678290/55885594-3668ff80-5be5-11e9-98fc-1e6e4043ce56.png)
![image](https://user-images.githubusercontent.com/48678290/55885600-3963f000-5be5-11e9-95d5-67f774bde800.png)
![image](https://user-images.githubusercontent.com/48678290/55885692-60222680-5be5-11e9-8ffb-89289cb24f20.png)
https://github.com/KimKangYeon/bookrating/tree/master/Bookrating/book/bookrate

**Comment by RyanKor** [comment]
김승태
[이미지 1. Main page]

![image](https://user-images.githubusercontent.com/40455392/55891810-2c003300-5bf0-11e9-87eb-cd5e39e2bc3d.png)

[이미지 2. 게시글 생성하기]

![image](https://user-images.githubusercontent.com/40455392/55891872-4a662e80-5bf0-11e9-84e5-1962ba2bb4cb.png)

[이미지 3. 게시글 내용 확인하기]

![image](https://user-images.githubusercontent.com/40455392/55891901-5651f080-5bf0-11e9-848d-849c05a373f1.png)

Github : https://github.com/RyanKor/Next-x-Likelion/tree/master/assignment5

**Comment by 10kdkd** [comment]
김동제
https://github.com/10kdkd/first_repo
![1](https://user-images.githubusercontent.com/48678281/55896113-87ceba00-5bf8-11e9-8c8a-da135090fd20.PNG)
![2](https://user-images.githubusercontent.com/48678281/55896119-89987d80-5bf8-11e9-9c86-1f698d8300ae.PNG)

**Comment by SoniaComp** [comment]
박선영
https://github.com/SoniaComp/NEXT/tree/master/book
<img width="1056" alt="스크린샷 2019-04-11 오전 2 31 58" src="https://user-images.githubusercontent.com/45381486/55900493-493dfd00-5c02-11e9-8eb6-68ca3dc2fb8b.png">

**Comment by miramira227** [comment]
김미라 
![image](https://user-images.githubusercontent.com/48576190/55936078-3cf08900-5c70-11e9-873e-aed7902931c0.png)
https://github.com/miramira227/Bookreview.git

**Comment by gaetokk** [comment]
https://github.com/gaetokk/Django_crud/tree/master/crud
안태경
![장고과제0411](https://user-images.githubusercontent.com/46814961/55938643-c86d1880-5c76-11e9-9905-def0b3c87725.jpg)
![장고과제0411_2](https://user-images.githubusercontent.com/46814961/55938644-c86d1880-5c76-11e9-861e-3d2a121b3101.jpg)

![0411과제](https://user-images.githubusercontent.com/46814961/55938950-80022a80-5c77-11e9-981c-7695ee46b8a9.jpg)

**Comment by jihakwoo** [comment]
![image](https://user-images.githubusercontent.com/44742935/55941204-b9896480-5c7c-11e9-8b05-82c5063de1a7.png)
<img width="407" alt="캡처" src="https://user-images.githubusercontent.com/44742935/55940998-3d8f1c80-5c7c-11e9-82ae-33929428bc5b.PNG">
<img width="370" alt="캡처2" src="https://user-images.githubusercontent.com/44742935/55941004-4122a380-5c7c-11e9-9423-060ae41f32b7.PNG">

https://github.com/woojeee/django_bookreview
우지학

**Comment by NamJaeyong** [comment]
남재용
![image](https://user-images.githubusercontent.com/48678278/55947798-29521c00-5c8a-11e9-93ce-087844ee38ec.png)
![image](https://user-images.githubusercontent.com/48678278/55947813-2fe09380-5c8a-11e9-876d-c7157056d0da.png)
![image](https://user-images.githubusercontent.com/48678278/55947856-425acd00-5c8a-11e9-9d1f-1a958260c52c.png)
https://github.com/NamJaeyong/bookreviewNam

**Comment by updownC** [comment]
https://github.com/sanghaC/django_assignment2

**Comment by ghost** [comment]
https://github.com/jwibanes/assignment
이정우
ㅠ
![1](https://user-images.githubusercontent.com/48678295/56007490-dcb32300-5d13-11e9-96e4-efe9d06cc0c9.png)
![2](https://user-images.githubusercontent.com/48678295/56007491-de7ce680-5d13-11e9-973b-bee892af0ec9.png)
