### ISSUE TITLE
1주차 과제(2) - HTML & CSS + 구글링

### ISSUE THREAD

**Issue by poongnewga** [NEXT-LIKELION/Assignment#3]
## HTML & CSS + 구글링

- [x] 김민형
- [x] 김보성
- [x] 김지현
- [x] 박승준
- [x] 방혜주
- [x] 배영현
- [x] 성인규
- [x] 손지연
- [x] 신예찬
- [x] 신한결
- [x] 안성수
- [x] 엄가람
- [x] 오상우
- [x] 원혜진
- [x] 유선아
- [x] 유정아
- [x] 유현재
- [x] 이수영
- [x] 이윤비
- [x] 이재승
- [x] 이정민
- [x] 이지원
- [x] 이지현
- [x] 장민규
- [x] 장영재
- [x] 전재현
- [x] 전준표
- [x] 주기현
- [x] 최희윤
- [x] 한승희
- [x] 허예림
- [x] 허재혁

---

- 32 / 32 명 완료

**Comment by norrard148** [comment]
장영재
![default](https://user-images.githubusercontent.com/37537262/37811887-0164ef06-2ea0-11e8-8a3a-431b1c05610a.PNG)

**Comment by poongnewga** [comment]
@norrard148 완벽합니다 :)

**Comment by gyeol1212** [comment]
신한결
![2018-03-24 1 32 05](https://user-images.githubusercontent.com/37537201/37841521-45d90b14-2f03-11e8-93df-7268bff17151.png)

**Comment by jason2133** [comment]
![default](https://user-images.githubusercontent.com/37537208/37853889-f7ba8af6-2f2b-11e8-8a13-fd2dc3c749da.png)

이재승

**Comment by preeminent77** [comment]
<img width="159" alt="homework3" src="https://user-images.githubusercontent.com/37537194/37861112-203b6dde-2f76-11e8-9882-9623a2826071.png">

전재현

**Comment by preeminent77** [comment]
<img width="239" alt="homework3" src="https://user-images.githubusercontent.com/37537194/37861149-e65a9db4-2f76-11e8-829b-e259c23c6629.png">

전재현

**Comment by Hyezzi** [comment]
![assignment3](https://user-images.githubusercontent.com/37537222/37861213-00bef708-2f78-11e8-9210-d301bf9cd9b4.jpeg)
원혜진

**Comment by dkor3** [comment]
안성수 
![3 22](https://user-images.githubusercontent.com/37537204/37863172-3b55d538-2f9d-11e8-9c06-5b1651f0549f.png)

**Comment by ingyuseong** [comment]
![2_chocoemong](https://user-images.githubusercontent.com/37537248/37864585-726d50a2-2fb4-11e8-8ea0-c027855392df.JPG)
성인규 입니다

**Comment by PoSungKim** [comment]
김보성
![_](https://user-images.githubusercontent.com/37537227/37865759-839fa8d8-2fc4-11e8-88d6-e26e4d742d67.PNG)

**Comment by jiwonny** [comment]
이지원
![image](https://user-images.githubusercontent.com/37537213/37905925-73e32618-313b-11e8-8289-5bebe6e2b070.png)

**Comment by JIHYUN1110** [comment]
김지현

![_3](https://user-images.githubusercontent.com/37537212/37868099-d25d257a-2fe4-11e8-8ec8-f589bdefc097.PNG)

**Comment by poongnewga** [comment]
@Hyezzi 아침부터 크리스피를 먹을 수 있는 건 크리스피 덕후로서 굉장히 부러운 일이지만 다음부터는 이름을 꼭 적어주도록 해요 :)

@dkor3 @jiwonny 배경이 살짝 겹치네요 :smile:  두 분은 나중에 코드 좀 봐드릴게요~

@JIHYUN1110 저도 마카롱을 진짜 진짜 좋아하는데 맛집 좀 알려주세요 :) Weekend 밑에 밑줄이 오른쪽에 붙었는데 여백을 좀 줬다면 더 좋았을 것 같아요 :)

**Comment by soonjune** [comment]
<img width="343" alt="2018-03-25 11 22 33" src="https://user-images.githubusercontent.com/37537242/37871046-ff775f8c-301e-11e8-9b49-da32142620d3.png">
박승준
스크롤바가 있긴 한데 만지지 않으면 안 보이네요 ㅠㅠ

**Comment by sangw0804** [comment]
<img width="576" alt="chris" src="https://user-images.githubusercontent.com/37537207/37871404-10cf9520-3028-11e8-9550-9afbb4fb2aae.png">
오상우

**Comment by poongnewga** [comment]
@jamie7060  왜일까요? :) 내일 코드 같이 볼게요~

**Comment by jihyuunn** [comment]
![2018-03-25 12 39 40](https://user-images.githubusercontent.com/37537223/37871883-0f6f1082-3034-11e8-9615-e6d23b7eae39.png)
이지현
저도 스크롤바가 안보여용..

**Comment by poongnewga** [comment]
@jihyuunn 내일은 꼭 꿔바로우를 먹어야겠네요 :yum: 지현님도 배경이 살짝 삐져나오고, 꿔바로우 아래의 밑줄 좌우에 여백을 주려면 어떻게 해야할까요? 내일 다같이 고민해보겠습니다

**Comment by mhbest** [comment]
![default](https://user-images.githubusercontent.com/37537238/37872110-671f1f8c-303b-11e8-894c-66ad86436fe9.PNG)
저는 사실상 웹페이지 창조가 아니라 모방했습니다ㅠㅠㅠ 이미지가 올라와야될텐데 일단 링크로 올렸습니다. 캡쳐해서 올려도 안되고 첨부도 안되서 일단 이렇게 올립니다.

**Comment by hyunjaeyou** [comment]
![default](https://user-images.githubusercontent.com/37537210/37872160-d1b3f5d8-303c-11e8-95d1-e1cc5fe585f9.png)
유현재입니다

**Comment by hy970723** [comment]
<img width="311" alt="2018-03-25 4 51 18" src="https://user-images.githubusercontent.com/37537254/37872942-d351f754-304c-11e8-93d9-8b9725d2ab47.png">


최희윤입니다 스크롤 만들었는데 스크롤바가 캡쳐할라하면 없어져요..

**Comment by woonjangahn** [comment]
![default](https://user-images.githubusercontent.com/26547475/37872808-142fa7ce-304a-11e8-9051-9fed992e1501.PNG)
채운장입니다

**Comment by Jack2ee** [comment]
허재혁
![image](https://user-images.githubusercontent.com/37537235/37872844-b69ae3d4-304a-11e8-8122-970f02f723d1.png)

**Comment by poongnewga** [comment]
@mhbest 왜 캡쳐가 안올라갈까요~? 내일 운영진이 도와줄게요 그리고 모방은 창조의 어머니죠 :)
@hyunjaeyou 이미지 정렬이 조금 아쉽죠? 내일 같이 풀어봅시다~
@hy970723 왜 그런지 알 것 같기도 하네요~ 😄 고생 많이 했고 내일 같이 알아봅시다 :)
@mikaescapel 웅장님 왜 방패를 만들어놨죠...?
@Jack2ee 아주 멋있는 시나 형님이네요! 아래쪽 스크롤은 쓰지 않으니 없으면 더 예쁠 것 같아요 ㅎㅎ

**Comment by jihyuunn** [comment]
![default](https://user-images.githubusercontent.com/37537223/37874408-9273f83c-3069-11e8-8429-ebf256aac6d7.png)

스크롤바 왜죠..?..

**Comment by X3PY** [comment]
![1-3](https://user-images.githubusercontent.com/37537209/37874452-6fe3e81c-306a-11e8-8ae3-6d7066d50c15.PNG)

전준표

**Comment by poongnewga** [comment]
@jihyuunn 밑줄이랑 배경 고치셨네요 대단합니다 :) 스크롤바... 그러게요... 왜인지는 내일 같이 알아보죠 😄
@X3PY 고생하셨습니다 :) 이미지를 정확히 가운데에 두려면 어떤 방법을 쓰면 좋을까요?

**Comment by swimmie0** [comment]
![image](https://user-images.githubusercontent.com/37537202/37877096-ed99cde6-3090-11e8-8093-943074e9efc2.png)


수정해봤어요!
이수영

**Comment by poongnewga** [comment]
@lsy044 너무 귀여운 무민이네요 😍고생하셨습니다 :) 배경과 테두리 사이에 있는 작은 공간을 없애고, 배경색 하단의 둥근 테두리를 직선으로 만들려면 어떻게 해야 할까요?

**Comment by karamie** [comment]
![_](https://user-images.githubusercontent.com/37537206/37876086-acd2665a-3082-11e8-9098-078ce0049bbf.PNG)

엄가람입니다:)

**Comment by Cecilia-L** [comment]
이윤비입니다!
<img width="423" alt="0326" src="https://user-images.githubusercontent.com/37537232/37876662-c6e66660-308a-11e8-88ee-0fc54964bc92.png">

**Comment by Yerim2695** [comment]
![default](https://user-images.githubusercontent.com/37537200/37876702-a99d3ce0-308b-11e8-8a3b-786ab46d87fe.PNG)
허예림입니다~

**Comment by poongnewga** [comment]
@karamie 마들렌도 마카롱만큼 맛있죠 :) 제가 눈이 침침해서 그런지 이미지가 조금 위로 올라간 것 같지만요
@Cecilia-L CHEEZE의 Madeleine Love 에도 마들렌이 들어가네요 먹는 것만 보이네요 ㅎㅎ 이미지를 어떻게 하면 가운데에 딱 맞출 수 있을까요? 스크롤바도 아래쪽은 없는 게 더 예쁠 것 같아요 :)
@Yerim2695 장어랑 먹으면 안된다니 처음 알았네요.. 산뜻한 배색이 인상적인데 border 두께가 살짝 차이가 나는 것 같기도...? 내일 이미지 정렬 같이 고민해봅시다 :)

**Comment by ghost** [comment]
<img width="242" alt="default" src="https://user-images.githubusercontent.com/37537219/37878526-932549ca-30a5-11e8-99e2-b95943912b80.PNG">
장민규 입니다 ~~

**Comment by Hyejoojjang** [comment]
<img width="379" alt="2018-03-26 4 06 31" src="https://user-images.githubusercontent.com/37541410/37878933-362b3ca6-30ab-11e8-86f0-e38d29b33857.png">

**Comment by poongnewga** [comment]
@MinkyuJ 저는 아이폰 X를 사고 카톡만 쓴답니다 ㅎㅎ.. border가 어째 아이폰 모양인 것 같기도 하고? 잘 만드셨어요 :)
@Hyejoojjang 가족 소개가 너무 인상적이네요 :) 이미지를 딱 가운데에 오게 하면 더 예쁘겠죠? 오늘 같이 해봐요~

**Comment by ashufflepuff** [comment]
![likelionhw02_ _](https://user-images.githubusercontent.com/37537211/37894180-edd0a9ce-30cc-11e8-8b11-7439537bf862.JPG)

유정아입니다~

**Comment by YeChan1030** [comment]
![2](https://user-images.githubusercontent.com/37537205/37894511-70113380-3119-11e8-8e54-7326959af13a.PNG)

신예찬입니다 :)
테두리 삐져나오는건 모르겠네요 ㅠㅠ

**Comment by ashufflepuff** [comment]
![_hw02_](https://user-images.githubusercontent.com/37537211/37894906-3e15deb6-30cf-11e8-864a-f41bd2c0c0a4.JPG)

유정아입니다 !

**Comment by emilyson** [comment]
<img width="248" alt="default" src="https://user-images.githubusercontent.com/37537203/37896666-416e9396-311f-11e8-841f-a0576c427257.PNG">

손지연

노란색 바탕 위에 동그라미를 올리기 위해서 relative를 썼는데 인식이 안되네요ㅠㅠㅠ

**Comment by seona-yu** [comment]
![pizza1 html css](https://user-images.githubusercontent.com/37537217/37898220-32cde6a8-3123-11e8-97dc-a7b9ce818a1e.jpg)

유선아

**Comment by kihyunjoo** [comment]
<img width="324" alt="kakaotalk_photo_2018-03-26-18-26-59_18" src="https://user-images.githubusercontent.com/37537229/37898262-4f6ab908-3123-11e8-815a-1efc4b01beb0.png">

주기현

**Comment by daisybae** [comment]
![default](https://user-images.githubusercontent.com/37537214/37900176-71625390-3128-11e8-8617-e2bd391daf95.jpg)

미완.... 과제...비슷한거...

**Comment by ssng123** [comment]
![kakaotalk_20180328_024935574](https://user-images.githubusercontent.com/37537241/37985070-ce9a98d2-3232-11e8-92d1-edde8f346bc5.jpg)
늦었지만,, 일단 제출,,, 상태가 이상한 건 지금 내가 매우 졸립기 때문,, mean,,,
다음엔 꼭꼭 미리미리 해 올게요 제성해여,,,^_ㅠ

**Comment by daisybae** [comment]
![image](https://user-images.githubusercontent.com/37537214/38017139-1c718042-32ac-11e8-8b05-fbfbb4096e12.png)
배영현입니다! 해내버렷!!!!

**Comment by qlqnf16** [comment]
<img width="238" alt="untitled" src="https://user-images.githubusercontent.com/37537216/38025245-a0371d0e-32c2-11e8-94f1-e64770045473.png">

이정민
