### ISSUE TITLE
[4/29 Django CRUD 과제 2]

### ISSUE THREAD

**Issue by jihyuunn** [NEXT-LIKELION/Assignment#30]
- 마감 : 4월 29일 월요일 세션 전까지
- 과제 : 4월 11일 교안에 나와있습니다
- 이번과제는 저번 과제했던 파일에 U,D기능 추가 및 CSS와 부트스트랩으로 꾸미면 됩니다
- 메인페이지, edit 페이지, delete 버튼이 보이도록 캡쳐 + 깃헙에 주소 올려주세요(이름도!)

**Comment by Gjunghoon** [comment]
권중훈
https://github.com/Gjunghoon/django_crud_practice
![K-001](https://user-images.githubusercontent.com/44766030/56481131-717a0580-64f8-11e9-9fa3-b6041a2c4c4a.png)
![K-002](https://user-images.githubusercontent.com/44766030/56481132-72ab3280-64f8-11e9-9650-bc6b0f5e1194.png)
![K-003](https://user-images.githubusercontent.com/44766030/56481133-73dc5f80-64f8-11e9-9309-70f08c86b525.png)
![K-004](https://user-images.githubusercontent.com/44766030/56481135-7474f600-64f8-11e9-8b59-f78dcc042a5c.png)

**Comment by RyanKor** [comment]
김승태
![image](https://user-images.githubusercontent.com/40455392/56494776-64780900-652e-11e9-9568-33ca7ba379b9.png)

![image](https://user-images.githubusercontent.com/40455392/56494781-69d55380-652e-11e9-9993-10039bd14d13.png)

![image](https://user-images.githubusercontent.com/40455392/56494787-6fcb3480-652e-11e9-9b10-cddfa188ada9.png)

![image](https://user-images.githubusercontent.com/40455392/56494823-8a051280-652e-11e9-8039-f1688a9de902.png)

Models.py에 ImageField 추가하면서 Create/Edit 기능에 사진 업로드하면 DB에 이미지가 업로드 되는 건 정상적으로 확인했는데, 썸네일 변경이 도무지 안되서 우선 작성한 부분만큼만 업로드합니다.

**Comment by antlikelion** [comment]
이인우
https://github.com/antlikelion/django
<img width="864" alt="메인" src="https://user-images.githubusercontent.com/48678284/56868419-2c406100-6a2d-11e9-856a-813819c5de3e.png">
<img width="863" alt="새로작성" src="https://user-images.githubusercontent.com/48678284/56868421-319dab80-6a2d-11e9-9ddb-3df05176a75a.png">
<img width="864" alt="수정" src="https://user-images.githubusercontent.com/48678284/56868422-34989c00-6a2d-11e9-8d31-bcc17879f6a1.png">
<img width="863" alt="삭제버튼" src="https://user-images.githubusercontent.com/48678284/56868426-37938c80-6a2d-11e9-9329-dd1a41e1a82b.png">

**Comment by jihakwoo** [comment]
<img width="948" alt="마1" src="https://user-images.githubusercontent.com/44742935/56872350-1352a280-6a63-11e9-9fd8-065073a3e1ca.PNG">
<img width="947" alt="마2" src="https://user-images.githubusercontent.com/44742935/56872351-1352a280-6a63-11e9-94cb-7177f969dae4.PNG">
<img width="947" alt="마3" src="https://user-images.githubusercontent.com/44742935/56872352-1352a280-6a63-11e9-83f2-b69f1e640f81.PNG">
<img width="947" alt="마4" src="https://user-images.githubusercontent.com/44742935/56872354-13eb3900-6a63-11e9-98d6-3fe51fa56286.PNG">

https://github.com/woojeee/django_bookreview2.git

**Comment by swcho9919** [comment]
![스크린샷(1)](https://user-images.githubusercontent.com/46709390/56873051-86134c00-6a6a-11e9-91e6-ce6e00f24285.png)
![스크린샷(2)](https://user-images.githubusercontent.com/46709390/56873052-86134c00-6a6a-11e9-99aa-2c7b6165de14.png)
https://github.com/swcho9919/django_bookreviewblog
조성우우

**Comment by SeeunChoi1** [comment]
![image](https://user-images.githubusercontent.com/37589355/56875964-0348bc00-6a7f-11e9-86ef-8b3c8e476348.png)
![image](https://user-images.githubusercontent.com/37589355/56875976-0e9be780-6a7f-11e9-9fce-65dc69451422.png)
![image](https://user-images.githubusercontent.com/37589355/56875981-165b8c00-6a7f-11e9-8a50-ed025c87265f.png)
![image](https://user-images.githubusercontent.com/37589355/56875988-27a49880-6a7f-11e9-8098-1d85da0ace87.png)
최세은
https://github.com/SeeunChoi1/Django_css

**Comment by wSuhye** [comment]
안수혜
https://github.com/wSuhye/CRUD-HW
![home](https://user-images.githubusercontent.com/48678364/56881747-5ed57280-6a9c-11e9-84cf-7777d5651c7d.JPG)
![detail](https://user-images.githubusercontent.com/48678364/56881752-60069f80-6a9c-11e9-9703-e059581209d4.JPG)
![new](https://user-images.githubusercontent.com/48678364/56881755-6137cc80-6a9c-11e9-93c5-9739f5dd2253.JPG)

**Comment by elksha** [comment]
김준태
https://github.com/elksha/Next/tree/master/crud_assignment

![이미지 004](https://user-images.githubusercontent.com/43684130/56889049-6e5eb680-6ab0-11e9-98f1-c22fc5668598.png)
![이미지 006](https://user-images.githubusercontent.com/43684130/56889051-6ef74d00-6ab0-11e9-8b2a-7ff556bba316.png)

**Comment by Gentleman37** [comment]
이경연입니다
https://github.com/mangod037/first_repo/tree/master/04.08

<img width="969" alt="스크린샷 2019-04-29 오후 5 06 49" src="https://user-images.githubusercontent.com/35323749/56883427-9d216080-6aa1-11e9-9494-bbcd3a254d49.png">

**Comment by 10kdkd** [comment]
김동제
https://github.com/10kdkd/first_repo/tree/master/0429hw
![1](https://user-images.githubusercontent.com/48678281/56884152-db1f8400-6aa3-11e9-9f8f-4ef495b3471e.PNG)
![2](https://user-images.githubusercontent.com/48678281/56884159-dce94780-6aa3-11e9-82b2-476beefb5024.PNG)
![3](https://user-images.githubusercontent.com/48678281/56884160-df4ba180-6aa3-11e9-8a8b-59f97eff0470.PNG)

**Comment by vhvha** [comment]
장주희
https://github.com/vhvha/aladdin
![aladdin](https://user-images.githubusercontent.com/46235386/56884507-f939b400-6aa4-11e9-8f53-fd1a9c0743da.PNG)

**Comment by gaetokk** [comment]
안태경

https://github.com/gaetokk/Django_crud/tree/master/crud

<img width="507" alt="글쓰는화면" src="https://user-images.githubusercontent.com/46814961/56885678-fee4c900-6aa7-11e9-9c22-91101c0c75c0.png">
<img width="513" alt="리뷰화면" src="https://user-images.githubusercontent.com/46814961/56885684-02785000-6aa8-11e9-83b3-5bbb2fd123fc.png">
<img width="510" alt="수정화면" src="https://user-images.githubusercontent.com/46814961/56885694-060bd700-6aa8-11e9-9a03-4cc991ab86bb.png">
<img width="505" alt="홈화면" src="https://user-images.githubusercontent.com/46814961/56885695-060bd700-6aa8-11e9-9d5d-72badb702b9d.png">

열심히 flex를 건드려봤지만 홈화면 저 책들이 가로정렬이 안돼네요....도륵

**Comment by jojoboy2212** [comment]
조형제
https://github.com/jojoboy2212/book_review
<img width="846" alt="스크린샷 2019-04-29 오후 5 50 20" src="https://user-images.githubusercontent.com/43463542/56885761-36537580-6aa8-11e9-8060-66930850f15d.png">
<img width="846" alt="스크린샷 2019-04-29 오후 5 33 20" src="https://user-images.githubusercontent.com/43463542/56885782-40757400-6aa8-11e9-93b4-72964f486d77.png">
<img width="843" alt="스크린샷 2019-04-29 오후 5 42 18" src="https://user-images.githubusercontent.com/43463542/56885793-48351880-6aa8-11e9-9806-c21be292fad8.png">

<img width="845" alt="스크린샷 2019-04-29 오후 5 39 29" src="https://user-images.githubusercontent.com/43463542/56885755-30f62b00-6aa8-11e9-99bf-c5f4d0f82832.png">

**Comment by juno1028** [comment]
김준오
https://github.com/juno1028/4_8
<img width="847" alt="Screen Shot 2019-04-29 at 5 50 47 PM" src="https://user-images.githubusercontent.com/45659499/56886098-22f4da00-6aa9-11e9-810d-883461805b57.png">
<img width="853" alt="Screen Shot 2019-04-29 at 6 02 10 PM" src="https://user-images.githubusercontent.com/45659499/56886108-2a1be800-6aa9-11e9-93ea-e48edf76034e.png">
<img width="850" alt="Screen Shot 2019-04-29 at 6 01 56 PM" src="https://user-images.githubusercontent.com/45659499/56886112-2d16d880-6aa9-11e9-9d0d-8464936092f8.png">

**Comment by NamJaeyong** [comment]
남재용

![image](https://user-images.githubusercontent.com/48678278/56886385-e37abd80-6aa9-11e9-9a83-16c46f6b837e.png)

https://github.com/NamJaeyong/bookreviewNam

**Comment by YUNALEEEE** [comment]
이유나
https://github.com/YUNALEEEE/book_review_exercise_2
![책리뷰_표지](https://user-images.githubusercontent.com/48678302/56886955-30ab5f00-6aab-11e9-87b1-cf753d164df4.JPG)
![책리뷰_수정](https://user-images.githubusercontent.com/48678302/56886956-31dc8c00-6aab-11e9-9b27-209bec7132ed.JPG)
![책리뷰_삭제](https://user-images.githubusercontent.com/48678302/56886958-33a64f80-6aab-11e9-86c4-230db67dfc63.JPG)

**Comment by parkjihwanjay** [comment]
박지환
<img width="944" alt="처음화면" src="https://user-images.githubusercontent.com/48053238/56886951-3012c880-6aab-11e9-81af-b6b3fb2c4d88.PNG">
<img width="941" alt="리뷰읽기" src="https://user-images.githubusercontent.com/48053238/56886975-3b65f400-6aab-11e9-9f72-4c1250099cbe.PNG">
<img width="944" alt="리뷰 쓰기" src="https://user-images.githubusercontent.com/48053238/56886977-3c972100-6aab-11e9-8290-767770bb09ae.PNG">
<img width="833" alt="수정" src="https://user-images.githubusercontent.com/48053238/56886970-37d26d00-6aab-11e9-866f-7fc484aa0dfa.PNG">


https://github.com/parkjihwanjay/django_assignment2

**Comment by miramira227** [comment]
김미라
https://github.com/miramira227/bookreviewdesign.git
![image](https://user-images.githubusercontent.com/48576190/56887856-a0bae480-6aad-11e9-8630-213a3aa586df.png)

**Comment by updownC** [comment]
최상하

과제 미리미리 하겠습니다 ㅠㅠㅠ
![과제](https://user-images.githubusercontent.com/48586856/56889121-90583900-6ab0-11e9-9bb1-c57e96b03292.jpg)

https://github.com/sanghaC/Bookreview

**Comment by SoniaComp** [comment]
박선영
<img width="688" alt="스크린샷 2019-04-29 오후 6 52 31" src="https://user-images.githubusercontent.com/45381486/56889458-56d3fd80-6ab1-11e9-97fb-a858eacbb038.png">
<img width="659" alt="스크린샷 2019-04-29 오후 6 58 26" src="https://user-images.githubusercontent.com/45381486/56889485-65bab000-6ab1-11e9-8c18-172e7305401e.png">

**Comment by chaeyeonie** [comment]
이채연
https://github.com/chaeyeonie/crud.git
<img width="921" alt="detail(with comment)" src="https://user-images.githubusercontent.com/48678352/57064338-f1764b80-6d00-11e9-9b71-bdaf75c8bb9e.PNG">
<img width="949" alt="home1" src="https://user-images.githubusercontent.com/48678352/57064339-f1764b80-6d00-11e9-81b0-db68279c8b95.PNG">
<img width="954" alt="new1" src="https://user-images.githubusercontent.com/48678352/57064340-f1764b80-6d00-11e9-8dfb-64548bda3297.PNG">
