### ISSUE TITLE
[5/2 Djanggo 1:N 과제]

### ISSUE THREAD

**Issue by sangw0804** [NEXT-LIKELION/Assignment#31]
- 마감 : 5/2 세션 전까지(7시)
- 내용 : 4/29 교안에 있습니다!
- detail페이지를 캡쳐해서 깃헙 주소, 본인 이름과 함께 댓글로 달아주세요!

**Comment by RyanKor** [comment]
김승태
![image](https://user-images.githubusercontent.com/40455392/56937844-cdb4d900-6b39-11e9-8ecd-aa0530af4e76.png)
https://github.com/RyanKor/Next-x-Likelion/tree/master/assignment6

**Comment by Gjunghoon** [comment]
권중훈
https://github.com/Gjunghoon/django_crud_practice
![K-001](https://user-images.githubusercontent.com/44766030/56940323-8d108c00-6b48-11e9-9dee-d4ac9c9b6865.png)

**Comment by elksha** [comment]
김준태
https://github.com/elksha/Next/tree/master/crud_assignment
![이미지 012](https://user-images.githubusercontent.com/43684130/56984968-4495b480-6bc2-11e9-96f3-80576a4e01c5.png)

**Comment by antlikelion** [comment]
이인우
https://github.com/antlikelion/django
<img width="960" alt="댓글추가" src="https://user-images.githubusercontent.com/48678284/57007212-f0bab800-6c21-11e9-9a07-444f8723dec5.png">

**Comment by Gentleman37** [comment]
이경연입니다
https://github.com/mangod037/first_repo/tree/master/04.08
<img width="1284" alt="스크린샷 2019-05-01 오후 3 51 46" src="https://user-images.githubusercontent.com/35323749/57008190-58283600-6c29-11e9-8d9c-da16305a6001.png">

**Comment by jihakwoo** [comment]
![image](https://user-images.githubusercontent.com/44742935/57017385-f46a3100-6c59-11e9-811a-5b3db6620829.png)
![image](https://user-images.githubusercontent.com/44742935/57017404-08ae2e00-6c5a-11e9-8178-2f8879d8bcf5.png)

https://github.com/woojeee/django_1-N_DB_comment.git

**Comment by parkjihwanjay** [comment]
박지환
https://github.com/parkjihwanjay/crude2_assignment
<img width="651" alt="댓글" src="https://user-images.githubusercontent.com/48053238/57017843-e9180500-6c5b-11e9-997b-88c9ed094c24.PNG">

**Comment by vhvha** [comment]
장주희
https://github.com/vhvha/aladdin
![댓글1](https://user-images.githubusercontent.com/46235386/57022445-22577180-6c6a-11e9-918e-4b7a1db2a460.PNG)

**Comment by SeeunChoi1** [comment]
![image](https://user-images.githubusercontent.com/37589355/57030413-89335580-6c7f-11e9-8587-a4230921bcdf.png)
최세은
https://github.com/SeeunChoi1/Django_bookrate

**Comment by YUNALEEEE** [comment]
이유나
https://github.com/YUNALEEEE/book_review_exercise_3
부트스트랩은 좀더 연구해보겠습니다...
![책리뷰_댓글작성](https://user-images.githubusercontent.com/48678302/57053166-409f8a80-6cc7-11e9-91fa-e3e1b86c69fc.JPG)
![책리뷰_댓글작성2](https://user-images.githubusercontent.com/48678302/57053167-42694e00-6cc7-11e9-9a9f-368529544773.JPG)

**Comment by 10kdkd** [comment]
김동제
https://github.com/10kdkd/first_repo/tree/master/0502hw
![과제](https://user-images.githubusercontent.com/48678281/57053650-6b3f1280-6cca-11e9-8969-fca62ab656a2.PNG)

**Comment by jojoboy2212** [comment]
조형제
https://github.com/jojoboy2212/book_review
<img width="966" alt="스크린샷 2019-05-02 오후 12 31 57" src="https://user-images.githubusercontent.com/43463542/57055538-0d64f780-6cd7-11e9-9a1f-e4e5064e3eae.png">

**Comment by kimjaehun96** [comment]
김재훈
https://github.com/kimjaehun96/llassignment
![image](https://user-images.githubusercontent.com/48678264/57055734-389c1680-6cd8-11e9-86df-a3b23e201c99.png)

**Comment by swcho9919** [comment]
![스크린샷(3)](https://user-images.githubusercontent.com/46709390/57056521-0a213a00-6cde-11e9-829d-bab1492e9b7f.png)
https://github.com/swcho9919/django_bookreviewblog
조성우

**Comment by gaetokk** [comment]
안태경
https://github.com/gaetokk/Django_crud/tree/master/crud
<img width="322" alt="댓글달기" src="https://user-images.githubusercontent.com/46814961/57057882-0e058a00-6ce7-11e9-9d86-de8dd2714531.png">

**Comment by hoiJuwon** [comment]
<img width="833" alt="스크린샷 2019-05-02 오후 3 19 05" src="https://user-images.githubusercontent.com/47557351/57059092-9a677b00-6cee-11e9-86ef-40e802e6a821.png">
https://github.com/hoiJuwon/CRUD_COMMENT

**Comment by wSuhye** [comment]
안수혜
https://github.com/wSuhye/Crud_comment
![숙제2](https://user-images.githubusercontent.com/48678364/57059280-8cfec080-6cef-11e9-9c54-a102896e6cc4.JPG)

**Comment by FriedPotato-hash** [comment]
김세연....
![image](https://user-images.githubusercontent.com/48678324/57060656-21b7ed00-6cf5-11e9-8355-7af46c87e1a3.png)
![image](https://user-images.githubusercontent.com/48678324/57060685-38f6da80-6cf5-11e9-89ee-989af2b7a6f7.png)
![image](https://user-images.githubusercontent.com/48678324/57060708-4c09aa80-6cf5-11e9-864e-373be03115c4.png)
https://github.com/080101/homework/tree/master/django_hw1/hwhwhw

**Comment by NamJaeyong** [comment]
https://github.com/NamJaeyong/bookreviewNam
![image](https://user-images.githubusercontent.com/48678278/57060921-15805f80-6cf6-11e9-872e-d6872add2ead.png)

**Comment by juno1028** [comment]
김준오
https://github.com/juno1028/4_8
<img width="1440" alt="Screen Shot 2019-05-02 at 5 27 06 PM" src="https://user-images.githubusercontent.com/45659499/57064089-4ebdcd00-6d00-11e9-946c-a5e4b31f256c.png">

**Comment by chaeyeonie** [comment]
이채연
https://github.com/chaeyeonie/crud.git
<img width="921" alt="detail(with comment)" src="https://user-images.githubusercontent.com/48678352/57065127-6ea2c000-6d03-11e9-8cbd-35248de33450.PNG">

**Comment by KimKangYeon** [comment]
![image](https://user-images.githubusercontent.com/48678290/57054407-70529080-6ccf-11e9-8fd8-04263267f409.png)
https://github.com/KimKangYeon/bookrating
김강연

**Comment by miramira227** [comment]
![image](https://user-images.githubusercontent.com/48576190/57066701-dc50eb00-6d07-11e9-8002-545072391dbf.png)

김미라
https://github.com/miramira227/comment.git

**Comment by SoniaComp** [comment]
박선영
<img width="635" alt="스크린샷 2019-05-10 오후 4 37 31" src="https://user-images.githubusercontent.com/45381486/57510765-88b35280-7342-11e9-99db-550340b326f9.png">

https://github.com/SoniaComp/my_blog_django
