### ISSUE TITLE
[5/9 Django 첨부파일 과제]

### ISSUE THREAD

**Issue by sangw0804** [NEXT-LIKELION/Assignment#32]
- 마감 : 5/9일 세션 전(~7시)까지 (5/6일은 대체공휴일로 세션이 없습니다!)
- 내용 : 5/2일 과제로 만든 페이지에 사진을 올릴 수 있는 기능을 추가하여 detail 페이지와 메인 페이지에서 사진이 보이도록 구현해주세요! 더 예쁘게 만들고 싶으신 분들은 CSS를 활용하여 꾸며도 좋습니다 :)
- 모르는 것이 있으면 파이빌로 오시거나 카톡으로 물어봐주세요.
- 소스 코드를 깃헙에 올리고 깃헙 주소와 detail, 메인, new 페이지 스크린샷을 댓글로 달아주세요!(본인의 이름도)

**Comment by Gjunghoon** [comment]
권중훈
https://github.com/Gjunghoon/django_crud_practice
![K-009](https://user-images.githubusercontent.com/44766030/57123391-999d1a80-6dbc-11e9-803f-33b978b035e1.png)
![K-010](https://user-images.githubusercontent.com/44766030/57123395-9bff7480-6dbc-11e9-86da-7abbe9bfe2de.png)
![K-011](https://user-images.githubusercontent.com/44766030/57123398-9efa6500-6dbc-11e9-955f-ce7ac94ccb07.png)

**Comment by jihakwoo** [comment]
![image](https://user-images.githubusercontent.com/44742935/57215230-3662f080-7027-11e9-8326-f98fc0215f60.png)
![image](https://user-images.githubusercontent.com/44742935/57215242-42e74900-7027-11e9-8c63-c5585e2758fe.png)

![image](https://user-images.githubusercontent.com/44742935/57215275-54305580-7027-11e9-9f56-496e6aede2c0.png)

https://github.com/woojeee/bookreview_comment_pic.git

**Comment by SeeunChoi1** [comment]
![image](https://user-images.githubusercontent.com/37589355/57240525-a1cdb200-7069-11e9-92e5-8ef434b983db.png)
![image](https://user-images.githubusercontent.com/37589355/57240620-e6f1e400-7069-11e9-8479-9d36bdeb6dd2.png)
![image](https://user-images.githubusercontent.com/37589355/57240550-b5791880-7069-11e9-82b6-866d9e172869.png)
![image](https://user-images.githubusercontent.com/37589355/57240567-be69ea00-7069-11e9-9a7c-631170b81def.png)
최세은
https://github.com/SeeunChoi1/Django_bookrate_comment

**Comment by RyanKor** [comment]
김승태
![image](https://user-images.githubusercontent.com/40455392/57267204-395af100-70ba-11e9-96bd-e5d103e4c72b.png)

![image](https://user-images.githubusercontent.com/40455392/57267224-41b32c00-70ba-11e9-9e0c-b74a9f80c001.png)

**Comment by wSuhye** [comment]
안수혜 
https://github.com/wSuhye/crud_img

![home](https://user-images.githubusercontent.com/48678364/57350587-9da0b200-7199-11e9-91c5-73479dee0bc1.JPG)
![detail](https://user-images.githubusercontent.com/48678364/57350589-9ed1df00-7199-11e9-9858-51d3e4583193.JPG)
![new](https://user-images.githubusercontent.com/48678364/57350593-a0030c00-7199-11e9-9c73-401793896681.JPG)

**Comment by YUNALEEEE** [comment]
이유나
https://github.com/YUNALEEEE/book_review_exercise_2
![책리뷰_첨부파일3](https://user-images.githubusercontent.com/48678302/57353977-2c66fc00-71a5-11e9-9d7e-e90e267d3569.JPG)
![책리뷰_첨부파일](https://user-images.githubusercontent.com/48678302/57353978-2c66fc00-71a5-11e9-9f95-c1d0fad56c69.JPG)
![책리뷰_첨부파일2](https://user-images.githubusercontent.com/48678302/57353980-2c66fc00-71a5-11e9-8d36-3947da44ff13.JPG)

**Comment by jojoboy2212** [comment]
조형제
https://github.com/jojoboy2212/book_review
<img width="1918" alt="스크린샷 2019-05-08 오후 7 51 35" src="https://user-images.githubusercontent.com/43463542/57370425-1b30e600-71cb-11e9-8409-d90e53bb2549.png">
<img width="1915" alt="스크린샷 2019-05-08 오후 7 51 42" src="https://user-images.githubusercontent.com/43463542/57370460-27b53e80-71cb-11e9-98b8-ba3e0e39a431.png">
<img width="1919" alt="스크린샷 2019-05-08 오후 7 52 02" src="https://user-images.githubusercontent.com/43463542/57370476-33086a00-71cb-11e9-94a3-03f4a2b2e88f.png">

**Comment by antlikelion** [comment]
이인우
https://github.com/antlikelion/django
<img width="960" alt="detail" src="https://user-images.githubusercontent.com/48678284/57373255-e6c12800-71d2-11e9-8629-ee9da0871e27.png">
<img width="960" alt="home" src="https://user-images.githubusercontent.com/48678284/57373075-63073b80-71d2-11e9-83d4-bbe0d96b7d7d.png">
<img width="960" alt="new" src="https://user-images.githubusercontent.com/48678284/57373079-65699580-71d2-11e9-994a-682cb84a33df.png">
<img width="960" alt="edit" src="https://user-images.githubusercontent.com/48678284/57373432-4ae3ec00-71d3-11e9-8b7e-cd30529b78cf.png">

**Comment by chaeyeonie** [comment]
이채연
<img width="773" alt="detail2" src="https://user-images.githubusercontent.com/48678352/57378744-64d7fb80-71e0-11e9-8b16-2d4606a7c7e7.PNG">
<img width="929" alt="home3" src="https://user-images.githubusercontent.com/48678352/57378751-6acddc80-71e0-11e9-9a87-524bd0bd68ff.PNG">
<img width="924" alt="new2" src="https://user-images.githubusercontent.com/48678352/57378956-ca2bec80-71e0-11e9-95e0-3af82e746efc.PNG">

https://github.com/NEXT-LIKELION/Assignment/issues/32

**Comment by Gentleman37** [comment]
이경연입니다

https://github.com/mangod037/first_repo/tree/master/BookReview
<img width="1440" alt="스크린샷 2019-05-09 오후 2 03 42" src="https://user-images.githubusercontent.com/35323749/57428586-07858e00-7264-11e9-8bad-7b82aecdbcb1.png">
<img width="1440" alt="스크린샷 2019-05-09 오후 2 03 58" src="https://user-images.githubusercontent.com/35323749/57428589-094f5180-7264-11e9-850a-a5cc06998e3f.png">
<img width="1440" alt="스크린샷 2019-05-09 오후 2 05 27" src="https://user-images.githubusercontent.com/35323749/57428592-0a807e80-7264-11e9-8cf6-448349fb0551.png">

**Comment by parkjihwanjay** [comment]
박지환
https://github.com/parkjihwanjay/crude2_assignment
<img width="949" alt="리뷰목록_수정" src="https://user-images.githubusercontent.com/48053238/57430585-25a2bc80-726b-11e9-89e6-925099593944.PNG">
<img width="613" alt="리뷰1" src="https://user-images.githubusercontent.com/48053238/57430591-29ceda00-726b-11e9-92f7-d305130a236c.PNG">
<img width="635" alt="리뷰2" src="https://user-images.githubusercontent.com/48053238/57430599-2dfaf780-726b-11e9-8ee5-73b4ec43a5cb.PNG">
<img width="656" alt="리뷰3" src="https://user-images.githubusercontent.com/48053238/57430607-30f5e800-726b-11e9-8a47-674beef1a3ed.PNG">
<img width="620" alt="리뷰 쓰기" src="https://user-images.githubusercontent.com/48053238/57430609-33f0d880-726b-11e9-83a2-2af69de937a0.PNG">

**Comment by swcho9919** [comment]
![스크린샷(8)](https://user-images.githubusercontent.com/46709390/57431065-8979b500-726c-11e9-8e1b-3dea843aa6f8.png)
![스크린샷(9)](https://user-images.githubusercontent.com/46709390/57431066-8a124b80-726c-11e9-992c-8bf689c86690.png)
이미지가..안떠요...가서 질문하겠슴당...ㅠ
조성우

**Comment by kimjaehun96** [comment]
김재훈
https://github.com/kimjaehun96/book_review

![blog_detail](https://user-images.githubusercontent.com/48678264/57432555-2dfdf600-7271-11e9-83de-a4ba613a0c87.png)
![blog_new](https://user-images.githubusercontent.com/48678264/57432557-2dfdf600-7271-11e9-9091-08866713bb0f.png)
![book_main](https://user-images.githubusercontent.com/48678264/57432558-2e968c80-7271-11e9-9ba7-ed69526cb4e0.png)

**Comment by gaetokk** [comment]
안태경
https://github.com/gaetokk/Django_crud/tree/master/crud
<img width="582" alt="home1" src="https://user-images.githubusercontent.com/46814961/57432825-d90eaf80-7271-11e9-8295-4095c002ff9a.png">
<img width="659" alt="home2" src="https://user-images.githubusercontent.com/46814961/57432862-f3e12400-7271-11e9-8856-3ff8c6b5362c.png">
<img width="609" alt="detail1" src="https://user-images.githubusercontent.com/46814961/57432831-df049080-7271-11e9-9fd2-24218c35f8a1.png">
<img width="624" alt="detail2" src="https://user-images.githubusercontent.com/46814961/57432833-df049080-7271-11e9-98b2-ac43a1987f52.png">
<img width="422" alt="edit1" src="https://user-images.githubusercontent.com/46814961/57432842-e6c43500-7271-11e9-9f5e-8a984977d9a8.png">

**Comment by juno1028** [comment]
김준오
https://github.com/juno1028/4_8
<img width="1253" alt="Screen Shot 2019-05-09 at 5 31 05 PM" src="https://user-images.githubusercontent.com/45659499/57439218-8092de80-7280-11e9-9fbd-86bb900969c8.png">
<img width="1181" alt="Screen Shot 2019-05-09 at 5 31 33 PM" src="https://user-images.githubusercontent.com/45659499/57439225-84befc00-7280-11e9-919c-f39abd881184.png">

**Comment by FriedPotato-hash** [comment]
김세연

![image](https://user-images.githubusercontent.com/48678324/57442670-690b2400-7287-11e9-9a8b-278f8c275553.png)
![image](https://user-images.githubusercontent.com/48678324/57442698-76c0a980-7287-11e9-99bf-711c88c8c5ea.png)

![image](https://user-images.githubusercontent.com/48678324/57442762-9c4db300-7287-11e9-9352-d602c0df0454.png)

**Comment by elksha** [comment]
김준태
https://github.com/elksha/Next/tree/master/crud_assignment
![이미지 007](https://user-images.githubusercontent.com/43684130/57444351-ee440800-728a-11e9-8f79-9da87ca6a48a.png)
![이미지 008](https://user-images.githubusercontent.com/43684130/57444353-ee440800-728a-11e9-9473-88842c2a0ab0.png)
![이미지 009](https://user-images.githubusercontent.com/43684130/57444354-eedc9e80-728a-11e9-9a92-a570ae8cb4af.png)

**Comment by updownC** [comment]
최상하

![홈](https://user-images.githubusercontent.com/48586856/57444598-77f3d580-728b-11e9-9f72-9dc9b5e8ca5c.jpg)
![홈2](https://user-images.githubusercontent.com/48586856/57444600-79250280-728b-11e9-9a97-29dce5d465a0.jpg)

**Comment by hoiJuwon** [comment]
<img width="831" alt="스크린샷 2019-05-09 오후 6 55 31" src="https://user-images.githubusercontent.com/47557351/57444908-2dbf2400-728c-11e9-9119-7f366704e323.png">
<img width="837" alt="스크린샷 2019-05-09 오후 6 55 43" src="https://user-images.githubusercontent.com/47557351/57444915-33b50500-728c-11e9-8ec6-6c2851f9f27f.png">
<img width="526" alt="스크린샷 2019-05-09 오후 6 55 59" src="https://user-images.githubusercontent.com/47557351/57444927-37e12280-728c-11e9-91d2-85389a1356aa.png">
https://github.com/hoiJuwon/CRUD_assignment

아무리해도 계속 이미지가 엑스박스 떠서 일단 올립니다..

**Comment by NamJaeyong** [comment]
남재용
https://github.com/NamJaeyong/bookreviewNam.git
![image](https://user-images.githubusercontent.com/48678278/57444540-572b8000-728b-11e9-89d4-8df6a3239cca.png)

**Comment by miramira227** [comment]
![image](https://user-images.githubusercontent.com/48576190/57445428-50057180-728d-11e9-8ef8-dde64aa5ac4a.png)
https://github.com/miramira227/uploadfile.git
김미라
엑박이 뜨는 문제를 해결 못했지만 늦게라도 제출합니닷....ㅠㅠ

**Comment by SoniaComp** [comment]
<img width="728" alt="스크린샷 2019-05-10 오후 6 48 16" src="https://user-images.githubusercontent.com/45381486/57518598-5a3e7300-7354-11e9-8b7c-75160426fc8e.png">
<img width="732" alt="스크린샷 2019-05-10 오후 6 48 35" src="https://user-images.githubusercontent.com/45381486/57518600-5b6fa000-7354-11e9-9170-e742d75c91d4.png">
박선영
https://github.com/SoniaComp/my_blog_django
