### ISSUE TITLE
[5/16 Authentication 과제]

### ISSUE THREAD

**Issue by qlqnf16** [NEXT-LIKELION/Assignment#33]
### 5/16 authentication 과제
* __마감__: 5월 16일 목요일 세션 전까지 (13일은 미니톤 다음날로 세션이 없습니다! 푹 쉬세요)
* __내용__: 지금까지 한 과제에 로그인/로그아웃/회원가입 및 5/9 세션에서 배운 기능을 추가해주세요
* 소스코드를 github에 업데이트 하고 화면과 github 링크를 댓글로 달아주시면 됩니다
---
* 추가1: 세션에서 배운 내용 외에 다양한 장고 내부 auth 기능을 사용해서 멋지게 만들어보세요
* 참고: https://docs.djangoproject.com/en/2.2/ref/contrib/auth/
* 추가2: 스페셜세션에서 인스타그램 만든 분들은 인스타그램에도 적용해보세요 ^_^
---

- [x] 권중훈
- [ ] 김강연
- [ ] 김동제
- [ ] 김미라
- [ ] 김세연
- [x] 김승태
- [ ] 김재훈
- [ ] 김준오
- [ ] 남재용
- [x] 박선영
- [ ] 박지환
- [ ] 김준태
- [x] 안수혜
- [ ] 안태경
- [x] 우지학
- [x] 이경연
- [x] 이유나
- [x] 이인우
- [ ] 이채연
- [x] 장주희
- [x] 조성우
- [ ] 조형제
- [ ] 최상하
- [ ] 최세은
- [x] 최주원

**Comment by RyanKor** [comment]
김승태
![image](https://user-images.githubusercontent.com/40455392/57503571-94474f00-732b-11e9-9a4d-02b595d3c6f8.png)
![image](https://user-images.githubusercontent.com/40455392/57503583-a0cba780-732b-11e9-8e97-fac7fac1e42a.png)
![image](https://user-images.githubusercontent.com/40455392/57503589-acb76980-732b-11e9-9385-e60d257dee1d.png)
![image](https://user-images.githubusercontent.com/40455392/57503595-b214b400-732b-11e9-963d-2d5d1a50851b.png)
도대체 홈 버튼에 CSS가 왜 안먹는거죵..ㅎㅎ

**Comment by SoniaComp** [comment]
<img width="735" alt="스크린샷 2019-05-10 오후 7 04 49" src="https://user-images.githubusercontent.com/45381486/57520751-6c6ee000-7359-11e9-9317-51c4e55eccd0.png">
<img width="730" alt="스크린샷 2019-05-10 오후 7 23 57" src="https://user-images.githubusercontent.com/45381486/57520753-6e38a380-7359-11e9-8c7f-28a677b2bef0.png">
<img width="729" alt="스크린샷 2019-05-10 오후 7 24 07" src="https://user-images.githubusercontent.com/45381486/57520756-6f69d080-7359-11e9-80f2-25c51df68d55.png">
박선영
https://github.com/SoniaComp/my_blog_django

**Comment by Gjunghoon** [comment]
권중훈
https://github.com/Gjunghoon/bokreview
![K-023](https://user-images.githubusercontent.com/44766030/57598546-9eb55300-758e-11e9-8c42-23519b192652.png)
![K-024](https://user-images.githubusercontent.com/44766030/57598547-9f4de980-758e-11e9-93e0-051948701d8b.png)
![K-025](https://user-images.githubusercontent.com/44766030/57598548-9f4de980-758e-11e9-80a4-23d1055e6289.png)

- 추가 : 인스타그램
https://github.com/Gjunghoon/instagram_auth
![K-026](https://user-images.githubusercontent.com/44766030/57674621-b3f7b380-765a-11e9-9929-76b7302c4af5.png)
![K-027](https://user-images.githubusercontent.com/44766030/57674620-b3f7b380-765a-11e9-9263-4c41f2dae356.png)
![K-028](https://user-images.githubusercontent.com/44766030/57674619-b3f7b380-765a-11e9-8036-5b985258e639.png)
![K-029](https://user-images.githubusercontent.com/44766030/57674618-b35f1d00-765a-11e9-9724-7cf0ae6a82a9.png)

**Comment by Gentleman37** [comment]
이경연입니다
https://github.com/mangod037/first_repo/tree/master/BookReview
<img width="1137" alt="스크린샷 2019-05-13 오후 6 36 22" src="https://user-images.githubusercontent.com/35323749/57611682-5a39af80-75ae-11e9-90ca-e5c3992920c9.png">
<img width="1137" alt="스크린샷 2019-05-13 오후 6 36 32" src="https://user-images.githubusercontent.com/35323749/57611684-5b6adc80-75ae-11e9-89c7-c54145a13b85.png">

**Comment by swcho9919** [comment]
https://github.com/swcho9919/django_book_blog_w_authentication
![스크린샷(11)](https://user-images.githubusercontent.com/46709390/57664870-bf37e880-7634-11e9-9bc9-37b95ebc64fb.png)
![스크린샷(12)](https://user-images.githubusercontent.com/46709390/57664871-bf37e880-7634-11e9-8631-ac1c8aa80aa1.png)
![스크린샷(13)](https://user-images.githubusercontent.com/46709390/57664872-bfd07f00-7634-11e9-908e-970428ee1e80.png)
![스크린샷(10)](https://user-images.githubusercontent.com/46709390/57664873-bfd07f00-7634-11e9-9f2b-5aab19e46df8.png)
조성우

**Comment by wSuhye** [comment]
안수혜
https://github.com/wSuhye/CRUD-HW
CSS가 안돼요ㅜㅜ코드에는 있는데 왜 적용이 안될까요?ㅜㅜㅜ파이빌 갈게요ㅜ
![s](https://user-images.githubusercontent.com/48678364/57759588-2c32a780-7735-11e9-8333-5a18c30eff54.JPG)
![캡처](https://user-images.githubusercontent.com/48678364/57759590-2ccb3e00-7735-11e9-92d6-42ecf3312a24.JPG)

**Comment by hoiJuwon** [comment]
<img width="1054" alt="스크린샷 2019-05-15 오후 6 51 50" src="https://user-images.githubusercontent.com/47557351/57766592-96057e00-7742-11e9-8fcc-6f61a993ee78.png">
<img width="490" alt="스크린샷 2019-05-15 오후 6 52 06" src="https://user-images.githubusercontent.com/47557351/57766600-9a319b80-7742-11e9-9e65-8c36fc1278c1.png">
<img width="694" alt="스크린샷 2019-05-15 오후 6 52 13" src="https://user-images.githubusercontent.com/47557351/57766605-9bfb5f00-7742-11e9-992a-a8ea6eb49b5b.png">

https://github.com/hoiJuwon/add_signin

**Comment by antlikelion** [comment]
이인우
https://github.com/antlikelion/django
<img width="960" alt="home" src="https://user-images.githubusercontent.com/48678284/57779094-6d8c7c80-7760-11e9-9dc7-89ff09807680.png">
<img width="960" alt="login" src="https://user-images.githubusercontent.com/48678284/57779101-70876d00-7760-11e9-85ad-fdbc68a4ba7c.png">
<img width="960" alt="detail" src="https://user-images.githubusercontent.com/48678284/57779105-71b89a00-7760-11e9-8df3-a0b1c3017054.png">

**Comment by vhvha** [comment]
장주희
https://github.com/vhvha/instagram
![인스타로그아웃](https://user-images.githubusercontent.com/46235386/57780872-14264c80-7764-11e9-91f0-bf5626771fec.PNG)
![인스타로그인](https://user-images.githubusercontent.com/46235386/57780874-14bee300-7764-11e9-9977-081d37dc9859.PNG)

**Comment by YUNALEEEE** [comment]
이유나 https://github.com/YUNALEEEE/book_review_exercise_2
![책리뷰_회원가입](https://user-images.githubusercontent.com/48678302/57823311-f68fcc00-77d1-11e9-91bf-142668ecfbf4.JPG)
![책리뷰_로그인](https://user-images.githubusercontent.com/48678302/57823312-f7286280-77d1-11e9-9fc7-a48504b8bb71.JPG)
![책리뷰_로그인홈](https://user-images.githubusercontent.com/48678302/57823313-f7286280-77d1-11e9-92d7-80771b1b6cfd.JPG)
![책리뷰_로그인댓글](https://user-images.githubusercontent.com/48678302/57823314-f7286280-77d1-11e9-8982-07fe42e89b49.JPG)

**Comment by jihakwoo** [comment]
![image](https://user-images.githubusercontent.com/44742935/57826316-ba626880-77dd-11e9-9ae0-f3b59e08e930.png)
![image](https://user-images.githubusercontent.com/44742935/57826331-c8b08480-77dd-11e9-9ebf-57bdc9941aaf.png)
![image](https://user-images.githubusercontent.com/44742935/57826340-d5cd7380-77dd-11e9-8517-9059f42b8b1b.png)

https://github.com/woojeee/django_review_register.git
우지학

**Comment by juno1028** [comment]
김준오
https://github.com/juno1028/django_practice
![Screen Shot 2019-05-16 at 1 19 27 PM](https://user-images.githubusercontent.com/45659499/57826499-89366800-77de-11e9-985d-a5c9c36e0e13.png)
<img width="1427" alt="Screen Shot 2019-05-16 at 1 28 12 PM" src="https://user-images.githubusercontent.com/45659499/57826508-92bfd000-77de-11e9-92ce-70976414c4ce.png">
<img width="1436" alt="Screen Shot 2019-05-16 at 1 27 42 PM" src="https://user-images.githubusercontent.com/45659499/57826516-981d1a80-77de-11e9-8e49-85cbf4d537e2.png">

**Comment by parkjihwanjay** [comment]
박지환
https://github.com/parkjihwanjay/crude2_assignment
<img width="951" alt="1" src="https://user-images.githubusercontent.com/48053238/57827326-e8e24280-77e1-11e9-9f2d-dd3e6c64fd5b.PNG">
<img width="942" alt="2" src="https://user-images.githubusercontent.com/48053238/57827335-eed82380-77e1-11e9-861c-38cf829bbeee.PNG">
<img width="945" alt="3" src="https://user-images.githubusercontent.com/48053238/57827339-f1d31400-77e1-11e9-9510-445d5956fef6.PNG">
<img width="376" alt="4" src="https://user-images.githubusercontent.com/48053238/57827345-fb5c7c00-77e1-11e9-915a-29153afba4d3.PNG">
<img width="361" alt="5" src="https://user-images.githubusercontent.com/48053238/57827348-fef00300-77e1-11e9-8596-5e4c910688bf.PNG">
<img width="948" alt="6" src="https://user-images.githubusercontent.com/48053238/57827350-00b9c680-77e2-11e9-8199-e381b18a4ce4.PNG">
<img width="411" alt="7" src="https://user-images.githubusercontent.com/48053238/57827352-02838a00-77e2-11e9-89a4-68415c5aa560.PNG">
<img width="305" alt="8" src="https://user-images.githubusercontent.com/48053238/57827356-044d4d80-77e2-11e9-9405-b94fe9ce6d84.PNG">
<img width="283" alt="13" src="https://user-images.githubusercontent.com/48053238/57827664-1f6c8d00-77e3-11e9-9805-4baaf6d0a269.PNG">
<img width="347" alt="9" src="https://user-images.githubusercontent.com/48053238/57827362-06afa780-77e2-11e9-9225-deca8924fdc4.PNG">
<img width="321" alt="10" src="https://user-images.githubusercontent.com/48053238/57827366-09120180-77e2-11e9-99e1-eb405a3e489a.PNG">
<img width="285" alt="11" src="https://user-images.githubusercontent.com/48053238/57827368-0adbc500-77e2-11e9-99f5-3f3911d0d466.PNG">
<img width="291" alt="12" src="https://user-images.githubusercontent.com/48053238/57827374-0f07e280-77e2-11e9-8167-cd5fec32588f.PNG">
<img width="460" alt="14" src="https://user-images.githubusercontent.com/48053238/57845782-a0d91500-780d-11e9-8283-89b3ddc1fc11.PNG">
<img width="312" alt="16" src="https://user-images.githubusercontent.com/48053238/57845915-f9a8ad80-780d-11e9-9f76-2199e6e8b7ce.PNG">

**Comment by SeeunChoi1** [comment]
최세은
https://github.com/SeeunChoi1/Django_bookrate_comment

![image](https://user-images.githubusercontent.com/37589355/57831012-dde1df00-77ee-11e9-97f6-577543fb69c1.png)
![image](https://user-images.githubusercontent.com/37589355/57831056-05d14280-77ef-11e9-8635-93b78c37f28b.png)


![image](https://user-images.githubusercontent.com/37589355/57829965-99087900-77eb-11e9-9d86-067760fd4ff4.png)
![image](https://user-images.githubusercontent.com/37589355/57830215-6317c480-77ec-11e9-8d9f-b38190335a37.png)
![image](https://user-images.githubusercontent.com/37589355/57830101-01575a80-77ec-11e9-9bc9-0e7ff9513417.png)

**Comment by NamJaeyong** [comment]
https://github.com/NamJaeyong/specialinstaNam.git
![image](https://user-images.githubusercontent.com/48678278/57835380-55b50700-77f9-11e9-8c7c-50c664ed9b78.png)
![image](https://user-images.githubusercontent.com/48678278/57835421-6ebdb800-77f9-11e9-8728-4e8afb388c7c.png)

**Comment by kimjaehun96** [comment]
김재훈
https://github.com/kimjaehun96/book_review
![블로그_main_with_signup](https://user-images.githubusercontent.com/48678264/57836702-45525b80-77fc-11e9-8c77-e7a6b2369a56.png)
![블로그_회원가입](https://user-images.githubusercontent.com/48678264/57836703-45525b80-77fc-11e9-9fc0-9b4e7cb0763a.png)
인스타도 해보겠습니다..!!

**Comment by KimKangYeon** [comment]
김강연
![image](https://user-images.githubusercontent.com/48678290/57837680-3cfb2000-77fe-11e9-9260-84989959553f.png)
![image](https://user-images.githubusercontent.com/48678290/57837689-41bfd400-77fe-11e9-920c-9a7208ca56eb.png)
https://github.com/KimKangYeon/bookrating

**Comment by elksha** [comment]
김준태
https://github.com/elksha/Next/tree/master/crud_assignment

![이미지 010](https://user-images.githubusercontent.com/43684130/57837951-c579c080-77fe-11e9-9054-d29ec7d967c0.png)
![이미지 011](https://user-images.githubusercontent.com/43684130/57837952-c579c080-77fe-11e9-9eb9-349b3e37fb94.png)

**Comment by jojoboy2212** [comment]
조형제
<img width="1541" alt="스크린샷 2019-05-16 오후 5 27 50" src="https://user-images.githubusercontent.com/43463542/57840505-b6494180-7803-11e9-84c6-0d4ad7dc5393.png">
<img width="1538" alt="스크린샷 2019-05-16 오후 5 46 21" src="https://user-images.githubusercontent.com/43463542/57840516-bea17c80-7803-11e9-9d48-de6272f99b5d.png">
<img width="1542" alt="스크린샷 2019-05-16 오후 5 27 24" src="https://user-images.githubusercontent.com/43463542/57840520-bfd2a980-7803-11e9-965e-ec2516fa84e3.png">
<img width="1540" alt="스크린샷 2019-05-16 오후 5 27 43" src="https://user-images.githubusercontent.com/43463542/57840528-c3fec700-7803-11e9-8495-523b5615e43d.png">
<img width="820" alt="스크린샷 2019-05-16 오후 5 49 41" src="https://user-images.githubusercontent.com/43463542/57840535-c5c88a80-7803-11e9-99c4-f292c9a18bd1.png">
<img width="1070" alt="스크린샷 2019-05-16 오후 5 50 20" src="https://user-images.githubusercontent.com/43463542/57840540-c7924e00-7803-11e9-976e-5377c1ebd26f.png">

**Comment by miramira227** [comment]
김미라
![image](https://user-images.githubusercontent.com/48576190/57842413-68ced380-7807-11e9-8281-cd07378781e3.png)

https://github.com/miramira227/authentification.git

**Comment by FriedPotato-hash** [comment]
김세연

![image](https://user-images.githubusercontent.com/48678324/57843378-24443780-7809-11e9-8d80-89c69396ddbb.png)
![image](https://user-images.githubusercontent.com/48678324/57843601-8866fb80-7809-11e9-80b8-862757ab8291.png)

**Comment by gaetokk** [comment]
안태경
https://github.com/gaetokk/Django_crud
<img width="937" alt="로그인창" src="https://user-images.githubusercontent.com/46814961/57844423-fcee6a00-780a-11e9-9d4a-fe12548c6552.png">
<img width="950" alt="회원가입" src="https://user-images.githubusercontent.com/46814961/57844433-ffe95a80-780a-11e9-9ab3-a6330ae5fbec.png">
<img width="703" alt="댓글" src="https://user-images.githubusercontent.com/46814961/57844444-07106880-780b-11e9-91cc-ee7fe5f28c51.png">
<img width="665" alt="로그아웃화면" src="https://user-images.githubusercontent.com/46814961/57844452-0aa3ef80-780b-11e9-82c1-7545cc80a053.png">

**Comment by updownC** [comment]
![ㅠㅠ](https://user-images.githubusercontent.com/48586856/57845479-10023980-780d-11e9-9a50-ac645322794e.jpg)

AWS 키 다시 받고 버킷 연결이 안돼서 이미지가 엑박으로 떠요 ㅠㅠㅠ
