### ISSUE TITLE
[미니 해커톤 마무리]

### ISSUE THREAD

**Issue by gyeol1212** [NEXT-LIKELION/Assignment#34]
1. 각 팀들의 대표는 각 팀의 서비스 화면 캡쳐 + 서비스 소개를 정리해서 올려주세요.

2. 서비스 소개와 함께 들어간 기술들을 bullet point로 써주세요. (ex.) Ajax, m:n 모델 추천, auth, login 등..

**Comment by Gjunghoon** [comment]
5조 : 사자누리(권중훈, 조성우, 안수혜, 이채연, 김동제)

사자누리는 ‘사자’와 세상을 뜻하는 순우리말 ‘누리’를 합친 말로 멋쟁이 사자처럼의 사자들을 위한 세상이라는 뜻입니다. 

멋쟁이 사자처럼은 국내 60여 개 대학, 당해 기수 1660명 학생들이 참여하는 프로그래밍 단체로 그 규모는 국내 최대에 이르지만, 단체 내에 학생들이 서로 소통할 수 있는 플랫폼은 없는 실정입니다. facebook에 각 학교별 멋쟁이 사자처럼 페이지가 개설되어 있지만, 홍보도 미흡하고, 각 학교별로 페이지가 운영되기 때문에 그 구조가 폐쇄적인 단점이 있습니다. 이에 저희 미니톤 팀 ‘lionbook’은 멋쟁이 사자처럼 회원들이 서로 소통할 수 있는 ‘멋쟁이 사자처럼 통합 SNS 서비스’ 사자누리를 만들기로 했습니다.

- 사자누리의 특징은 다음 세 가지입니다.

1. 펀딩 : 멋쟁이 사자처럼에서 만든 서비스를 대상으로 한 크라우드펀딩 게시판
2. 아이디어 : 아이디어 제안, 개인 프로젝트 진행 상황을 공유할 수 있는 게시판
3. 팀찾기 : 특정 회원 찾기, 연합 해커톤 제안 기능을 갖춘 게시판

사자누리 웹사이트는 다음과 같습니다.
![K-019](https://user-images.githubusercontent.com/44766030/57598692-2a2ee400-758f-11e9-9e7c-ca9a715d9af5.png)
![K-016](https://user-images.githubusercontent.com/44766030/57597706-6a8c6300-758b-11e9-9ee1-2b200ae4dbcb.png)
![K-018](https://user-images.githubusercontent.com/44766030/57594899-3c078b80-757d-11e9-89c1-eda2e2e61b6d.png)
![K-021](https://user-images.githubusercontent.com/44766030/57597765-a1fb0f80-758b-11e9-9924-e7d0d46ef658.png)
![K-012](https://user-images.githubusercontent.com/44766030/57595017-da93ec80-757d-11e9-94f5-9c1918abe3e5.png)
![K-013](https://user-images.githubusercontent.com/44766030/57595016-da93ec80-757d-11e9-96fe-d03f06fda091.png)

사자누리를 만들기 위해 이용한 기술은 다음과 같습니다.

- HTML, CSS를 이용해 Front-end를 구성했습니다.
: UI는 전세계 가장 많은 이용자수를 보유하고 있는 Facebook을 참조했습니다.

- Django를 이용해 전체적인 Back-end를 구성했습니다.
: 별도의 회원가입, 로그인 페이지 없이 index페이지에서 이를 한번에 이용할 수 있도록 request.POST로 전달받는 value에 따라 각각 로그인, 회원가입을 할 수 있게 조건문을 만들어 views.py 를 코딩했습니다. 또 장고 모델의 Foreignkey, FileField를 이용하여 각 user마다 프로필 사진을 가질 수 있게 구현했습니다. 이외에도 1:N 모델을 이용하여 댓글 기능을 구현하고, 모델과 폼을 이용하여 CRUD 기능을 만들었습니다. 자신이 쓴 글만 수정, 삭제가 가능하도록 하였습니다.
 회원가입, 로그인, 로그아웃을 구현하기 위해 auth와 user model을 참조했습니다. 파일 업로드는 AWS의 bucket을 이용해 구현했습니다.

- ajax, javascript를 이용해 좋아요 기능과 메시지창 기능을 구현했습니다.
: 좋아요 버튼을 눌렀을 때 해당 게시글의 좋아요 개수를 늘리거나 줄이고, 새로고침없이 화면에 바로 좋아요 개수 상태를 반영하기 위해 ajax를 활용했습니다. 좋아요를 누르면 해당 게시글의 다대다 모델의 like_user_set에 좋아요를 누른 유저 이름이 추가되고, 좋아요 개수는 이 유저수들을 더해 표현됩니다. 이를 위해 django의 다대다 관계, m:n 모델을 활용했습니다.
 이밖에 로그인 창에서 사용자가 id나 password를 잘못 눌렀을 때 이를 알려줄 수 있도록 javascript의 alert 기능을 이용하여 '아이디가 존재하지 않습니다.' '비밀번호가 일치하지 않습니다.' 창이 뜨도록 만들었습니다.

Github : https://github.com/Gjunghoon/lionbook

**Comment by RyanKor** [comment]
미니톤 3조 아나뿜다 팀 (김승태, 최주원, 김준태, 이유나, 안태경)
서비스 소개: 아껴쓰고, 나눠쓰고, 뿜빠이하고, 다시쓰는 자취생 플랫폼
![image](https://user-images.githubusercontent.com/40455392/57598917-07e99600-7590-11e9-8ff7-d99792fd8558.png)

![image](https://user-images.githubusercontent.com/40455392/57594957-78d38280-757d-11e9-83c8-52d3915274c2.png)
- Ajax, Haystack, Whoosh를 활용한 검색기능 구현
- login, signup구현을 위한 auth 주고 받기 구현
- Category 목록 구현(관리자 계정이 뿜빠이할 카테고리 추가 가능) : Class Inheritance 사용
- Menu 기능 구현(카테고리 내 세부 메뉴 기능 추가) 
- 1:N 기능을 사용한 댓글 기능 추가
- Ajax, JS 기반 뿜빠이할 장소를 선택할 수 있는 지역 기반 선택지 추가(Sub-Choices) 


제 깃허브에 오시면 Readme.md 읽어보실 수 있습니다.

GitHub : https://github.com/RyanKor/Mini

**Comment by jojoboy2212** [comment]
4조 라면파니(김강연, 박선영, 박지환, 장주희, 조형제)
서비스 소개: 라면을 색다른 조합으로 즐기는 사람들의 라면 레시피 커뮤니티

라면파니는 라면을 좋아하는 그리고 색다른 조합을 즐기는 사람들을 위한 커뮤니티 입니다. 각자만의 레시피를 만들고 원하는 조합으로 라면을 끓여보며 이 과정에서 찾아내는 본인만의 레시피에 점수를 표시하며 다른사람들의 평가를 들어 볼 수 있습니다. 항상 새로운것은 즐겁기에 또 어떤 조합으로 사람들이 리뷰를 올렸을까 하는 궁금증을 가지고 들어올 수 도 있으며, 말도안되는 정말 맛이라고는 하나도 없을 것같은 조합으로 먹어본 사람들의 후기를 보며 웃을 수도 있는 그런 사이트를 만들어 보고자 하였습니다. 

<img width="1604" alt="스크린샷 2019-05-14 오후 9 00 21" src="https://user-images.githubusercontent.com/43463542/57696360-9262f000-768b-11e9-9156-0c461185bdf5.png">
<img width="1614" alt="스크린샷 2019-05-14 오후 9 00 02" src="https://user-images.githubusercontent.com/43463542/57696370-968f0d80-768b-11e9-8815-3e43a1e1c9b1.png">
<img width="1590" alt="스크린샷 2019-05-14 오후 9 01 34" src="https://user-images.githubusercontent.com/43463542/57696373-98f16780-768b-11e9-9497-fda9e4251192.png">
<img width="1586" alt="스크린샷 2019-05-14 오후 9 01 41" src="https://user-images.githubusercontent.com/43463542/57696384-9b53c180-768b-11e9-9a31-6de6c805faaf.png">
<img width="1599" alt="스크린샷 2019-05-14 오후 9 00 41" src="https://user-images.githubusercontent.com/43463542/57696393-9ee74880-768b-11e9-99a1-9b6aefd9be72.png">
<img width="1583" alt="스크린샷 2019-05-14 오후 9 00 32" src="https://user-images.githubusercontent.com/43463542/57696397-a27acf80-768b-11e9-8992-988959dd3ea9.png">

프로젝트 소개

3,4월에 고려대 멋쟁이 사자처럼에서 배운 것들을 활용하여 만든 커뮤니티 웹 서비스입니다.
포스트, 댓글, 로그인, DB, 등의 다양한 내용을 기반으로 만들었습니다.
HTML, CSS로 Front-End를 구성하였으며 Django로 Back-End를 구성하였습니다. 

로그인시 기존에 배웠던 id 중복여부 확인기능과 추가적으로 비밀번호+비밀번호확인 에서 동일하지 않은 비밀번호가 입력되면 회원가입이 진행되지 않고 "똑같은 비밀번호를 입력해 주세요" 라는 문구가 뜨도록 설정하였습니다. 
각 아이디로 로그인시 본인의 아이디로 작성한 글만 삭제 가능하도록 설정하였습니다. 
글쓰기 화면에서 각 항목별로 선택가능한 내용들은 admin계정을 통해 각 항목별 DB를 추가 및 삭제할 수 있으며 새로운 라면이 출시되면 즉시 항목에 추가할 수 있습니다. 
NavBar의 dropdown 기능을 활용하기위해 bootstrap과 javascript를 활용하였습니다. 

어려웠던점. 
.gitignore 파일을 제 위치에 놓아도 제대로 ignore이 안되는 현상이 나타나곤 했다. 항상 aws키를 올리지 않도록
항상 조심하고 또 조심하자... 5명의 팀원 중 80프로인 4명의 키가 노출되는 타노스의 핑거스냅보다 더 강력한 효과를 볼 수 있으니 진짜진짜 조심하자...

Github : https://github.com/SoniaComp/mini_hackerton_ramen

**Comment by antlikelion** [comment]
2조 : INDI-THEATER
 
<img width="960" alt="INDI_THEATER" src="https://user-images.githubusercontent.com/48678284/57707704-0492ff00-76a3-11e9-90cc-bb49173e5fef.png">

‘영화계의 웹툰화’를 위한 플랫폼을 만들어, 사장되는 많은 저예산영화들과 대중의 접점을 넓히는 것이 INDI-THEATER의 서비스 취지입니다.

- 동영상 끌어오기

- Responsive menu 구현

- Home화면 애니메이션 활용

- 로그인 및 회원가입 기능 구현

- 1:N데이터모델을 이용한 댓글 기능 구현

- 게시물 별 조회수

- 홈 화면 노출시 조회수 순 정렬 구현

- 좋아요 기능

자세한 내용은 아래 repository의 README.md에서 확인하실 수 있습니다.

Github : https://github.com/antlikelion/mini_team2/tree/master

**Comment by Gentleman37** [comment]
<img width="1440" alt="스크린샷 2019-05-14 오후 11 39 41" src="https://user-images.githubusercontent.com/35323749/57707061-ed074680-76a1-11e9-8390-4bb9ba7db9ad.png">
<img width="1440" alt="스크린샷 2019-05-14 오후 11 39 31" src="https://user-images.githubusercontent.com/35323749/57707086-f4c6eb00-76a1-11e9-92bf-e0d13274ab37.png">
<img width="1440" alt="스크린샷 2019-05-14 오후 11 39 48" src="https://user-images.githubusercontent.com/35323749/57707091-f7294500-76a1-11e9-9c54-b966f5c0322d.png">
<img width="1440" alt="스크린샷 2019-05-14 오후 11 39 56" src="https://user-images.githubusercontent.com/35323749/57707095-f8f30880-76a1-11e9-80ac-53e61a0205b8.png">

Github: https://github.com/mangod037/MiniWinner
3조 MR.Fridge: "스마트 냉장고는 없지만, 스마트폰은 있잖아요"
스마트폰을 통해 스마트냉장고의 기능을 구현하고자 하였습니다.
1. 유통기한 알림: 각 식품별로 남아있는 유통기한을 알려주고, 유통기한이 지난 식품도 알려 줍니다.
2. 레시피 제공: 유통기한이 지나지 않은 식품을 선택하여 검색하기 버튼을 누르면, 네이버에서 각 재료로 만들 수 있는 레시피를 찾아줍니다.
3. 요리팁 공유: 유저들끼리의 커뮤니티를 통해 레시피를 공유할 수 있습니다.

- Login/회원가입 기능 구현
- 입력된 유통기한과 오늘날짜의 차이를 통해 식품의 남은 기한과 몇일이 지났는가를 보여줌
- Recipe 페이지에서 선택된 식품 재료로 검색을 하면 네이버로 검색한 페이지를 보여줌
   ex) 계란, 식빵 선택 -> 네이버에서 [계란 식빵 레시피] 검색화면이 나타남
- 커뮤니티 페이지를 Bootstrap을 통해 디자인함
