### ISSUE TITLE
[5/20 Django 크롤링 과제]

### ISSUE THREAD

**Issue by Jack2ee** [NEXT-LIKELION/Assignment#35]
5/20 크롤링 과제

- 마감: 5월 20일 월요일 세션 전까지
- 내용: 아래의 과제 1), 2)

**1) 네이버 뉴스 크롤러 장고 페이지 만들기:** home.html, result.html 두 개로 이루어진 프로젝트 파일을 만들고 home.html에서 input으로 검색하고자 하는 키워드를 입력하면 그에 대한 뉴스 기사 제목을 크롤링해오는 과제. result.html에 해당 키워드의 뉴스 기사 제목이 나열되고 기사 제목을 클릭할 시 기사의 페이지로 넘어가게 해주시면 됩니다. 부트스트랩을 통해 간단히 시각화해보는 것을 추천합니다.
**!참고자료**
(1) 네이버 뉴스 페이지 url: https://search.naver.com/search.naver?where=news&sm=tab_jum&query=
(2) 아래의 사진자료 1.home.html과 2.result.html

**2) 네이버 실시간 검색 순위 기록 만들기**: 아래의 그림의 네이버 실시간 검색 순위를 크롤링 해오는 과제입니다. 해당 데이터에 접근하는 방법 중 css_selector를 통한 접근(nth:child 개념)을 적용해보는 것을 추천드립니다. 해당 css_selector에 복사하는 방법은 개발자 도구에서 해당 html에서 마우스 오른쪽 버튼을 누르고 'Copy' > 'copy selector' 를 누르시면 복사가능합니다.
![image](https://user-images.githubusercontent.com/37537235/57900450-cf9dcc80-789b-11e9-85c6-9ece1fd974d5.png)
**!참고자료**
(1) 네이버 url: https://www.naver.com
(2) 아래의 사진자료 3.네이버 검색 순위 기록

<사진자료>
1.home.html
![image](https://user-images.githubusercontent.com/37537235/57900221-00c9cd00-789b-11e9-80a7-58f58239e7cb.png)

2.result.html(손흥민을 입력한 화면)
![image](https://user-images.githubusercontent.com/37537235/57900246-12ab7000-789b-11e9-94b8-b2b113115a3d.png)

3.네이버 순위 기록
![image](https://user-images.githubusercontent.com/37537235/57900152-b47e8d00-789a-11e9-8791-0f8d29b13262.png)

**Comment by elksha** [comment]
김준태
https://github.com/elksha/next

![이미지 004](https://user-images.githubusercontent.com/43684130/57903265-3c1ec880-78a8-11e9-8593-21cc7bbe002b.png)
![이미지 005](https://user-images.githubusercontent.com/43684130/57903266-3c1ec880-78a8-11e9-879d-ba95b3c2668e.png)
![이미지 006](https://user-images.githubusercontent.com/43684130/57903269-3d4ff580-78a8-11e9-8a9a-95856f5b7a95.png)

**Comment by SoniaComp** [comment]
박선영
https://github.com/SoniaComp/my_blog_django
<img width="774" alt="스크린샷 2019-05-17 오후 5 51 57" src="https://user-images.githubusercontent.com/45381486/57916005-f9bbb280-78cc-11e9-8c23-0836844cc602.png">
<img width="762" alt="스크린샷 2019-05-17 오후 5 52 14" src="https://user-images.githubusercontent.com/45381486/57916010-faecdf80-78cc-11e9-9785-10fcebdead0c.png">
<img width="451" alt="스크린샷 2019-05-18 오후 6 49 14" src="https://user-images.githubusercontent.com/45381486/57967972-bc742500-799f-11e9-8b64-ee88a7f9f5a2.png">
<img width="923" alt="스크린샷 2019-05-18 오후 7 03 29" src="https://user-images.githubusercontent.com/45381486/57967974-be3de880-799f-11e9-98a9-be03f4012bba.png">

**Comment by Gentleman37** [comment]
이경연입니다
https://github.com/mangod037/first_repo/tree/master/05.16.crawling
<img width="865" alt="스크린샷 2019-05-17 오후 6 48 05" src="https://user-images.githubusercontent.com/35323749/57922750-6ccc2580-78db-11e9-955d-6320d3a2247e.png">
<img width="865" alt="스크린샷 2019-05-17 오후 6 48 11" src="https://user-images.githubusercontent.com/35323749/57922753-6e95e900-78db-11e9-8697-bc2fdef8680d.png">
<img width="865" alt="스크린샷 2019-05-17 오후 7 36 06" src="https://user-images.githubusercontent.com/35323749/57922757-6fc71600-78db-11e9-81ea-1515def595f1.png">

**Comment by parkjihwanjay** [comment]
박지환
https://github.com/parkjihwanjay/naver_ranking
https://github.com/parkjihwanjay/search

<img width="491" alt="1" src="https://user-images.githubusercontent.com/48053238/57965579-19141780-7981-11e9-89ab-4e3e03d6c536.PNG">
<img width="208" alt="2" src="https://user-images.githubusercontent.com/48053238/57965580-1b767180-7981-11e9-9efc-a7389cbaa99a.PNG">
<img width="957" alt="3" src="https://user-images.githubusercontent.com/48053238/57965581-1dd8cb80-7981-11e9-94eb-2b30dd318945.PNG">
<img width="949" alt="4" src="https://user-images.githubusercontent.com/48053238/57965583-1fa28f00-7981-11e9-8e61-f406c9fa2dc7.PNG">

**Comment by Gjunghoon** [comment]
권중훈
https://github.com/Gjunghoon/crawling_assignment
- 네이버 뉴스 크롤러 장고 페이지
![K-005](https://user-images.githubusercontent.com/44766030/57966185-d86ccc00-7989-11e9-9f93-f7b15821cbca.png)
![K-004](https://user-images.githubusercontent.com/44766030/57966191-e28eca80-7989-11e9-990f-33aa50d5bdf9.png)

- 네이버 실시간 검색 순위
1. bs4 이용
![K-009](https://user-images.githubusercontent.com/44766030/57966204-123dd280-798a-11e9-9743-728e4138531b.png)
2. selenium 이용
![K-006](https://user-images.githubusercontent.com/44766030/57966210-21bd1b80-798a-11e9-95be-048bdbdd848d.png)

**Comment by vhvha** [comment]
장주희
1)  https://github.com/vhvha/crawling_django
2)  https://github.com/vhvha/realtime
![멋사_검색어 입력창](https://user-images.githubusercontent.com/46235386/57980198-e0e50580-7a62-11e9-8995-204e58844a06.JPG)
![멋사_뉴스모음](https://user-images.githubusercontent.com/46235386/57980200-e4788c80-7a62-11e9-8067-76450782a7da.JPG)


![멋사_실시간 검색어](https://user-images.githubusercontent.com/46235386/57980202-f2c6a880-7a62-11e9-9cbe-b60bb7d9f8f1.JPG)

**Comment by antlikelion** [comment]
이인우
https://github.com/antlikelion/crawl_news
https://github.com/antlikelion/crawl_rank
<img width="960" alt="검색화면" src="https://user-images.githubusercontent.com/48678284/57980500-6ec2ef80-7a67-11e9-9bc9-fc35c7d2b576.png">
<img width="960" alt="검색결과" src="https://user-images.githubusercontent.com/48678284/57980502-72ef0d00-7a67-11e9-9008-63c3c92e5af1.png">
<img width="960" alt="검색어순위" src="https://user-images.githubusercontent.com/48678284/57980505-771b2a80-7a67-11e9-87a0-0a4fce73dd95.png">

**Comment by RyanKor** [comment]
김승태
![image](https://user-images.githubusercontent.com/40455392/57984817-718b0800-7a9a-11e9-8581-8dac0daafc53.png)

![image](https://user-images.githubusercontent.com/40455392/57984791-19ec9c80-7a9a-11e9-9841-29e8c96ba76e.png)

Github: https://github.com/RyanKor/Next-x-Likelion 
djangocrawling, selenium 파일 참고

**Comment by wSuhye** [comment]
안수혜
https://github.com/wSuhye/search
![home](https://user-images.githubusercontent.com/48678364/57990814-1e8a7280-7ae5-11e9-9f1f-d60039a5a84d.JPG)
![result](https://user-images.githubusercontent.com/48678364/57990815-1f230900-7ae5-11e9-9014-2242d8daeac2.JPG)
![실시간 hw](https://user-images.githubusercontent.com/48678364/57990825-3d890480-7ae5-11e9-91eb-cf0a3e0e7c91.JPG)

**Comment by jihakwoo** [comment]
![image](https://user-images.githubusercontent.com/44742935/57990699-10882200-7ae4-11e9-827c-f154954bfc18.png)
![image](https://user-images.githubusercontent.com/44742935/57990709-27c70f80-7ae4-11e9-945d-a481523e74e3.png)


![image](https://user-images.githubusercontent.com/44742935/57990714-37465880-7ae4-11e9-8492-9c9d6beaa591.png)

마블리♥
https://github.com/woojeee/python_crawling_news_title.git
https://github.com/woojeee/python_crawling_realtimesearchword.git

**Comment by FriedPotato-hash** [comment]
김세연

![image](https://user-images.githubusercontent.com/48678324/57992795-06b8eb80-7af1-11e9-9741-47e5854e5cf3.png)
![image](https://user-images.githubusercontent.com/48678324/57992917-a4acb600-7af1-11e9-8bdb-de9e37bf6507.png)

![image](https://user-images.githubusercontent.com/48678324/57994107-9319dd00-7af6-11e9-9884-88e1dbc043eb.png)

**Comment by swcho9919** [comment]
![스크린샷(20)](https://user-images.githubusercontent.com/46709390/57994390-efc9c780-7af7-11e9-9648-8c9c2d828cee.png)
![스크린샷(21)](https://user-images.githubusercontent.com/46709390/57994391-efc9c780-7af7-11e9-87c9-b2e2c271f8aa.png)
![스크린샷(19)](https://user-images.githubusercontent.com/46709390/57994392-efc9c780-7af7-11e9-8f10-20141d51147e.png)
조성우

**Comment by SeeunChoi1** [comment]
![image](https://user-images.githubusercontent.com/37589355/58001679-26630a80-7b17-11e9-9003-65f3bc2888cd.png)
![image](https://user-images.githubusercontent.com/37589355/58001811-8bb6fb80-7b17-11e9-9c73-779f29002ebe.png)
![image](https://user-images.githubusercontent.com/37589355/58001828-95d8fa00-7b17-11e9-953c-85037058fa8c.png)
최세은
https://github.com/SeeunChoi1/crawling
https://github.com/SeeunChoi1/crawl_selenium

**Comment by jojoboy2212** [comment]
조형제
![스크린샷 2019-05-20 오후 4 01 00](https://user-images.githubusercontent.com/43463542/58002195-ab025880-7b18-11e9-8974-400bdcb6d121.png)
![스크린샷 2019-05-20 오후 4 01 08](https://user-images.githubusercontent.com/43463542/58002202-adfd4900-7b18-11e9-91de-807f28ae5b9e.png)
<img width="330" alt="스크린샷 2019-05-20 오후 4 01 50" src="https://user-images.githubusercontent.com/43463542/58002203-af2e7600-7b18-11e9-984a-a623026d3f60.png">
https://github.com/jojoboy2212/0519_crawl

**Comment by gaetokk** [comment]
안태경
https://github.com/gaetokk/0520-
![검색홈기말고사](https://user-images.githubusercontent.com/46814961/58005965-d8073900-7b21-11e9-915d-c95892f68d42.png)
![검색결과](https://user-images.githubusercontent.com/46814961/58005972-db022980-7b21-11e9-9c53-73580966615c.png)
![실검](https://user-images.githubusercontent.com/46814961/58005977-dd648380-7b21-11e9-9121-d9b780de2eec.png)

**Comment by hoiJuwon** [comment]
<img width="1670" alt="스크린샷 2019-05-20 오후 5 04 48" src="https://user-images.githubusercontent.com/47557351/58005926-c3c33c00-7b21-11e9-9023-84985546c173.png">
<img width="1657" alt="스크린샷 2019-05-20 오후 5 05 12" src="https://user-images.githubusercontent.com/47557351/58005935-c756c300-7b21-11e9-91e7-4b6bad8de309.png">
<img width="1638" alt="스크린샷 2019-05-20 오후 5 05 22" src="https://user-images.githubusercontent.com/47557351/58005939-c9b91d00-7b21-11e9-9cd6-f3a5e8028eda.png">

<img width="450" alt="스크린샷 2019-05-20 오후 5 20 20" src="https://user-images.githubusercontent.com/47557351/58006695-a2634f80-7b23-11e9-82a3-e5d4b55de710.png">


https://github.com/hoiJuwon/crawler_django

**Comment by YUNALEEEE** [comment]
이유나
https://github.com/YUNALEEEE/realtime
https://github.com/YUNALEEEE/crawling
![뉴스크롤링1](https://user-images.githubusercontent.com/48678302/58007690-ccb60c80-7b25-11e9-925b-9bcd3d072ceb.JPG)
![뉴스크롤링2](https://user-images.githubusercontent.com/48678302/58007691-ccb60c80-7b25-11e9-9c28-1208402df8e5.JPG)
![실시간검색어](https://user-images.githubusercontent.com/48678302/58007693-cd4ea300-7b25-11e9-8e7a-bd85895aa53f.JPG)

**Comment by KimKangYeon** [comment]
![image](https://user-images.githubusercontent.com/48678290/58007371-20742600-7b25-11e9-8d14-c547b6d4557b.png)
![image](https://user-images.githubusercontent.com/48678290/58007425-3550b980-7b25-11e9-923e-d8f183995b92.png)
![image](https://user-images.githubusercontent.com/48678290/58008077-9036e080-7b26-11e9-947e-14a13f0cc78d.png)

김강연
https://github.com/KimKangYeon/crawling_hw

**Comment by NamJaeyong** [comment]
남재용
![image](https://user-images.githubusercontent.com/48678278/58009419-5e734900-7b29-11e9-8a34-91b89f0a8ce0.png)

![image](https://user-images.githubusercontent.com/48678278/58009393-52878700-7b29-11e9-8f06-a91199cf6432.png)

https://github.com/NamJaeyong/crawlingNam

![image](https://user-images.githubusercontent.com/48678278/58009491-8cf12400-7b29-11e9-8be5-4cdb84f81664.png)

https://github.com/NamJaeyong/crawlingwithselenium.git

**Comment by kimjaehun96** [comment]
김재훈
https://github.com/kimjaehun96/crawling.git
![크롤링](https://user-images.githubusercontent.com/48678264/58011156-a6479f80-7b2c-11e9-89be-b0aacda9235c.png)

**Comment by chaeyeonie** [comment]
이채연
![image](https://user-images.githubusercontent.com/48678352/58012325-2f5fd600-7b2f-11e9-9596-0cf6fdc6b1f2.png)
![image](https://user-images.githubusercontent.com/48678352/58012352-3dadf200-7b2f-11e9-96cc-8846833bdbb0.png)
![image](https://user-images.githubusercontent.com/48678352/58012384-47cff080-7b2f-11e9-8310-8dcafa3a8a53.png)
https://github.com/chaeyeonie/518.git
https://github.com/chaeyeonie/518work.git

**Comment by updownC** [comment]
최상하

![크롤링](https://user-images.githubusercontent.com/48586856/58012424-60d8a180-7b2f-11e9-9caf-df64964038ff.jpg)
![크롤링2](https://user-images.githubusercontent.com/48586856/58012425-60d8a180-7b2f-11e9-8eb9-66a7e9ea51ee.jpg)

https://github.com/sanghaC/crawling.git

**Comment by juno1028** [comment]
김준오
https://github.com/juno1028/crawling
https://github.com/juno1028/django_practice
<img width="822" alt="Screen Shot 2019-05-20 at 6 55 23 PM" src="https://user-images.githubusercontent.com/45659499/58013223-2a038b00-7b31-11e9-9fac-644535811eea.png">
<img width="715" alt="Screen Shot 2019-05-20 at 6 55 31 PM" src="https://user-images.githubusercontent.com/45659499/58013233-2d971200-7b31-11e9-8b4a-f66ccf04bf0d.png">
<img width="723" alt="Screen Shot 2019-05-20 at 6 56 55 PM" src="https://user-images.githubusercontent.com/45659499/58013235-2ff96c00-7b31-11e9-96c5-6d05c86bf9bb.png">

**Comment by miramira227** [comment]
김미라
https://github.com/miramira227/crawling.git
![image](https://user-images.githubusercontent.com/48576190/58013308-54554880-7b31-11e9-9bd7-417ddc099492.png)
![image](https://user-images.githubusercontent.com/48576190/58013452-98e0e400-7b31-11e9-9da7-feabb32d69e8.png)
