### ISSUE TITLE
[5/23 API&JSON 과제]

### ISSUE THREAD

**Issue by Jack2ee** [NEXT-LIKELION/Assignment#36]
과제: API를 이용하여 서비스 만들어보기
기한: 5/23 세션 시작 전까지

세션 때 소개했던 공공데이터 포털(https://www.data.go.kr)을 이용하거나 google maps API 등 다른 API를 이용하여 원하는 서비스를 구현하는 것입니다. py 파일로만 해도 좋지만 django프로젝트에 추가하면 더욱 좋겠죠?
API key의 경우 gitignore를 철저히 하셔서 소스코드와 캡처본을 올려주시고 만약 그것에 자신이 없다 하시면 로컬만 캡처해서 올려주셔도 됩니다.

<크롤링과 API&JSON 소스코드>
1. crawling_bs4: https://github.com/Jack2ee/crawling_page
2. crawling_selenium: https://github.com/Jack2ee/crawling_with_selenium
3. news_api: https://github.com/Jack2ee/news_API
4. air_api: https://github.com/Jack2ee/API_air

**Comment by SoniaComp** [comment]
박선영(naver API 사용)
https://github.com/SoniaComp/BookSearch-CRUD-
<img width="390" alt="스크린샷 2019-05-22 오전 9 30 01" src="https://user-images.githubusercontent.com/45381486/58139111-4d831e80-7c74-11e9-8d30-4ed6019fbb92.png">
<img width="760" alt="v2_1_page2" src="https://user-images.githubusercontent.com/45381486/58133599-3128b700-7c5f-11e9-9bd9-d664e0302b76.png">
<img width="759" alt="v2_1_page1" src="https://user-images.githubusercontent.com/45381486/58133598-3128b700-7c5f-11e9-9add-c361a1573a4c.png">

**Comment by wSuhye** [comment]
안수혜
https://github.com/wSuhye/API
![캡처](https://user-images.githubusercontent.com/48678364/58152982-e2077400-7ca8-11e9-9e5d-7b4046390d87.JPG)

**Comment by jihakwoo** [comment]
![image](https://user-images.githubusercontent.com/44742935/58152951-ca2ff000-7ca8-11e9-9120-d4597a7186dd.png)
![image](https://user-images.githubusercontent.com/44742935/58153053-1aa74d80-7ca9-11e9-9421-df852fd3b3dc.png)
![image](https://user-images.githubusercontent.com/44742935/58153066-21ce5b80-7ca9-11e9-9d0a-7df3e4ab90d6.png)
![image](https://user-images.githubusercontent.com/44742935/58153087-2d218700-7ca9-11e9-991a-c5a5ebddf674.png)
![image](https://user-images.githubusercontent.com/44742935/58153098-3579c200-7ca9-11e9-9dec-1177e205c4a8.png)
![image](https://user-images.githubusercontent.com/44742935/58153112-3f9bc080-7ca9-11e9-91be-6f7c5513f9d0.png)
![image](https://user-images.githubusercontent.com/44742935/58153137-4d514600-7ca9-11e9-819b-7cdf22303a9b.png)
![image](https://user-images.githubusercontent.com/44742935/58153159-5cd08f00-7ca9-11e9-9822-cab01504ce80.png)
![image](https://user-images.githubusercontent.com/44742935/58153178-6528ca00-7ca9-11e9-966b-13cf35e9cb53.png)


https://github.com/woojeee/django_API_parking.git

apikey gitignore 완료
JS 배우면 사진 자동으로 슬라이드 되게 만들 수 있겠죠?

**Comment by swcho9919** [comment]
![스크린샷(26)](https://user-images.githubusercontent.com/46709390/58159315-36b1eb80-7cb7-11e9-8494-137cf654406b.png)
네이버 api 썼습니다,,,,secretkey때메 깃헙에 못올렸어도 좋습니다,,,,하지만 네이버 api,,,하나만 기억해주십시오,,,밤낮으로 디버깅했습니다,,,저의 진심이 전해지길 바랍니다,,,
조성우

**Comment by YUNALEEEE** [comment]
이유나
(장고프로젝트는 좀더 고민해보고 올릴게요!)
![전기자동차충전소py](https://user-images.githubusercontent.com/48678302/58191366-5b2eb780-7cf9-11e9-919c-eabc909a0364.JPG)

**Comment by parkjihwanjay** [comment]
박지환
https://github.com/parkjihwanjay/api_usage
<img width="847" alt="아이디 검색" src="https://user-images.githubusercontent.com/48053238/58192376-8dd9af80-7cfb-11e9-9954-c810b99c201f.PNG">
<img width="936" alt="결과1" src="https://user-images.githubusercontent.com/48053238/58192385-916d3680-7cfb-11e9-914d-875907c7f7c2.PNG">
<img width="949" alt="결과2" src="https://user-images.githubusercontent.com/48053238/58192391-94682700-7cfb-11e9-8243-58c423aa833e.PNG">
<img width="938" alt="결과2(전스코필드)" src="https://user-images.githubusercontent.com/48053238/58192401-98944480-7cfb-11e9-85f8-1c726e374e33.PNG">
<img width="947" alt="결과3(전스코필드)" src="https://user-images.githubusercontent.com/48053238/58192404-9a5e0800-7cfb-11e9-8a28-9d7adb026dec.PNG">
<img width="924" alt="결과1(진북동)" src="https://user-images.githubusercontent.com/48053238/58192408-9d58f880-7cfb-11e9-9582-2b91ac785c64.PNG">
<img width="946" alt="결과2(진북동)" src="https://user-images.githubusercontent.com/48053238/58192415-a053e900-7cfb-11e9-8b41-9e885c58d62a.PNG">

실버라고 놀리지 마세여..

**Comment by antlikelion** [comment]
이인우
<img width="960" alt="숙제" src="https://user-images.githubusercontent.com/48678284/58193528-296c1f80-7cfe-11e9-8904-c40f4dc0d375.png">

**Comment by hoiJuwon** [comment]
<img width="995" alt="스크린샷 2019-05-23 오전 2 08 18" src="https://user-images.githubusercontent.com/47557351/58194152-b1065e00-7cff-11e9-90f9-89f14326f5d5.png">
<img width="909" alt="스크린샷 2019-05-23 오전 2 10 55" src="https://user-images.githubusercontent.com/47557351/58194257-05a9d900-7d00-11e9-95ea-ae19946e53a2.png">

https://github.com/hoiJuwon/movieAPI.git

**Comment by SeeunChoi1** [comment]
![image](https://user-images.githubusercontent.com/37589355/58201823-026b1900-7d11-11e9-8d99-695ad6dd5487.png)
![image](https://user-images.githubusercontent.com/37589355/58243183-2703d700-7d8b-11e9-8a71-aadc7b177a34.png)

최세은
구글맵 api에 제대로 꽂히는 바람에.. home.html에 데이터 불러오기까지는 했는데 그 데이터를 지도로 넘기는걸 못해서 일단 아쉬운데로 좌표는 하드코딩햇어여...ㅎㅎ

**Comment by chaeyeonie** [comment]
이채연
![image](https://user-images.githubusercontent.com/48678352/58227568-53592c80-7d66-11e9-94db-2fcc3979b309.png)
https://github.com/chaeyeonie/-.git

**Comment by RyanKor** [comment]
김승태
![image](https://user-images.githubusercontent.com/40455392/58230446-4e4cab00-7d6f-11e9-8acd-388d2c25485c.png)
url : https://github.com/RyanKor/Next-x-Likelion/tree/master/api_assignment

**Comment by vhvha** [comment]
장주희
https://github.com/vhvha/using_api
![공공api사용](https://user-images.githubusercontent.com/46235386/58230719-14c86f80-7d70-11e9-8cf8-b0a29e45f874.JPG)
__제출에 의의를,,,

**Comment by juno1028** [comment]
김준오
https://github.com/juno1028/translation_api
<img width="1236" alt="Screen Shot 2019-05-23 at 3 40 03 PM" src="https://user-images.githubusercontent.com/45659499/58231535-3c203c00-7d72-11e9-95bd-77e3735e6fe1.png">
<img width="1251" alt="Screen Shot 2019-05-23 at 3 41 18 PM" src="https://user-images.githubusercontent.com/45659499/58231541-404c5980-7d72-11e9-8c8f-ece64ae96ef3.png">
maroon5 - she will be loved 가사 번역입니다ㅎ

**Comment by FriedPotato-hash** [comment]
![image](https://user-images.githubusercontent.com/48678324/58233142-3af10e00-7d76-11e9-82f1-82fb10fff8d9.png)
![image](https://user-images.githubusercontent.com/48678324/58233187-4d6b4780-7d76-11e9-831a-4b05a520bfe8.png)

김세연,,,

**Comment by kimjaehun96** [comment]
김재훈
django로 다시 올리겠습니다!
![image](https://user-images.githubusercontent.com/48678264/58235735-5b23cb80-7d7c-11e9-8f97-5a5e67b18299.png)

**Comment by KimKangYeon** [comment]
김강연
![image](https://user-images.githubusercontent.com/48678290/58238130-a5f41200-7d81-11e9-907d-aaa7f7258d8e.png)

**Comment by Gentleman37** [comment]
이경연입니다
https://github.com/mangod037/first_repo/tree/master/API
<img width="865" alt="스크린샷 2019-05-23 오후 5 57 23" src="https://user-images.githubusercontent.com/35323749/58239759-a510af80-7d84-11e9-870a-e8f8772b31f4.png">
<img width="865" alt="스크린샷 2019-05-23 오후 5 57 08" src="https://user-images.githubusercontent.com/35323749/58239834-cc677c80-7d84-11e9-87d6-8c24e3aad8c2.png">

**Comment by jojoboy2212** [comment]
조형제
<img width="297" alt="스크린샷 2019-05-23 오후 6 05 20" src="https://user-images.githubusercontent.com/43463542/58240160-64656600-7d85-11e9-810e-1a9089458287.png">
<img width="515" alt="스크린샷 2019-05-23 오후 6 05 05" src="https://user-images.githubusercontent.com/43463542/58240166-66c7c000-7d85-11e9-9d03-d8726e567992.png">
https://github.com/jojoboy2212/api_hw

**Comment by NamJaeyong** [comment]
남재용
![image](https://user-images.githubusercontent.com/48678278/58241183-71835480-7d87-11e9-9e75-b05df1982ffc.png)
![image](https://user-images.githubusercontent.com/48678278/58241219-7ba55300-7d87-11e9-9fcb-41602a9791cd.png)
https://github.com/NamJaeyong/airapiNam

**Comment by elksha** [comment]
김준태
https://github.com/elksha/Next/tree/master/with_api

![이미지 009](https://user-images.githubusercontent.com/43684130/58241633-5238f700-7d88-11e9-92ad-f94321541286.png)

**Comment by gaetokk** [comment]
안태경
https://github.com/gaetokk/0523-
무우려 검색기능까지 있다구욧
![0523과제수정](https://user-images.githubusercontent.com/46814961/58241757-8ca29400-7d88-11e9-8f32-7e463e0fadfb.png)

**Comment by updownC** [comment]
이미지 업로드를 해야하는데... AWS key 잘못 올렸다가 1272$ 청구당하고 문제 해결 중에 계정 access 자체가 막혀버려서 웹으로 구현을 못했읍니다.. 로컬 이미지로 작업해서 일단 콘솔화면만 띄울게요...ㅠ

사용한 API : google-vision-API (OCR)

![result](https://user-images.githubusercontent.com/48586856/58243138-12bfda00-7d8b-11e9-8185-b650d86193f9.jpg)

**Comment by miramira227** [comment]
김미라
https://github.com/miramira227/API.git
![image](https://user-images.githubusercontent.com/48576190/58243878-7d254a00-7d8c-11e9-80c8-8f51b9bbf521.png)

**Comment by Gjunghoon** [comment]
권중훈
kakao 얼굴인식 api 이용했습니다.
https://github.com/Gjunghoon/kakao_api_practice
![K-011](https://user-images.githubusercontent.com/44766030/58243931-94643780-7d8c-11e9-9b25-641ae9318c9a.png)

![K-010](https://user-images.githubusercontent.com/44766030/58243932-94643780-7d8c-11e9-86f0-f1c72c1a91dc.png)
