### ISSUE TITLE
[5/27 JS&DOM 기초 과제]

### ISSUE THREAD

**Issue by gyeol1212** [NEXT-LIKELION/Assignment#37]
- 마감 : 5월 27일 세션 전
- 세션 때 보여드린 글자와 배경화면이 무작위 색깔로 변경하는 페이지 하나를 올려주시면 됩니다.
- Github에 올리신 후, 캡쳐화면과 함께 Github 주소를 올려주세요.
- 과제에 대한 힌트는 교안 맨 마지막에 있습니다.
<img width="1792" alt="스크린샷 2019-05-24 오전 9 04 34" src="https://user-images.githubusercontent.com/37537201/58294108-43dbf100-7e03-11e9-83db-cfae246c93ad.png">

**Comment by SoniaComp** [comment]
박선영
https://github.com/SoniaComp/my_blog_django/tree/master/book/climbing
(뭔가 글자랑 배경 색깔 변화가 단조롭네요ㅠㅜ 랜덤함수 호출 간격이 얼마 안돼서 그런건가요?)
<img width="817" alt="스크린샷 2019-05-24 오전 9 48 58" src="https://user-images.githubusercontent.com/45381486/58295302-74bf2480-7e09-11e9-8ed6-a1218bad1099.png">

**Comment by swcho9919** [comment]
조성우
https://github.com/swcho9919/Javascript_first
![스크린샷(42)](https://user-images.githubusercontent.com/46709390/58297096-64ab4300-7e11-11e9-9e89-cd980e474025.png)

**Comment by parkjihwanjay** [comment]
박지환
https://github.com/parkjihwanjay/js_practice
rgb 사용했습니다.
<img width="960" alt="캡처" src="https://user-images.githubusercontent.com/48053238/58305390-e1024e00-7e32-11e9-9d37-d8d6deabf222.PNG">
<img width="959" alt="캡처1" src="https://user-images.githubusercontent.com/48053238/58305474-2e7ebb00-7e33-11e9-8962-e83a073c404a.PNG">

**Comment by hoiJuwon** [comment]
<img width="1129" alt="스크린샷 2019-05-24 오후 3 30 28" src="https://user-images.githubusercontent.com/47557351/58307268-232e8e00-7e39-11e9-8599-7735a018789a.png">

// start click 
<img width="1040" alt="스크린샷 2019-05-24 오후 3 30 40" src="https://user-images.githubusercontent.com/47557351/58307294-304b7d00-7e39-11e9-80bd-748146defa65.png">

// stop click
<img width="947" alt="스크린샷 2019-05-24 오후 3 30 46" src="https://user-images.githubusercontent.com/47557351/58307303-36415e00-7e39-11e9-80d2-4646ec425e5d.png">


https://github.com/hoijuwoncodes/JS_randomColor.git

**Comment by hoiJuwon** [comment]
<img width="1129" alt="스크린샷 2019-05-24 오후 3 30 28" src="https://user-images.githubusercontent.com/47557351/58307410-802a4400-7e39-11e9-9438-5ff94bdbc494.png">

// start click 
<img width="1004" alt="스크린샷 2019-05-24 오후 3 33 54" src="https://user-images.githubusercontent.com/47557351/58307416-86b8bb80-7e39-11e9-99a7-8f7463721655.png">

// stop click
<img width="770" alt="스크린샷 2019-05-24 오후 3 34 07" src="https://user-images.githubusercontent.com/47557351/58307427-90422380-7e39-11e9-8592-e9e4b8bd7564.png">


https://github.com/hoijuwoncodes/JS_randomColor.git

**Comment by miramira227** [comment]
김미라
![image](https://user-images.githubusercontent.com/48576190/58308349-5292ca00-7e3c-11e9-9b44-a08643d12b66.png)
https://github.com/miramira227/JS-DOM.git

**Comment by jihakwoo** [comment]
![GIF](https://user-images.githubusercontent.com/44742935/58308876-aa7e0080-7e3d-11e9-9b02-91dd76808bee.gif)

https://github.com/woojeee/JS_ass1_backgroundcolor.git

**Comment by Gentleman37** [comment]
이경연입니다
https://github.com/mangod037/first_repo/tree/master/javascript

<img width="386" alt="스크린샷 2019-05-24 오후 5 26 50" src="https://user-images.githubusercontent.com/35323749/58313862-83c5c700-7e49-11e9-8a63-51c212296ec9.png">
<img width="386" alt="스크린샷 2019-05-24 오후 5 26 52" src="https://user-images.githubusercontent.com/35323749/58313865-84f6f400-7e49-11e9-8041-f6b8616086cf.png">
<img width="386" alt="스크린샷 2019-05-24 오후 5 26 56" src="https://user-images.githubusercontent.com/35323749/58313866-86282100-7e49-11e9-98b6-6b2a8e2afbf6.png">

**Comment by elksha** [comment]
김준태
https://github.com/elksha/Next/tree/master/js

![GIF](https://user-images.githubusercontent.com/43684130/58358746-29654e80-7ebb-11e9-8344-c78ad77b0e68.gif)

**Comment by Gjunghoon** [comment]
권중훈
https://github.com/Gjunghoon/js_practice
16진수로 바꿔 풀었어요
![js](https://user-images.githubusercontent.com/44766030/58363787-ba9ceb00-7ee4-11e9-87db-a0967aa3f7b9.gif)

**Comment by RyanKor** [comment]
김승태
![aaa](https://user-images.githubusercontent.com/40455392/58369347-13e03b00-7f34-11e9-8030-c53df60f8c0f.gif)

Github : https://github.com/RyanKor/Next-x-Likelion/tree/master/jspractice

5월 26일 - 6월 8일 중국&홍콩에 가있어 세션 참석이 불가능할 듯 합니다.. 3회 불참하는데 과제는 꼬박꼬박 내겠슴돠  @.@;;

**Comment by antlikelion** [comment]
이인우
https://github.com/antlikelion/javascript
<img width="960" alt="오늘의 과제" src="https://user-images.githubusercontent.com/48678284/58376320-6f95dd00-7fa3-11e9-952b-f3c279d3a9f5.png">

**Comment by wSuhye** [comment]
안수혜
https://github.com/wSuhye/js
![colorchange_hw](https://user-images.githubusercontent.com/48678364/58380366-28cbd580-7feb-11e9-9128-bac90aa09deb.JPG)

**Comment by updownC** [comment]
최상하
https://github.com/sanghaC/likelion7/tree/master/js

과제하다 눈빠질뻔해서 조금 바꿔봤읍니다... 
![new3](https://user-images.githubusercontent.com/48586856/58385083-c3490a80-8025-11e9-9a4b-a88499102564.gif)

**Comment by SeeunChoi1** [comment]
![image](https://user-images.githubusercontent.com/37589355/58385167-1cfe0480-8027-11e9-82b1-dbff415ab9c3.png)
눈아파를 누르면 홈으로 갑니다.
https://github.com/SeeunChoi1/randomColor
최세은

**Comment by vhvha** [comment]
장주희
https://github.com/vhvha/firstJS
![gif1](https://user-images.githubusercontent.com/46235386/58388286-e4c2ea00-8057-11e9-9ece-d15487030343.gif)

**Comment by jojoboy2212** [comment]
https://github.com/jojoboy2212/JS_prac
조형제
<img width="952" alt="스크린샷 2019-05-27 오후 2 08 10" src="https://user-images.githubusercontent.com/43463542/58396865-68e19580-8089-11e9-88d0-87c96592099f.png">
이거 다들 사진 어케했어요...? 캡쳐말고 gif 모르는 1인...

**Comment by YUNALEEEE** [comment]
이유나
https://github.com/YUNALEEEE/randomColor

![randomcolor2](https://user-images.githubusercontent.com/48678302/58397862-c4158700-808d-11e9-952e-a85c94b9d5a5.gif)

**Comment by chaeyeonie** [comment]
이채연
https://github.com/chaeyeonie/jshw.git
![image](https://user-images.githubusercontent.com/48678352/58400020-e6f76980-8094-11e9-9062-bca9cec4022d.png)

**Comment by KimKangYeon** [comment]
김강연 https://github.com/KimKangYeon/js.homework
![image](https://user-images.githubusercontent.com/48678290/58400162-4b1a2d80-8095-11e9-953a-3c1f24243898.png)

**Comment by juno1028** [comment]
김준오
https://github.com/juno1028/190527
<img width="1137" alt="Screen Shot 2019-05-27 at 4 03 31 PM" src="https://user-images.githubusercontent.com/45659499/58401573-38a1f300-8099-11e9-9150-b29794acb8de.png">

**Comment by gaetokk** [comment]
안태경
https://github.com/gaetokk/javascript
![0527과제1](https://user-images.githubusercontent.com/46814961/58405451-67709700-80a2-11e9-8d40-3020335149e8.png)
![과제2](https://user-images.githubusercontent.com/46814961/58405455-6a6b8780-80a2-11e9-9e0e-3dea69edf677.png)

**Comment by kimjaehun96** [comment]
김재훈
https://github.com/kimjaehun96/java
![java_assignment](https://user-images.githubusercontent.com/48678264/58409511-2d57c300-80ab-11e9-854c-72b12c95e608.png)
![java_assignment2](https://user-images.githubusercontent.com/48678264/58409513-2d57c300-80ab-11e9-83fd-e0e9922a0053.png)

**Comment by FriedPotato-hash** [comment]
김세연

![image](https://user-images.githubusercontent.com/48678324/58411530-74e04e00-80af-11e9-9fb4-abf5eebac5be.png)

**Comment by NamJaeyong** [comment]
남재용
https://github.com/NamJaeyong/randomjavaNam.git
![image](https://user-images.githubusercontent.com/48678278/58411944-6d6d7480-80b0-11e9-9100-4339e8516811.png)
글씨 반짝반짝을 못하겠읍니다....
