### ISSUE TITLE
[5/30] DOM Control 과제

### ISSUE THREAD

**Issue by gyeol1212** [NEXT-LIKELION/Assignment#38]
과제는 총 3개입니다

### 과제 1 : 내용 입력하고, Enter 쳤을 때 보이기!
![image](https://user-images.githubusercontent.com/37537201/58422491-a9630280-80cd-11e9-87d0-14aa94fe750f.png)
- input에 텍스트를 입력하고 Enter를 치면, 글씨가 나타나게 해주세요!
- Enter를 입력하고나면, input을 초기화 시켜주세요!
 
### 과제 2 : 나는 얘만 클릭하고 싶은데...?
![image](https://user-images.githubusercontent.com/37537201/58422624-02329b00-80ce-11e9-95c6-d806cafda632.png)
- 교안과 함께 올라가있는 assignment2.html 파일을 다운 받아서 진행하세요
- 가운데, 가장 안쪽, 링크를 클릭하면 상위 요소의 console.log는 실행되지 않게 해주세요
- '구글로 가기'를 클릭하면, console.log만 실행되고, 링크가 작동하지 않게 해주세요 (직접적으로 a tag를 조작하지 않고!)

### 과제 3: 클릭한 놈이랑, 그 위에 놈
![image](https://user-images.githubusercontent.com/37537201/58422708-41f98280-80ce-11e9-81de-50a16ce81704.png)
- 교안과 함께 올라가있는 assignment3.html 파일을 다운 받아서 진행하세요
- 클릭한 div는 파란색으로!
- 클릭한 div의 상위 div는 빨간색으로!
- 각각의 div를 잡아서 하지 마시고, 클릭한 요소의 상위 요소를 조종하는 법을 찾아보세요!
- for 반복문을 사용하지 말고 풀어주세요!

다음 세션(5월 30일) 전까지, 과제를 모두 완료하셔서,  github에 올리신 후, 주소를 남겨주세요!

**Comment by Gjunghoon** [comment]
권중훈
https://github.com/Gjunghoon/dom_control_assignment

![h1](https://user-images.githubusercontent.com/44766030/58612231-d0e3e600-82ec-11e9-846a-af252a15b65d.gif)
![h2](https://user-images.githubusercontent.com/44766030/58612232-d0e3e600-82ec-11e9-8140-ec1c9d4b9e06.gif)
![h3](https://user-images.githubusercontent.com/44766030/58612230-d0e3e600-82ec-11e9-928d-fab198d4eeef.gif)

**Comment by swcho9919** [comment]
![스크린샷(46)](https://user-images.githubusercontent.com/46709390/58446668-7f94f480-813c-11e9-847c-f1617399ac84.png)
![스크린샷(47)](https://user-images.githubusercontent.com/46709390/58446670-7f94f480-813c-11e9-9b07-c205920a49f9.png)
![스크린샷(48)](https://user-images.githubusercontent.com/46709390/58446671-7f94f480-813c-11e9-91ca-d49cfca3a6aa.png)
https://github.com/swcho9919/Javascript_first
조성우

**Comment by antlikelion** [comment]
이인우
https://github.com/antlikelion/javapractice
<img width="960" alt="과제1" src="https://user-images.githubusercontent.com/48678284/58447490-7a857480-813f-11e9-9cb3-f809bd70f3fb.png">
<img width="960" alt="과제2" src="https://user-images.githubusercontent.com/48678284/58447495-7eb19200-813f-11e9-8ee0-6f57e295989f.png">
<img width="960" alt="과제3" src="https://user-images.githubusercontent.com/48678284/58447496-807b5580-813f-11e9-93dc-6f25a21de76d.png">
<img width="960" alt="과제4" src="https://user-images.githubusercontent.com/48678284/58447499-82451900-813f-11e9-85d0-7ce93af3f855.png">

**Comment by elksha** [comment]
김준태
https://github.com/elksha/Next/tree/master/js

![1](https://user-images.githubusercontent.com/43684130/58450000-f7b4e780-8147-11e9-8a41-6f5a9e37485d.gif)
![2](https://user-images.githubusercontent.com/43684130/58450001-f7b4e780-8147-11e9-8bd7-11a096cdb250.gif)
![3](https://user-images.githubusercontent.com/43684130/58450002-f84d7e00-8147-11e9-9371-cc8328cb58b3.gif)

**Comment by juno1028** [comment]
김준오
https://github.com/juno1028/190527/tree/master/assignment
<img width="910" alt="Screen Shot 2019-05-28 at 1 18 33 PM" src="https://user-images.githubusercontent.com/45659499/58450821-9bec5d80-814b-11e9-9a8a-99a136a1362d.png">
<img width="1417" alt="Screen Shot 2019-05-28 at 1 18 55 PM" src="https://user-images.githubusercontent.com/45659499/58450823-9f7fe480-814b-11e9-9505-4fe32588853c.png">
<img width="1428" alt="Screen Shot 2019-05-28 at 1 19 06 PM" src="https://user-images.githubusercontent.com/45659499/58450825-a1e23e80-814b-11e9-8763-fc4a7063d6b3.png">

**Comment by parkjihwanjay** [comment]
박지환
https://github.com/parkjihwanjay/js_assignment2
<img width="415" alt="1" src="https://user-images.githubusercontent.com/48053238/58452561-bd9d1300-8152-11e9-90fa-9f8a74b17861.PNG">
<img width="255" alt="2" src="https://user-images.githubusercontent.com/48053238/58452567-bf66d680-8152-11e9-9ee7-0a8b8f06d720.PNG">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/48053238/58452570-c1309a00-8152-11e9-9704-9b549f140b15.PNG">
<img width="949" alt="4" src="https://user-images.githubusercontent.com/48053238/58452573-c392f400-8152-11e9-83a4-29918256d6bb.PNG">

**Comment by jihakwoo** [comment]
과제1
![ass1](https://user-images.githubusercontent.com/44742935/58474652-b98ae880-8186-11e9-8158-dfb0003ed6ff.gif)


과제2
![ass2](https://user-images.githubusercontent.com/44742935/58474422-028e6d00-8186-11e9-83b2-0ece5b229c08.gif)


과제3
![ass3](https://user-images.githubusercontent.com/44742935/58474434-0a4e1180-8186-11e9-805c-6131be5706b9.gif)


https://github.com/woojeee/woojeee-JS_ass2_DOM.git

**Comment by Gentleman37** [comment]
이경연입니다
https://github.com/mangod037/first_repo/tree/master/javascript
<img width="392" alt="스크린샷 2019-05-28 오후 9 59 10" src="https://user-images.githubusercontent.com/35323749/58479896-25278280-8194-11e9-9acc-18d51cc1d1e5.png">
<img width="1121" alt="스크린샷 2019-05-28 오후 9 59 53" src="https://user-images.githubusercontent.com/35323749/58479898-26f14600-8194-11e9-9ceb-31ddb83b789a.png">
<img width="1077" alt="스크린샷 2019-05-28 오후 10 00 24" src="https://user-images.githubusercontent.com/35323749/58479902-28227300-8194-11e9-8412-734f89f03d14.png">

**Comment by YUNALEEEE** [comment]
이유나
https://github.com/YUNALEEEE/javascript_assignment
![글입력](https://user-images.githubusercontent.com/48678302/58537489-f2ca6380-822d-11e9-82c0-3efdc6247fd2.gif)
![구글로가기](https://user-images.githubusercontent.com/48678302/58537498-f52cbd80-822d-11e9-9716-62c87a843469.gif)
![color2](https://user-images.githubusercontent.com/48678302/58537513-f9f17180-822d-11e9-830e-fc2688478a48.gif)

**Comment by RyanKor** [comment]
김승태
과제 1. 검색어 입력하기
![search](https://user-images.githubusercontent.com/40455392/58568251-81f36d80-8266-11e9-80c4-0ccfd11448d7.gif)

과제 2. 구글 링크 연결된 박스에서 콘솔창 확인하기
![google](https://user-images.githubusercontent.com/40455392/58568256-8586f480-8266-11e9-984c-3bf0b740dd58.gif)

과제 3. 자식, 부모 div 색 변경시키기
![divs](https://user-images.githubusercontent.com/40455392/58568291-95063d80-8266-11e9-88cc-0306aec8da9d.gif)

중국에서 구글이 안되서 과제하느라 약간 애먹었습니다. 감사합니다 :)

Github : https://github.com/RyanKor/Next-x-Likelion/tree/master/domassignment

**Comment by wSuhye** [comment]
안수혜
https://github.com/wSuhye/js
![1](https://user-images.githubusercontent.com/48678364/58603555-307dc980-82cc-11e9-83e0-f2cf25e61351.JPG)
![1-1](https://user-images.githubusercontent.com/48678364/58603556-307dc980-82cc-11e9-9736-379b8742cdf5.JPG)
![2](https://user-images.githubusercontent.com/48678364/58603557-307dc980-82cc-11e9-8d08-3780c5b4ea6e.JPG)
![3](https://user-images.githubusercontent.com/48678364/58603558-31166000-82cc-11e9-84fc-16bbcea17171.JPG)

**Comment by vhvha** [comment]
장주희
https://github.com/vhvha/jszonjam
![과제1_삐에로](https://user-images.githubusercontent.com/46235386/58612837-ea862d00-82ee-11e9-8f55-f55d7df40372.gif)
![과제2](https://user-images.githubusercontent.com/46235386/58612842-ed811d80-82ee-11e9-94d9-d91d3e99eb44.JPG)
![과제3](https://user-images.githubusercontent.com/46235386/58612847-f07c0e00-82ee-11e9-9f3c-c5b04749b1c9.JPG)

**Comment by SeeunChoi1** [comment]
![image](https://user-images.githubusercontent.com/37589355/58616730-58375680-82f9-11e9-8fd1-fbc0684df6f6.png)
![image](https://user-images.githubusercontent.com/37589355/58617070-2377cf00-82fa-11e9-8378-dfaae569126e.png)
![image](https://user-images.githubusercontent.com/37589355/58617026-09d68780-82fa-11e9-8fcc-8366dfda2531.png)
최세은
https://github.com/SeeunChoi1/JavaScript_beginner

**Comment by NamJaeyong** [comment]
남재용
![과제1](https://user-images.githubusercontent.com/48678278/58618203-fb3d9f80-82fc-11e9-89fc-c7a05d10cc66.gif)
![과제 22](https://user-images.githubusercontent.com/48678278/58618205-fd076300-82fc-11e9-83bf-d4bb0e5a0eb6.gif)
![과제3](https://user-images.githubusercontent.com/48678278/58618211-009aea00-82fd-11e9-93ee-393a0fbb832e.gif)
https://github.com/NamJaeyong/javascriptNam.git

**Comment by KimKangYeon** [comment]
김강연 https://github.com/KimKangYeon/js.homework (세션때 만들었던 index.html파일에 과제 1을 했습니다ㅎㅎㅎㅎ)
![image](https://user-images.githubusercontent.com/48678290/58619465-f2020200-82ff-11e9-894c-844662c6f18a.png)
![image](https://user-images.githubusercontent.com/48678290/58619480-f6c6b600-82ff-11e9-96f6-6f99be1b28cb.png)
![image](https://user-images.githubusercontent.com/48678290/58619486-f9c1a680-82ff-11e9-94da-be81d7731952.png)
![image](https://user-images.githubusercontent.com/48678290/58619494-fdedc400-82ff-11e9-9183-6e5bc35296ce.png)

**Comment by updownC** [comment]
최상하 
https://github.com/sanghaC/likelion7/tree/master/js_assignment

![assignment1](https://user-images.githubusercontent.com/48586856/58619587-22e23700-8300-11e9-939a-a759cd1c90e3.jpg)

![assignment2](https://user-images.githubusercontent.com/48586856/58619588-22e23700-8300-11e9-9f3b-a773b71fc073.jpg)

![assignment3](https://user-images.githubusercontent.com/48586856/58619589-22e23700-8300-11e9-85f0-c9a676211d38.jpg)

**Comment by chaeyeonie** [comment]
이채연
https://github.com/chaeyeonie/jshw2.git

![image](https://user-images.githubusercontent.com/48678352/58620498-2d9dcb80-8302-11e9-9829-6376cc2142a7.png)

![image](https://user-images.githubusercontent.com/48678352/58620555-4c9c5d80-8302-11e9-9539-6b4405034046.png)


![image](https://user-images.githubusercontent.com/48678352/58620404-f7f8e280-8301-11e9-88b4-cf3a4f261911.png)

**Comment by kimjaehun96** [comment]
김재훈
https://github.com/kimjaehun96/java/tree/master/assignment_2
![java_ass1](https://user-images.githubusercontent.com/48678264/58621645-dbaa7500-8304-11e9-8a3c-652eff6caf0a.png)
![java_ass2](https://user-images.githubusercontent.com/48678264/58621646-dbaa7500-8304-11e9-9715-d421ef4f82cb.png)
![java_ass3](https://user-images.githubusercontent.com/48678264/58621648-dc430b80-8304-11e9-8607-ee6448925afb.png)

**Comment by miramira227** [comment]
김미라
https://github.com/miramira227/DOM.git 
과제 1
![image](https://user-images.githubusercontent.com/48576190/58624409-1ca58800-830b-11e9-8745-cc4ef057c50f.png)
과제 2
![image](https://user-images.githubusercontent.com/48576190/58624441-347d0c00-830b-11e9-84c4-9efa78d6c3e5.png)
과제 3
![image](https://user-images.githubusercontent.com/48576190/58624645-b4a37180-830b-11e9-9eae-30775a60e628.png)

**Comment by miramira227** [comment]
김미라 
https://github.com/miramira227/DOM.git 
과제1
![과제1](https://user-images.githubusercontent.com/48576190/58625390-5d9e9c00-830d-11e9-9f71-75ea0a055733.gif)

과제 2
![과제2](https://user-images.githubusercontent.com/48576190/58625155-cdf8ed80-830c-11e9-830c-da679738d7a9.gif)

과제3
![캡처전체3](https://user-images.githubusercontent.com/48576190/58625471-81fa7880-830d-11e9-97f6-53aa9bb30d6c.gif)

**Comment by gaetokk** [comment]
https://github.com/gaetokk/javascript
안태경
과제3에 클릭하면 이전 결과값 없애는 방법을 못 찾았습니다ㅠㅠㅠ죄송해요....
![문제1](https://user-images.githubusercontent.com/46814961/58625857-4d3af100-830e-11e9-857c-94787f3f75a3.png)
![문제2](https://user-images.githubusercontent.com/46814961/58625859-4d3af100-830e-11e9-9bd6-bf9b253fe61c.png)
![문제3](https://user-images.githubusercontent.com/46814961/58625860-4dd38780-830e-11e9-89e3-3faaf0a25075.png)

**Comment by hoiJuwon** [comment]
<img width="323" alt="스크린샷 2019-05-30 오후 7 35 26" src="https://user-images.githubusercontent.com/47557351/58627446-47dfa580-8312-11e9-8510-41d04e63d42b.png">
<img width="280" alt="스크린샷 2019-05-30 오후 7 35 30" src="https://user-images.githubusercontent.com/47557351/58627449-4910d280-8312-11e9-9aa5-a8d44f59df57.png">
<img width="1658" alt="스크린샷 2019-05-30 오후 7 36 02" src="https://user-images.githubusercontent.com/47557351/58627456-4ada9600-8312-11e9-97af-f72c1a339ee6.png">
<img width="1674" alt="스크린샷 2019-05-30 오후 7 35 07" src="https://user-images.githubusercontent.com/47557351/58627459-4c0bc300-8312-11e9-83e1-6d79b48efdea.png">


https://github.com/hoijuwoncodes/JS_click.git

**Comment by SoniaComp** [comment]
https://github.com/SoniaComp/NEXT
