### ISSUE TITLE
[6/3 jQuery 과제]

### ISSUE THREAD

**Issue by gyeol1212** [NEXT-LIKELION/Assignment#39]
- 기한은 6월 3일 월요일 종강식 전입니다

## 1. 저번 시간에 실습한 toDoList.html 파일을 올려주세요.
 (들어가야 할 항목들은 교안 참고)

## 3. jQuery의 AJAX를 이용하여, 버튼을 누르면 랜덤하게 강아지 사진이 나오는 html 파일을 만들어주세요.
(랜덤 강아지 사진 API : https://dog.ceo/api/breeds/image/random)

#### (4. Django + jQuery 실전에 적용하기!) (필수는 아닙니다.)
실습했던 toDoList를 실제 장고와 연결해서 적용해봅시다
(참고 사이트 : https://wayhome25.github.io/django/2017/06/25/django-ajax-like-button/)

**Comment by Gentleman37** [comment]
이경연입니다
https://github.com/mangod037/first_repo/tree/master/javascript/ajax
<img width="637" alt="스크린샷 2019-05-31 오전 11 05 59" src="https://user-images.githubusercontent.com/35323749/58676718-36d77880-8394-11e9-9dc7-0ec717577d36.png">

**Comment by Gjunghoon** [comment]
권중훈
https://github.com/Gjunghoon/ajax_assignment
1. 
![todolist](https://user-images.githubusercontent.com/44766030/58677244-317b2d80-8396-11e9-9f40-7d4fb8c95a3f.gif)

2. 새로 고침 없이 서버와 비동기적으로 통신하는 기술, jquery에 내장되어 있다
3.
![puppy](https://user-images.githubusercontent.com/44766030/58677125-bf0a4d80-8395-11e9-8757-c422e3108dcf.gif)

**Comment by antlikelion** [comment]
이인우
1. https://github.com/antlikelion/javapractice
2. 웹페이지의 일부 정보만 바뀌었을 때 페이지 전체를 새로 불러오는 것의 비효율을 피하기 위하여 부분적으로 정보를 갱신하는 기술이라고 합니다.
3. 
<img width="960" alt="깡생이" src="https://user-images.githubusercontent.com/48678284/58680926-f6ccc180-83a4-11e9-8f72-456a7d783f7d.png">

**Comment by parkjihwanjay** [comment]
박지환
https://github.com/parkjihwanjay/ajax_assignment
1.
<img width="498" alt="1" src="https://user-images.githubusercontent.com/48053238/58690402-67370b00-83c4-11e9-8cd3-650b5fc790a7.PNG">
<img width="434" alt="2" src="https://user-images.githubusercontent.com/48053238/58690407-69996500-83c4-11e9-9ffb-e6f0fbbe4f8f.PNG">
2.
Ajax : Asynchronous JavaScript And XML의 약어  비동기식 자바스크립트 XML

웹 화면을 갱신하지 않고 필요한 데이터를 서버로 보내고 가져오는 방법.

화면 갱신이 없기 때문에 사용자 입장에서 굉장히 편리하고 빠른 작업 가능

*동기식, 비동기식

-동기식 -> 업들 사이의 수행 시기를 맞추는 것. 사건이 동시에 일어나거나, 일정한 간격을 두고 일어나도록 시간의 간격을 조정하는 것  서버로 데이터를 요청하고 응답이 오는 시간동안 작업을 멈추고 기다려야 한다.(ex)로그인 화면)

-비동기식 -> 서버로 데이터를 요청하고 응답을 기다리는 동안 웹은 자신의 다른 업무를 진행하고 응답이 오면 그 후 작업을 진행. -> 화면 갱신 필요 x

3.
<img width="406" alt="멍" src="https://user-images.githubusercontent.com/48053238/58690455-82a21600-83c4-11e9-8c45-807a9f2cc8eb.PNG">
<img width="580" alt="댕댕이" src="https://user-images.githubusercontent.com/48053238/58690458-846bd980-83c4-11e9-84b8-455b08ef5ca9.PNG">

javascript와 jquery 둘다 사용해 봤습니다.
4.
https://github.com/parkjihwanjay/api_usage
<img width="960" alt="캡처" src="https://user-images.githubusercontent.com/48053238/58763541-e714cf00-8596-11e9-9798-5567fb966654.PNG">

댓글 작성, 삭제, 전체 삭제 다 새로고침 없이 가능합니다.

**Comment by SoniaComp** [comment]
1.https://github.com/SoniaComp/NEXT/blob/master/javascript/session_3.html
2.
Ajax는 웹페이지 전체 리소스를 리로드 하지 않고,
웹페이지에서 부분적으로, 비동기적으로, 서버와 데이터를 주고받는 작업을 도와주는 기술입니다.
3. https://github.com/SoniaComp/NEXT/tree/master/ajax_assignment
<img width="716" alt="스크린샷 2019-05-31 오후 7 01 53" src="https://user-images.githubusercontent.com/45381486/58749007-2f5ebf00-84bb-11e9-94cd-74cf3d7571f8.png">
4.https://github.com/SoniaComp/my_blog_django/tree/master/book/todo
화면녹화: [나의 동영상.mp4.zip](https://github.com/NEXT-LIKELION/Assignment/files/3245424/mp4.zip)
참고 1: https://simpleisbetterthancomplex.com/tutorial/2016/11/15/how-to-implement-a-crud-using-ajax-and-json.html#delete-book
참고 2: https://simpleisbetterthancomplex.com/tutorial/2016/08/29/how-to-work-with-ajax-request-with-django.html

**Comment by SeeunChoi1** [comment]
1. toDoList(아이콘 바껴욧)
![image](https://user-images.githubusercontent.com/37589355/58750841-eb2ae900-84d1-11e9-9a62-35d57e80fcce.png)
![image](https://user-images.githubusercontent.com/37589355/58750842-f120ca00-84d1-11e9-905f-fece3d32fa13.png)
2. 전체 페이지를 리로드하지 않고도 데이터를 불러올 수 있는 기법입니다. 서버처리를 기다리지 않아도 되기때문에 화면을 더 빠르게 전환할 수 있습니다.

3. 댕댕이 
![image](https://user-images.githubusercontent.com/37589355/58750815-b9b21d80-84d1-11e9-9e9d-9c63734038c9.png)
최세은
https://github.com/SeeunChoi1/JavaScript_beginner

**Comment by miramira227** [comment]
김미라
https://github.com/miramira227/JQUERY-AJAX.git

과제 1
![댕댕쓰](https://user-images.githubusercontent.com/48576190/58759326-1e698880-8563-11e9-8a58-e2b0f08ad675.gif)

과제 2
Ajax는 자바스크립트의 라이브러리 중 하나이며, 브라우저가 가지고 있는 XMLHttpRequest 객체를 이용해 전체 페이지를 새로고침하지 않고도 페이지의 일부만을 위한 데이터를 로드하는 기법이다. 이 방식의 장점은 불필요한 리소스 낭비가 발생하지 않으며 또한 웹페이지의 속도가 향상되고, 서버의 처리가 완료될 때까지 기다리지 않고 처리가 가능하다는 것이다. 전체적인 코딩의 양도 줄어들지만 연속으로 데이터를 요청하면 서버 부하가 증가할 수도 있다.

과제 3
![투두리스트](https://user-images.githubusercontent.com/48576190/58759344-6092ca00-8563-11e9-8fcd-1c5db6b7030d.gif)

운영진 분들 한 학기동안 고생많으셨습니다 감사합니다! 🥇

**Comment by RyanKor** [comment]
김승태

과제 1.
![image](https://user-images.githubusercontent.com/40455392/58764908-7920d580-859f-11e9-8cf5-3bf68eff9481.png)

과제 2.
AJAX의 경우 지난 미니톤에서 Subclass에 형성된 새로운 게시글이 메인 페이지에 새로 고침 없이 뜨게끔 사용하고자 시도했던 적이 있습니다. 아마 HTML 파일을 기존에는 변경사항을 보려면 새로고침을 했어야 되는데 사용자가 번거롭게 새로고침하지 않고 화면에 새로운 변경사항을 볼 수 있게끔 돕는 것이 AJAX가 아닌가 생각해봅니다.

과제 3.
![image](https://user-images.githubusercontent.com/40455392/58764913-935ab380-859f-11e9-8954-d9583a487058.png)

Git URL : https://github.com/RyanKor/Next-x-Likelion/tree/master/jqueryassignment

**Comment by jihakwoo** [comment]
마동석
![toDoList](https://user-images.githubusercontent.com/44742935/58769399-bc039d00-85e1-11e9-801d-9029043929e9.gif)

![dog](https://user-images.githubusercontent.com/44742935/58769406-c756c880-85e1-11e9-8cfb-e794ea80e47d.gif)

https://github.com/woojeee/JS_toDoList-AJAX_Dog.git

**Comment by jojoboy2212** [comment]
도대체 다들 영상으로 업로드 어케해여... 화면 
오 찾았어요!!!!!!
1. 
![Jun-03-2019 12-14-39](https://user-images.githubusercontent.com/43463542/58773758-41467c00-85f9-11e9-812b-8b97a1215b87.gif)

2. Ajax 는 네덜란드의 에레디비시에 속하는 축구 팀으로 이번 챔피언스리그에서 토트넘과 4강에서 만났다....
Ajax는 JavaScript와 xml을 이용하여 비동기 통신을 하는 기능으로 페이지를 새로고침 하지 않고 동적인 변화를 확인 할 수 있도록 한다. 이를 jQuery를 이용하면 보다 더 쉽게 사용할 수 있다고 한다.

3. 

![Jun-03-2019 12-43-30](https://user-images.githubusercontent.com/43463542/58774596-3db4f400-85fd-11e9-97d4-83ae4af9fcaf.gif)
https://github.com/jojoboy2212/jquery_ajax

**Comment by wSuhye** [comment]
안수혜
https://github.com/wSuhye/js
<과제1>
![todolist](https://user-images.githubusercontent.com/48678364/58775869-9c30a100-8602-11e9-890c-e29c4ff7f6ef.JPG)

<과제2>
Ajax는 화면을 새로고침하지 않고도 데이터를 주고받을 수 있게 하는 것이다. 이를 통해 웹페이지의 처리 속도를 빠르게 할 수 있다.

<과제3>
![dog](https://user-images.githubusercontent.com/48678364/58775877-a488dc00-8602-11e9-9895-f848591204cc.JPG)

**Comment by vhvha** [comment]
장주희
https://github.com/vhvha/jquerywork2
![올해의 강아지](https://user-images.githubusercontent.com/46235386/58778541-f7b45c00-860d-11e9-9ca3-82ef5634d104.JPG)

**Comment by gaetokk** [comment]
안태경
https://github.com/gaetokk/javascript
ajax는 해당 웹 페이지 전체가 아닌 페이지의 일부분만을 로딩해서 변경할 수 있는 방법이라고 생각합니다.
![ajax과제2](https://user-images.githubusercontent.com/46814961/58778580-1e729280-860e-11e9-991b-5d777753a836.png)
![todo](https://user-images.githubusercontent.com/46814961/58778582-1e729280-860e-11e9-9a37-4671cb727e61.png)

**Comment by YUNALEEEE** [comment]
이유나
과제 1. https://github.com/YUNALEEEE/javascript_assignment/blob/master/todoList2.html
![todoList](https://user-images.githubusercontent.com/48678302/58780834-1bc76b80-8615-11e9-9236-28863af0ad8f.gif)

과제 2. 비동기적인 웹애플리케이션 제작을 위한 웹 개발 기법. 필요한 데이터만을 웹서버에 요청해서 받은 후 클라이언트에서 데이터에 대한 처리를 할 수 있기 때문에 효율적이다.

과제3. 
https://github.com/YUNALEEEE/javascript_assignment/blob/master/puppy.html
https://github.com/YUNALEEEE/javascript_assignment/blob/master/puppy.css
![puppy](https://user-images.githubusercontent.com/48678302/58780847-23871000-8615-11e9-92ef-db5cc07090d4.gif)

**Comment by hoiJuwon** [comment]
1.
<img width="797" alt="스크린샷 2019-06-03 오후 4 10 36" src="https://user-images.githubusercontent.com/47557351/58782799-6a2b3900-861a-11e9-8c47-05c405d64832.png">

2.
Ajax 란 Asynchronous JavaScript and XML 의 약자로, 전체를 갱신하지 않고 웹페이지의 일부분만을 갱신 할 수 있는 기법의 하나입니다.

3.
<img width="617" alt="스크린샷 2019-06-03 오후 3 48 05" src="https://user-images.githubusercontent.com/47557351/58782898-a5c60300-861a-11e9-9801-42e0b86382cb.png">


https://github.com/hoijuwoncodes/final_assignment.git

**Comment by chaeyeonie** [comment]
이채연
ajax : 서버에서 필요한 데이터만을 챙겨오는 친구
![image](https://user-images.githubusercontent.com/48678352/58783239-677d1380-861b-11e9-960c-957527e9a3e0.png)

![image](https://user-images.githubusercontent.com/48678352/58783175-46b4be00-861b-11e9-8821-a18ff6b02446.png)

실패했어요ㅜㅜ
https://github.com/chaeyeonie/jshw2.git

**Comment by juno1028** [comment]
김준오
https://github.com/juno1028/190530
1.
<img width="820" alt="Screen Shot 2019-06-03 at 4 49 35 PM" src="https://user-images.githubusercontent.com/45659499/58785068-c6448c00-861f-11e9-88b5-89cb8eb04b27.png">
2. ajax는 데이터를 불러올 때 전체 페이지를 새로고침하지 않고, 필요한 부분만 갱신하여 데이터를 가져오는 효율적인 방식입니다.
3.
<img width="799" alt="Screen Shot 2019-06-03 at 4 47 49 PM" src="https://user-images.githubusercontent.com/45659499/58785158-effdb300-861f-11e9-8af3-9ce9da841663.png">

**Comment by swcho9919** [comment]
![스크린샷(56)](https://user-images.githubusercontent.com/46709390/58787651-36094580-8625-11e9-8882-871c8f8ec4e1.png)
![스크린샷(57)](https://user-images.githubusercontent.com/46709390/58787652-36094580-8625-11e9-85b3-ffe357a95e96.png)
![스크린샷(70)](https://user-images.githubusercontent.com/46709390/58787654-36a1dc00-8625-11e9-9287-c5b27fd39343.png)
조성우
AJAX 내용 summary
	Ajax는 Asynchronous JavaScript and Xml의 준말이다
	짧게 말해 ajax는 페이지를 새로고침하지 않은 상태에 새로운 데이터를 보여 줄 수 있게 하는 툴이다
	Ajax를 써서 만든 서비스는 gmail, google maps, 유툽, 페북 등이 있다
	jQuery와 ajax를 같이 쓰면 text, HTML, XML, JSON를 HTTP Get과 HTTP post 방식으로 가져올 수 있다

장고 써서 해봤는데...ㅎㅎ..;;;디버깅이 안돼요...
https://github.com/swcho9919/Javascript_first

**Comment by kimjaehun96** [comment]
김재훈
1.
![jquery_ass1](https://user-images.githubusercontent.com/48678264/58788562-1b37d080-8627-11e9-88a4-e00d7e979504.png)

2. AJAX는
페이지 리로딩 없이 웹 브라우저 안에서 페이지 전체가 아닌 일부분의 데이터를 처리할 수 있게 해주는 프로그래밍 언어다.

페이지 웹 서버가 처리할 데이터를 줄여주면서( 너무 많은 데이터를 요청하면 더 느려질 수도 있지만!) 화면 전환을 빠르게 할 수 있다. 

3. 
![ajax1](https://user-images.githubusercontent.com/48678264/58788858-c2b50300-8627-11e9-82f0-7fe3552cfbf9.png)
https://github.com/kimjaehun96/java/tree/master/thirdClass

**Comment by KimKangYeon** [comment]
김강연
1. https://github.com/KimKangYeon/js.homework
![image](https://user-images.githubusercontent.com/48678290/58791064-7e783180-862c-11e9-8b90-11a20b670877.png)

2. Ajax는 웹페이지 전체를 리로드 하지 않아도 될 때 웹페이지에서 부분적으로만 효율적으로 변경하기위한 것으로 서버와 데이터를 주고받는 작업을 도와주는 기술이라고 생각합니다.
3.
![image](https://user-images.githubusercontent.com/48678290/58791101-92239800-862c-11e9-8bba-98ea0bd0cca8.png)

**Comment by elksha** [comment]
김준태
https://github.com/elksha/Next/tree/master/js

1. 
![1](https://user-images.githubusercontent.com/43684130/58792969-26dbc500-8630-11e9-9354-462af6ac2813.gif)

2. 효율적인 동기화를 위해서 일부분만 동기화하는 것

3.
![GIF](https://user-images.githubusercontent.com/43684130/58793130-77ebb900-8630-11e9-8a83-b17cadf26cc4.gif)

**Comment by NamJaeyong** [comment]
남재용
https://github.com/NamJaeyong/halflastNam.git
![image](https://user-images.githubusercontent.com/48678278/58794351-f47f9700-8632-11e9-93c3-8ae943dc4986.png)
과제 2. 전체 페이지를 새로고침을 안해도 일부분만  새로 데이터를 가져오는 것
![image](https://user-images.githubusercontent.com/48678278/58794491-445e5e00-8633-11e9-9bb5-5a19e54b241f.png)

**Comment by updownC** [comment]
최상하

![new](https://user-images.githubusercontent.com/48586856/58795389-7f619100-8635-11e9-9910-085e3dd81d25.gif)

애견인입니다..
https://github.com/sanghaC/likelion7/tree/master/JQuery
