### ISSUE TITLE
2주차 과제(3) - Ruby(~ 6. Hashed and Symbols) & GitHub에 올리기

### ISSUE THREAD

**Issue by poongnewga** [NEXT-LIKELION/Assignment#4]
## Codecademy - Ruby(~ 6. Hashed and Symbols) & GitHub에 올리기

기한 :  **4/1 자정** 까지

아래의 **코멘트 양식** 지켜주세요 :)

---

1. 이름 : 채희재

2. GitHub 주소 : https://github.com/poongnewga/likelion_week1
> 수업시간(3/26)에 함께 올렸던 GitHub Repository 주소를 올려주세요. NEXT-LIKELION이 아닌 ***본인의 Repository*** 로 올려주세요!

3. 캡쳐 화면 : 
<img width="500" alt="2018-03-27 10 41 30" src="https://user-images.githubusercontent.com/15710904/37941908-8620cfc2-31ab-11e8-9003-d5740ad476b9.png">

---

- [x] 김민형
- [x] 김보성
- [x] 김지현
- [x] 박승준
- [x] 방혜주
- [x] 배영현
- [x] 성인규
- [x] 손지연
- [x] 신예찬
- [x] 신한결
- [x] 안성수
- [x] 엄가람
- [x] 오상우
- [x] 원혜진
- [x] 유선아
- [x] 유정아
- [x] 유현재
- [x] 이수영
- [x] 이윤비
- [x] 이재승
- [x] 이정민
- [x] 이지원
- [x] 이지현
- [x] 장민규
- [x] 장영재
- [x] 전재현
- [x] 전준표
- [x] 주기현
- [x] 최희윤
- [x] 한승희
- [x] 허예림
- [x] 허재혁

---

- 31 / 32 명 완료

**Comment by YeChan1030** [comment]
1. 이름 : 신예찬
2. Github 주소 : https://github.com/YeChan1030/likelion_week1

3.
![default](https://user-images.githubusercontent.com/37537205/38169550-eccf14e0-35a7-11e8-94b6-b4837900a760.PNG)

**Comment by Cecilia-L** [comment]
1. 이름: 이윤비
2. Github 주소: https://github.com/Cecilia-L/likelion_week1
3. 
![image](https://user-images.githubusercontent.com/37537232/38173699-e9f6e4fe-35fd-11e8-8d25-cc9dcd4eb4e1.png)

**Comment by ashufflepuff** [comment]
1. 이름 : 유정아
2. Github 주소 : https://github.com/ashufflepuff/likelion_week1
3. 
![ruby](https://user-images.githubusercontent.com/37537211/38173160-0c65ae58-35f4-11e8-861a-956aada2db22.PNG)

**Comment by norrard148** [comment]
1. 이름 : 장영재
2. Github : 주소 https://github.com/norrard148/likelion_week1
3. Ubuntu
![default](https://user-images.githubusercontent.com/37537262/38127692-44e5b9c6-3432-11e8-8c3a-5bcdcb8d6f66.PNG)

**Comment by Yerim2695** [comment]
1. 이름 : 허예림
2. Github 주소 : https://github.com/yerim2695/likelion_week1
3. 
![default](https://user-images.githubusercontent.com/37537200/38141206-0899898a-3472-11e8-8ec0-eeaf0cc449b0.PNG)

**Comment by PoSungKim** [comment]
1. 이름 : 김보성
2. Github 주소 : https://github.com/PoSungKim/likelion_week1
3. 
v
![_ruby1_](https://user-images.githubusercontent.com/37537227/38148393-54baebf0-3491-11e8-9b63-7303a9bd5ead.PNG)

**Comment by poongnewga** [comment]
@norrard148 @Yerim2695 @PoSungKim 항상 선두를 달리는 세 분 너무 칭찬해~

**Comment by mhbest** [comment]
1. 김민형
2. Github 주소: https://github.com/mhbest/likelion_week1
3. 
![image](https://user-images.githubusercontent.com/37537238/38164429-8ec22a80-353f-11e8-8c77-9ff6b73300a9.png)
혹시 의심하실까봐 그런데 CSS를 다 하고, 다시 코드보려고 진행률 RESET한 것입니다 ㅎㅎ

**Comment by poongnewga** [comment]
@mhbest ㅋㅋㅋㅋ 고생했어요~

**Comment by seona-yu** [comment]
1. 이름 : 유선아
2. GitHub 주소 : https://github.com/seona-yu/likelion_week1
3. 
<img width="959" alt="4 1" src="https://user-images.githubusercontent.com/37537217/38173659-26238b18-35fd-11e8-9d6d-167ac1a7ef37.png">

**Comment by soonjune** [comment]
1. 이름 : 박승준
2. GitHub 주소: https://github.com/jamie7060/likelion_week1
3. 캡쳐화면:
<img width="1258" alt="2018-04-01 2 36 03" src="https://user-images.githubusercontent.com/37537242/38170221-60d68f14-35ba-11e8-94c6-15d34ea820ad.png">

**Comment by gyeol1212** [comment]
1. 이름 : 신한결
2. GitHub 주소 : https://github.com/gyeol1212/likelion_week1
3. 캡쳐화면
![2018-04-01 2 49 04](https://user-images.githubusercontent.com/37537201/38170273-dbd869de-35bb-11e8-852a-f7a0a2285e23.png)

**Comment by jason2133** [comment]
1. 이름 : 이재승
2. GitHub 주소 : https://github.com/jason2133/likelion_week1
3. 캡쳐화면
![default](https://user-images.githubusercontent.com/37537208/38170435-798ff878-35c0-11e8-8ac1-a52f5959a786.jpg)

**Comment by sangw0804** [comment]
1. 이름 : 오상우
2. gitHub 주소 : https://github.com/sangw0804/likelion_week1
3. 캡쳐화면
![image](https://user-images.githubusercontent.com/37537207/38170881-dceba10c-35c9-11e8-988a-428c325fa30e.png)

**Comment by dkor3** [comment]
1. 이름: 안성수 
2. gitHub 주소:https://github.com/dkor3/Likelion_week1
3. 캡쳐화면 
![3 29](https://user-images.githubusercontent.com/37537204/38171045-6e45160e-35cc-11e8-98d9-3303f801e863.png)

**Comment by poongnewga** [comment]
@jamie7060 @gyeol1212 @jason2133 @sangw0804  @dkor3 저는 여러분을 믿습니다 ^^

**Comment by X3PY** [comment]
1. 전준표
2. gitHub 주소 : https://github.com/X3PY/likelion_week1/
3.캡쳐화면

![capture](https://user-images.githubusercontent.com/37537209/38171428-93cae34c-35d4-11e8-86a8-f5b5e7e2e178.PNG)

**Comment by Jack2ee** [comment]
1. 이름: 허재혁
2. github 주소: https://github.com/Jack2ee/likelion_week1
3. 캡처화면
![ruby](https://user-images.githubusercontent.com/37537235/38171726-641e3080-35da-11e8-9516-9c1cbb464d26.PNG)

**Comment by Hyezzi** [comment]
1. 이름 : 원혜진
2. github 주소 : https://github.com/Hyezzi/likelion_week1
3. 캡쳐화면
![image](https://user-images.githubusercontent.com/37537222/38171971-aa0bbd84-35de-11e8-812e-c5b65de54d51.png)

**Comment by swimmie0** [comment]
1. 이름: 이수영
2. github 주소: https://github.com/lsy044/likelion_week1
3. 루비:
![image](https://user-images.githubusercontent.com/37537202/38172456-cfdf85aa-35e7-11e8-9616-33144b6a49cc.png)

**Comment by jihyuunn** [comment]
1 이지현
2 https://github.com/jihyuunn/likelion_week1
3 
![2018-04-01 8 06 07](https://user-images.githubusercontent.com/37537223/38172482-50fa271c-35e8-11e8-986d-07046f17af7d.png)

**Comment by ghost** [comment]
1. 이름 : 장민규
2. github 주소 : 
https://github.com/MinkyuJ/likelion_week1
<img width="960" alt="default" src="https://user-images.githubusercontent.com/37537219/38172738-a5b26cf2-35ec-11e8-83f6-14eafebef9aa.PNG">

**Comment by emilyson** [comment]
1. 이름: 손지연
2. github 주소 : https://github.com/emilyson/likelion_week1
3. 캡처 
<img width="957" alt="default" src="https://user-images.githubusercontent.com/37537203/38172898-7145f832-35ef-11e8-9e0c-502a7bed7618.PNG">

**Comment by hyunjaeyou** [comment]
1: 이름 : 유현재
2. GitHub 주소 : https://github.com/hyunjaeyou/likelion_week1
3. 캡쳐 화면
![default](https://user-images.githubusercontent.com/37537210/38173297-dc3be3ca-35f6-11e8-8a0d-5f38b5b00fd0.png)

**Comment by JIHYUN1110** [comment]
1. 이름: 김지현
2. Github 주소: https://github.com/JIHYUN1110/likelion_week1
3. 캡처 
![default](https://user-images.githubusercontent.com/37537212/38173427-77f88ab4-35f9-11e8-9c4f-0a774705a879.PNG)

**Comment by ingyuseong** [comment]
1.이름 : 성인규
2. GitHub 주소 : https://github.com/staycozyboy/likelion_week1
3. 캡처화면 :
![1-3](https://user-images.githubusercontent.com/37537248/38173432-a80714fa-35f9-11e8-9aba-e7a29e3562c4.png)

**Comment by poongnewga** [comment]
@ashufflepuff @X3PY  @Jack2ee  @Hyezzi @jihyuunn @lsy044 @emilyson @MinkyuJ @hyunjaeyou  @JIHYUN1110 @staycozyboy 다들 고생 많았어요~! 😄

**Comment by karamie** [comment]
1. 이름: 엄가람
2. Github 주소: https://github.com/karamie/likelion_week1
3. 캡쳐화면: 
![_ 3](https://user-images.githubusercontent.com/37537206/38173592-c2a12f74-35fb-11e8-911a-27030cc1a016.PNG)

**Comment by poongnewga** [comment]
@Cecilia-L @seona-yu 수정한 거 확인했고 고생했어요~ :)

**Comment by preeminent77** [comment]
1. 이름: 전재현
2. Github 주소: https://github.com/preeminent77/likelion_week1
3. 캡쳐화면:  
![default](https://user-images.githubusercontent.com/37537194/38174158-2fcbed84-3604-11e8-9a79-ac5446bd59da.jpg)

**Comment by ssng123** [comment]
1. 이름 : 한승희
2. Github 주소 : https://github.com/ssng123/20180328.git
3. Ruby 과제
![image](https://user-images.githubusercontent.com/37537241/38174509-318289da-3609-11e8-83bb-46d24ddaa47e.png)

**Comment by qlqnf16** [comment]
1. 이름: 이정민
2. Github 주소: https://github.com/qlqnf16/0328help
3. Learn Ruby
<img width="960" alt="2018-04-02" src="https://user-images.githubusercontent.com/37537216/38174805-fc6a800e-360d-11e8-90a3-e2eb4fe6b679.png">

**Comment by daisybae** [comment]
1.이름: 배영현
2. Github 주소 : https://github.com/daisybae/likelion_week1.git
3. Ruby 과제
![dlllld](https://user-images.githubusercontent.com/37537214/38175536-521cfcb6-35cd-11e8-8712-6125899f629c.png)

**Comment by hy970723** [comment]
이름 : 최희윤
GitHub 주소: https://github.com/hy970723/likelion_week1
캡쳐화면: <img width="1411" alt="2018-04-02 12 44 12" src="https://user-images.githubusercontent.com/37537254/38174874-0d7ba73c-360f-11e8-8197-2395bb0fd7d6.png">

**Comment by Hyejoojjang** [comment]
1. 이름 : 방혜주
2. GitHub 주소 : https://github.com/Hyejoojjang/HW_RUBY
3. 
<img width="1280" alt="2018-04-02 2 14 17" src="https://user-images.githubusercontent.com/37541410/38175997-71c08ff2-3621-11e8-90cb-9d75e3ac77ff.png">

**Comment by jiwonny** [comment]
1. 이지원
2. GitHub 주소 : https://github.com/jiwonny/likelion_week1
3.
![image](https://user-images.githubusercontent.com/37537213/38320374-5d75f51e-386f-11e8-84f0-e65a225b9528.png)

**Comment by kihyunjoo** [comment]
1. 주기현 
2. Github 주소: https://github.com/kihyunjoo/likelion_week1
3. 
<img width="1134" alt="screen shot 2018-04-08 at 7 27 00 pm" src="https://user-images.githubusercontent.com/37537229/38466364-0317ef22-3b63-11e8-883d-a740563ec845.png">
