### ISSUE TITLE
[7/15 Responsive Web Design 과제]

### ISSUE THREAD

**Issue by woonjangahn** [NEXT-LIKELION/Assignment#40]
## 과제설명
- 1학기 때 각자 만들었던 다음 과제 중 1개 이상을 모바일 반응형으로 리팩토링 해주세요.
  - Instagram (CSS 실습, 스페셜 세션)
  - 미니 해커톤때 개발한 서비스 (자신의 Repository가 아닌 경우 Fork 해서 개발, AWS Key 주의)
- 또는, 현재 중앙 해커톤을 대비 개발중인 사이트를 모바일 / 데스크탑 반응형으로 완성해서 올려주세요.

## 제출방법 및 유의사항
- Chrome Emulator를 이용한 모바일 화면(기종 상관 없음), 그리고 기존에 있던 데스크탑 화면을 캡쳐해서 Github 주소와 함께 올려주세요.
- **7월 15일 세션 전까지** 제출 부탁드립니다.
- 팀별 과제가 아닌 개인 과제입니다.

**Comment by elksha** [comment]
김준태
https://github.com/elksha/Next/tree/master/rwd

--Desktop
![이미지 001](https://user-images.githubusercontent.com/43684130/60876543-13e39280-a277-11e9-9fb9-9486242815d8.png)

--IPad
![이미지 002](https://user-images.githubusercontent.com/43684130/60876564-1e059100-a277-11e9-88b7-31cd219824b7.png)

--IPhone
![이미지 003](https://user-images.githubusercontent.com/43684130/60876573-2231ae80-a277-11e9-90ce-8297dac5ae17.png)

**Comment by Gentleman37** [comment]
이경연입니다
https://github.com/mangod037/first_repo/tree/master/insta
iPhoneX
<img width="300" alt="스크린샷 2019-07-10 오후 9 33 41" src="https://user-images.githubusercontent.com/35323749/60969562-c80a1980-a35a-11e9-9b53-7f23890996fb.png">
iPad
<img width="389" alt="스크린샷 2019-07-10 오후 9 34 00" src="https://user-images.githubusercontent.com/35323749/60969599-e4a65180-a35a-11e9-82d2-b50b0d05737c.png">
iPad Pro
<img width="489" alt="스크린샷 2019-07-10 오후 9 34 14" src="https://user-images.githubusercontent.com/35323749/60969604-e96b0580-a35a-11e9-8bd8-03e029c351d3.png">

**Comment by juno1028** [comment]
김준오

https://github.com/juno1028/FAKE_instagram

**iPhone 6/7/8**
<img width="376" alt="Screen Shot 2019-07-10 at 10 06 38 AM" src="https://user-images.githubusercontent.com/45659499/60976040-f821d000-a2fa-11e9-87a6-7fda3b31f5d3.png">

**iPad**
<img width="576" alt="Screen Shot 2019-07-10 at 10 07 09 AM" src="https://user-images.githubusercontent.com/45659499/60976054-007a0b00-a2fb-11e9-93da-a91ae13a41fc.png">

**Desktop**
<img width="890" alt="Screen Shot 2019-07-10 at 10 07 31 AM" src="https://user-images.githubusercontent.com/45659499/60976081-0ec82700-a2fb-11e9-8d72-1533bc54e184.png">

**Comment by jihakwoo** [comment]
오랜만입니다. 마동석입니다.


![image](https://user-images.githubusercontent.com/44742935/61169043-1ce3a500-a592-11e9-8887-f5694f16194a.png)
데스크탑

![image](https://user-images.githubusercontent.com/44742935/61169032-e86fe900-a591-11e9-8358-a167bf035d12.png)
모바일

https://github.com/woojeee/web-instagram.git

**Comment by parkjihwanjay** [comment]
모바일
<img width="302" alt="mobile1" src="https://user-images.githubusercontent.com/48053238/61179263-1ad52100-a63a-11e9-9b68-1513ef093987.PNG">
<img width="241" alt="mobile2" src="https://user-images.githubusercontent.com/48053238/61179285-89b27a00-a63a-11e9-9b57-920782b24d5c.PNG">

태블릿
<img width="570" alt="tablet1" src="https://user-images.githubusercontent.com/48053238/61179267-21639880-a63a-11e9-8898-f1a819d9fb63.PNG">
<img width="578" alt="tablet2" src="https://user-images.githubusercontent.com/48053238/61179268-245e8900-a63a-11e9-9f74-c3481f3247bd.PNG">
데스크탑
<img width="750" alt="labtop1" src="https://user-images.githubusercontent.com/48053238/61179269-26c0e300-a63a-11e9-9ab7-3d477edf64a3.PNG">
<img width="755" alt="labtop2" src="https://user-images.githubusercontent.com/48053238/61179271-2a546a00-a63a-11e9-8cdb-67f096bbd8c0.PNG">

https://github.com/parkjihwanjay/media_query.git

까먹고 insta로 안하고 새로 만들었습니다. 죄송합니다 ㅜㅜ

**Comment by RyanKor** [comment]
김승태

1. Desktop
![image](https://user-images.githubusercontent.com/40455392/61179369-fda15200-a63b-11e9-9d78-2ad431098594.png)

2.  Mobile
![image](https://user-images.githubusercontent.com/40455392/61180070-3b59a700-a64b-11e9-8cfb-4629db06457a.png)

3. Tablet
![image](https://user-images.githubusercontent.com/40455392/61180090-ae631d80-a64b-11e9-9ffa-85754b11172f.png)

git url : https://github.com/RyanKor/Next-x-Likelion/tree/master/assignment3

**Comment by YUNALEEEE** [comment]
이유나
https://github.com/YUNALEEEE/instagram_responsive

1. 데스크탑
![0715데탑](https://user-images.githubusercontent.com/48678302/61180522-980c9000-a652-11e9-8a28-66709ee8c8de.PNG)

2. 아이패드
![0715 아이패드](https://user-images.githubusercontent.com/48678302/61180524-a064cb00-a652-11e9-959e-e46ac057be10.PNG)

3. 아이폰 6,7,8
![0715아이폰678](https://user-images.githubusercontent.com/48678302/61180528-a8bd0600-a652-11e9-8f71-549df1d7ecc7.PNG)

**Comment by jojoboy2212** [comment]
조형제 
https://github.com/jojoboy2212/responsive_prac

모바일
![스크린샷 2019-07-14 오후 4 50 23](https://user-images.githubusercontent.com/43463542/61181548-2c7eee80-a663-11e9-9da9-45b6d2c4f604.png)
태블릿
![스크린샷 2019-07-14 오후 6 18 10](https://user-images.githubusercontent.com/43463542/61181597-cba3e600-a663-11e9-9d0d-ecfdf23c980a.png)

데스크탑
![스크린샷 2019-07-14 오후 6 18 21](https://user-images.githubusercontent.com/43463542/61181602-cf376d00-a663-11e9-8475-b9e91598f43a.png)

**Comment by Gjunghoon** [comment]
권중훈
home.html -> https://github.com/Gjunghoon/instagram_auth/blob/master/insta/templates/home.html
insta.css -> https://github.com/Gjunghoon/instagram_auth/blob/master/static/insta.css 
레포 https://github.com/Gjunghoon/instagram_auth
개판입니당..

![js2](https://user-images.githubusercontent.com/44766030/61185455-ae3b4000-a694-11e9-8d22-af6fb1946698.gif)

**Comment by antlikelion** [comment]
이인우
제출에 의의를...
https://github.com/antlikelion/responsive-css
1.모바일
![모바일](https://user-images.githubusercontent.com/48678284/61185805-556da680-a698-11e9-9bef-ad0f2a05909c.png)
2.데스크탑
![데스크탑](https://user-images.githubusercontent.com/48678284/61185807-5ef70e80-a698-11e9-9910-ae8b39b7d881.png)

**Comment by wSuhye** [comment]
https://github.com/wSuhye/Center_HW

안수혜

1. 아이폰
![iphone](https://user-images.githubusercontent.com/48678364/61186637-ab474c00-a6a2-11e9-9dc5-22b636db5cb9.JPG)

2. 데스크탑
![web](https://user-images.githubusercontent.com/48678364/61186634-a2567a80-a6a2-11e9-8234-b666074e399a.JPG)

**Comment by updownC** [comment]
최상하

큰화면에서 줄이기 너무힘든것...
https://github.com/sanghaC/likelion7/tree/sanghaC-assign-0715/css

<데스크탑>

![css_assign](https://user-images.githubusercontent.com/48586856/61190878-66d9a180-a6de-11e9-8736-8d1113dc122e.jpg)
<모바일>

![css_assign2](https://user-images.githubusercontent.com/48586856/61190881-735dfa00-a6de-11e9-9739-832a5923462e.jpg)

**Comment by wSuhye** [comment]
https://github.com/wSuhye/Center_HW
안수혜

1.iphone
![iphone](https://user-images.githubusercontent.com/48678364/61196676-483dcf80-a70b-11e9-953e-c880632a48cb.JPG)

2. desktop
![web](https://user-images.githubusercontent.com/48678364/61196682-50960a80-a70b-11e9-9ed0-dc9cde757836.JPG)

**Comment by hoiJuwon** [comment]
1. 데스크탑
<img width="1680" alt="스크린샷 2019-07-15 오후 2 53 43" src="https://user-images.githubusercontent.com/47557351/61197531-66f29500-a710-11e9-99cd-57f4b02b4341.png">


2. 아이패드
<img width="677" alt="스크린샷 2019-07-15 오후 1 44 07" src="https://user-images.githubusercontent.com/47557351/61197262-e717fb00-a70e-11e9-95ac-621e24651f82.png">


https://github.com/hoiJuwon/responsive_insta

**Comment by swcho9919** [comment]
![스크린샷(114)](https://user-images.githubusercontent.com/46709390/61199476-13d11000-a719-11e9-8f40-440d26347ada.png)
![스크린샷(115)](https://user-images.githubusercontent.com/46709390/61199477-13d11000-a719-11e9-83c6-04498ced5246.png)
![스크린샷(118)](https://user-images.githubusercontent.com/46709390/61199537-4c70e980-a719-11e9-8f26-42bd3461c9bf.png)

https://github.com/swcho9919/likelion_assignment

**Comment by chaeyeonie** [comment]
![image](https://user-images.githubusercontent.com/48678352/61200153-7c20f100-a71b-11e9-8d41-42d736fbfc79.png)


![image](https://user-images.githubusercontent.com/48678352/61200261-cc984e80-a71b-11e9-99c6-01b5d6238871.png)


![image](https://user-images.githubusercontent.com/48678352/61200249-bf7b5f80-a71b-11e9-883c-339977c807a0.png)




https://github.com/chaeyeonie/responsiveweb.git

**Comment by gaetokk** [comment]
https://github.com/gaetokk/-
안태경
![1](https://user-images.githubusercontent.com/46814961/61200286-e46fd280-a71b-11e9-8309-ad15166f1074.png)
![2](https://user-images.githubusercontent.com/46814961/61200287-e46fd280-a71b-11e9-858c-bc1e9b73435f.png)
![3](https://user-images.githubusercontent.com/46814961/61200288-e46fd280-a71b-11e9-9922-3e5618f18e06.png)

**Comment by SoniaComp** [comment]
박선영
https://github.com/SoniaComp/NEXT_2/tree/master/hw1_responsive
데스크탑
<img width="823" alt="무제" src="https://user-images.githubusercontent.com/45381486/61200237-b8ece800-a71b-11e9-8eb2-154b2f7457ec.png">
아이폰
<img width="365" alt="무제2" src="https://user-images.githubusercontent.com/45381486/61200241-bab6ab80-a71b-11e9-8b4b-d69b5925b91f.png">
ㅠㅜㅠㅜ 어렵

**Comment by SeeunChoi1** [comment]
최세은
https://github.com/SeeunChoi1/Django_counting_sametext/tree/master/instagram
![image](https://user-images.githubusercontent.com/37589355/61203462-66b0c480-a725-11e9-9781-ca7bd6f2f782.png)
![image](https://user-images.githubusercontent.com/37589355/61203470-6adce200-a725-11e9-8f45-932a1ab3e3fc.png)
![image](https://user-images.githubusercontent.com/37589355/61203477-6d3f3c00-a725-11e9-8a0f-797a0989404e.png)
왜 counting_sametext에 올라갓는지는 모르겟지만...암튼...

**Comment by KimKangYeon** [comment]
김강연
https://github.com/KimKangYeon/HW_
아이폰 678
![image](https://user-images.githubusercontent.com/48678290/61206512-b4c9c600-a72d-11e9-8bdc-337b40fc1b7d.png)
아이패드
![image](https://user-images.githubusercontent.com/48678290/61206534-be532e00-a72d-11e9-844f-40c316dcedb6.png)
데스크탑
![image](https://user-images.githubusercontent.com/48678290/61206609-f195bd00-a72d-11e9-960e-bff9f959d4bb.png)

**Comment by NamJaeyong** [comment]
남재용
https://github.com/NamJaeyong/instaNam
![image](https://user-images.githubusercontent.com/48678278/61206910-b5af2780-a72e-11e9-993b-1e89967fbe13.png)
![image](https://user-images.githubusercontent.com/48678278/61206944-cbbce800-a72e-11e9-907e-2d26a2598863.png)

**Comment by hyunjaeyou** [comment]
[PMF_Test_Plan.docx](https://github.com/NEXT-LIKELION/Assignment/files/3586465/PMF_Test_Plan.docx)
