### ISSUE TITLE
[7/22 Git 협업 / RESTful URI 과제]

### ISSUE THREAD

**Issue by woonjangahn** [NEXT-LIKELION/Assignment#41]
어제 어려운 강의 들으시느라 다들 수고하셨습니다.
과제가 힘들지 몰라도 복습을 위해서 해야하니 이번 과제도 충실히 해주시기 바랍니다!

**이번 과제는 팀 과제입니다.**

## 요구사항
- Django 프로젝트를 새로 만들되 다음 기능들이 있어야 합니다.
  - 회원가입 기능
  - 게시판 기능
  - 게시판의 글마다 댓글 기능 
- 팀원 모두가 Git과 GitHub의 `Pull Request`, `Issue` 등을 활용해주세요.
- `development` 브랜치에서 각각 자신의 이름을 딴 브랜치를 만들어 작업해주시고 팀장은 마지막에 최종본을 `master` 브랜치에 올려주세요.
- RESTful하게 URI를 설계해주세요.

## 선택사항
- CSS / JavaScript

## 제출해야 할 것
- 프로젝트가 완성된 `master` branch 주소 (Repository는 반드시 Public으로 만들어주세요)
- 프로젝트의 페이지별 스크린샷과 URI
- Closed된 `Pull Requests` 스크린샷
- 각 팀의 팀장만 댓글로 올려주시면 됩니다.

**Comment by Gjunghoon** [comment]
★ 팀 ☆ 원 ★ : 권중훈, 남재용, 안태경, 우지학, 이경연, 최세은
- master branch 주소 : https://github.com/Gjunghoon/gugutiger

- 스크린샷과 URI

1. 로그인
![K-008](https://user-images.githubusercontent.com/44766030/61580751-2cde2480-ab50-11e9-86ef-1915272ea05e.png)
2. 회원가입
![K-001](https://user-images.githubusercontent.com/44766030/61580754-32d40580-ab50-11e9-81bd-2208eff833e5.png)
3. home
![K-007](https://user-images.githubusercontent.com/44766030/61580758-3a93aa00-ab50-11e9-8fb6-16fcb492ec24.png)
4. new
![K-002](https://user-images.githubusercontent.com/44766030/61580760-3d8e9a80-ab50-11e9-8b68-049825c243e1.png)
5. detail
![K-005](https://user-images.githubusercontent.com/44766030/61580762-42534e80-ab50-11e9-99c2-42e812f8a776.png)
6. edit
![K-006](https://user-images.githubusercontent.com/44766030/61580763-467f6c00-ab50-11e9-91d9-65fea4b1baf0.png)
7. urls.py
![K-010](https://user-images.githubusercontent.com/44766030/61580792-91997f00-ab50-11e9-8696-ae05050d0598.png)

- closed된 Pull Requests 스크린샷
![K-011](https://user-images.githubusercontent.com/44766030/61580786-85adbd00-ab50-11e9-94a6-f41ba5f6aa7f.png)

**Comment by RyanKor** [comment]
팀원 : 김승태, 이인우, 이채연, 최상하, 박지환, 박선영

Github URL : https://github.com/RyanKor/practice-likelion

1. Closed Pull Request
![image](https://user-images.githubusercontent.com/40455392/61603270-f00d4d00-ac77-11e9-99a7-ca7f6da9e70f.png)

2. REST URL
![image](https://user-images.githubusercontent.com/40455392/61615110-31b1ee00-aca0-11e9-9666-b69daab6e556.png)

3. 로그인, 게시판 확인
![image](https://user-images.githubusercontent.com/40455392/61603277-f7345b00-ac77-11e9-8a1c-3abf6770a1c1.png)

4. 게시글 댓글 작성 페이지
![image](https://user-images.githubusercontent.com/40455392/61603285-00bdc300-ac78-11e9-8663-a74524ec4610.png)

5. 게시글 수정 페이지
![image](https://user-images.githubusercontent.com/40455392/61620223-6a0af980-acab-11e9-89dd-9269082358e8.png)

**Comment by jojoboy2212** [comment]
팀원 : 조형제, 조성우, 최주원, 안수혜

https://github.com/jojoboy2212/0722hw
<img width="430" alt="KakaoTalk_Photo_2019-07-22-18-19-40-3" src="https://user-images.githubusercontent.com/43463542/61621156-52347500-acad-11e9-9ee3-46ab0606c072.png">
<img width="279" alt="KakaoTalk_Photo_2019-07-22-18-19-40-4" src="https://user-images.githubusercontent.com/43463542/61621168-56f92900-acad-11e9-9a39-b3ff89b66cf9.png">
<img width="233" alt="KakaoTalk_Photo_2019-07-22-18-19-40-5" src="https://user-images.githubusercontent.com/43463542/61621177-5a8cb000-acad-11e9-985c-c72dbc11bd19.png">
<img width="376" alt="KakaoTalk_Photo_2019-07-22-18-19-40-7" src="https://user-images.githubusercontent.com/43463542/61621184-5fe9fa80-acad-11e9-84a4-a0f7781b24a2.png">
<img width="488" alt="KakaoTalk_Photo_2019-07-22-18-19-40-2" src="https://user-images.githubusercontent.com/43463542/61621191-64aeae80-acad-11e9-8a3a-32de3a64ef3f.png">
<img width="433" alt="KakaoTalk_Photo_2019-07-22-18-19-40-1" src="https://user-images.githubusercontent.com/43463542/61621194-68423580-acad-11e9-818d-36af3f5e166c.png">

**Comment by elksha** [comment]
김준태, 김강연, 김미라, 김준오, 이유나
https://github.com/elksha/git_assignment

![이미지 009](https://user-images.githubusercontent.com/43684130/61622500-e0115f80-acaf-11e9-8d1a-f25998f4676a.png)
![이미지 010](https://user-images.githubusercontent.com/43684130/61622451-c4a65480-acaf-11e9-9dfc-4db1bb4f4365.png)
![이미지 011](https://user-images.githubusercontent.com/43684130/61622452-c53eeb00-acaf-11e9-8221-956b66c1feeb.png)
![이미지 012](https://user-images.githubusercontent.com/43684130/61622453-c53eeb00-acaf-11e9-82b5-298d60c51df6.png)
![이미지 013](https://user-images.githubusercontent.com/43684130/61622454-c5d78180-acaf-11e9-9634-4156c51418c0.png)
![이미지 014](https://user-images.githubusercontent.com/43684130/61622552-f7504d00-acaf-11e9-8a94-13ef7837fe7d.png)
