### ISSUE TITLE
[9/9 Assignment: PMF Test Plan Upload]

### ISSUE THREAD

**Issue by hyunjaeyou** [NEXT-LIKELION/Assignment#42]
**[PMF Test Plan]**

**마감:** 9/9 수업 전까지
**내용:**
팀별로 프로젝트에 맞게 PMF 테스트 플랜을 짜고 댓글로 업로드해주세요!
양식은 구글 드라이브에 업로드되어 있고, 자유롭게 수정하셔도 됩니다 :)

**Comment by Gjunghoon** [comment]
## Team 구구독입니다.

> 권중훈, 최세은, 안태경, 우지학

[구구독_PMF Test Plan.docx](https://github.com/NEXT-LIKELION/Assignment/files/3588858/_PMF.Test.Plan.docx)

[구구독_PMF Test Plan.pdf](https://github.com/NEXT-LIKELION/Assignment/files/3588905/_PMF.Test.Plan.pdf)

감사합니다.

**Comment by swcho9919** [comment]
막타
조형제 조성우 최주원 이인우

[막타_pmf.docx](https://github.com/NEXT-LIKELION/Assignment/files/3589016/_pmf.docx)

**Comment by RyanKor** [comment]
망고 (망해도 고)

김승태 이채연 최상하 박선영

[망고 PMF_Test_Plan.docx](https://github.com/NEXT-LIKELION/Assignment/files/3589438/PMF_Test_Plan.docx)

**Comment by NamJaeyong** [comment]
도치가잡(도랑치고 가재잡고) 팀

김강연 김준태 남재용

[도치가잡 PMF_Test_Plan.docx](https://github.com/NEXT-LIKELION/Assignment/files/3589554/PMF_Test_Plan.docx)

**Comment by Gentleman37** [comment]
아일로팀
이경연, 박지환

[아일로_PMF_Test_Plan.docx](https://github.com/NEXT-LIKELION/Assignment/files/3589698/_PMF_Test_Plan.docx)

**Comment by juno1028** [comment]
레인업팀
김미라, 김준오, 안수혜, 이유나
[IR자료_레인업.pdf](https://github.com/NEXT-LIKELION/Assignment/files/3589867/IR._.pdf)
[PMF_Test_Plan.pdf](https://github.com/NEXT-LIKELION/Assignment/files/3589927/PMF_Test_Plan.pdf)
