### ISSUE TITLE
[9/16 Assignment: 사업계획서/IR피칭 자료 Upload]

### ISSUE THREAD

**Issue by hyunjaeyou** [NEXT-LIKELION/Assignment#43]
**[사업계획서&IR피칭 자료]**

**마감:** 9/16 수업 전까지
**내용:**
팀별로 프로젝트에 맞게 사업계획서와 IR자료를 작성 후, 댓글로 업로드해주세요!
양식은 구글 드라이브에 업로드되어 있고, 자유롭게 수정하셔도 됩니다 :)
*사업계획서와 IR자료에는 진행했던 PMF 테스트의 결과가 들어있어야 합니다!

**Comment by parkjihwanjay** [comment]
[사업계획서_양식 (2).docx](https://github.com/NEXT-LIKELION/Assignment/files/3615145/_.2.docx)

**Comment by Gjunghoon** [comment]
### **Team 구구독입니다.**
[구구독_ IR자료_초안.pdf](https://github.com/NEXT-LIKELION/Assignment/files/3615497/_.IR._.pdf)
[사업계획서_구구독.docx](https://github.com/NEXT-LIKELION/Assignment/files/3615236/_.docx)

PMF Test는 설문조사 페이지는 만들었으나, 아직 시행하지 못했습니다. 빠른 시일 내에 실행하도록 하겠습니다.

시장조사 또한 자료조사 중입니다.. 우선 한 곳 까지 올립니다.

**Comment by juno1028** [comment]
레인업

[IR자료_레인업.pdf](https://github.com/NEXT-LIKELION/Assignment/files/3615382/IR._.pdf)
[사업계획서_레인업.pdf](https://github.com/NEXT-LIKELION/Assignment/files/3615389/_.pdf)

**Comment by jojoboy2212** [comment]
J2C 막타
용량이 너무 커서 IR자료가 안올라가네요...
나머지 먼저 첨부하였습니다.
[막타 PMF test 결과보고.pptx](https://github.com/NEXT-LIKELION/Assignment/files/3615396/PMF.test.pptx)
[막타 참가신청서.pdf](https://github.com/NEXT-LIKELION/Assignment/files/3615399/default.pdf)

**Comment by parkjihwanjay** [comment]
아일로
[아일로_사업계획서.docx](https://github.com/NEXT-LIKELION/Assignment/files/3615417/_.docx)
[아일로_IR자료.pdf](https://github.com/NEXT-LIKELION/Assignment/files/3615436/_IR.pdf)

**Comment by NamJaeyong** [comment]
[도치가잡 발표.docx](https://github.com/NEXT-LIKELION/Assignment/files/3615705/default.docx)


[도치가잡.pptx](https://github.com/NEXT-LIKELION/Assignment/files/3615697/default.pptx)

**Comment by updownC** [comment]
망고 IR 발표
[mango.pdf](https://github.com/NEXT-LIKELION/Assignment/files/3615716/mango.pdf)
