### ISSUE TITLE
3주차 과제 - 루비 실습하기

### ISSUE THREAD

**Issue by skywoo1994** [NEXT-LIKELION/Assignment#5]
NEXT-LIKELION / Week3에 가면 이번 수업 때 미리 만들어놓은 교안을 올려놓았습니다.

0. 세시간동안 수업을 열정적으로 들어주셔서 감사했습니다. 많이 부족한 수업이었지만 유익한 시간이었길 바랍니다.
1. 복습합니다. 아마 수업시간에 제가 여러분과 함께 만든 rb파일과는 좀 다를거에요. 더 상세한 부분도, 덜 상세한 부분도 있을테니 참고용으로 봐주세요.
2. gookbun.rb파일을 눌러서 봐주세요. 코드를 복사 + 붙여넣기를 통해서 한번 실행해보시면 어떤 식으로 구동하는지 볼 수 있을 것입니다. gookbun.rb 파일의 내용은 오늘 수업내용의 정수를 담은 내용입니다. 다만, loop do 구문이 들어가있는데, 이는 for, while 구문과 연계해서 보시면 충분히 이해하실 수 있으리라 봅니다. 또한 #로 싸여있는 주석을 보시면 이해하실 수 있을 것입니다.
3. silseup.rb파일을 보시면 전체가 주석입니다. crea 케이크 또는 minap 2개의 문제가 올라가있는데요, gookbun.rb와 구조가 거의 비슷한 문제입니다. 기한은 이번 주 목요일까지!입니다. 문제는 굉장히 구체적으로 쓰여있어, 아이디어톤에 참가하지 않았거나 본인의 아이템이 아니더라도 설명서를 상세히 따라가다보면 어느 새 다 풀었을거에요.
4. silseup.rb파일에 대해 답을 찾아 코딩을 하시고 이곳에 실행한 배시 창을 스크린샷하여 댓글로 올려주세요. 아, 오류가 뜨는 코드의 경우에는 댓글로 올리지 마시고 우선 질문을 해주세요! 만약 실패하신다면 코드를 우선 운영진 아무나 잡고 물어봐주시고, 기한 직전까지도 하지 못한다면 고생했다는 것을 증명하기 위해 코드라도 올려주세요.
5. 둘 중 한개만 하면 되지만, 둘 다하고싶으신 분은 둘 다 하는 것을  #추천드립니다. 어려운 알고리즘을 짜는 것보다는 손에 문법을 익히는 목적의 질문들인만큼 한번 해보세요!
과제 기한 : 4/5 수업 직전까지

아래의 양식대로 댓글 부탁해요~
이름 : 심건우
캡쳐 화면

오늘 수업 고생 많으셨습니다. 과제 화이팅입니다!

---

- [x] 김민형
- [x] 김보성
- [x] 김지현
- [x] 박승준
- [x] 방혜주
- [x] 배영현
- [x] 성인규
- [x] 손지연
- [x] 신예찬
- [x] 신한결
- [x] 안성수
- [x] 엄가람
- [x] 오상우
- [x] 원혜진
- [x] 유선아
- [x] 유정아
- [x] 유현재
- [x] 이수영
- [x] 이윤비
- [x] 이재승
- [x] 이정민
- [x] 이지원
- [x] 이지현
- [x] 장민규
- [x] 장영재
- [x] 전재현
- [x] 전준표
- [x] 주기현
- [x] 최희윤
- [x] 한승희
- [x] 허예림
- [x] 허재혁

---

31 / 32 명 완료

**Comment by gyeol1212** [comment]
이름 : 신한결
![2018-04-03 10 49 27](https://user-images.githubusercontent.com/37537201/38224910-3028e776-372d-11e8-8a86-140c41b33ef5.png)
![2018-04-03 11 31 23](https://user-images.githubusercontent.com/37537201/38226091-d4686c30-3732-11e8-9044-e91532e02a8a.png)
한개더!

**Comment by poongnewga** [comment]
@gyeol1212 아니 이렇게 빠르게 과제를... 결이는 희소식이 있을 예정 😋

**Comment by norrard148** [comment]
이름 : 장영재
![default](https://user-images.githubusercontent.com/37537262/38235789-4f93544a-375d-11e8-9f73-7cc9d6171e2c.PNG)

**Comment by skywoo1994** [comment]
@norrard148 영재 구웃~~

**Comment by Cecilia-L** [comment]
이름: 이윤비
<img width="456" alt="default" src="https://user-images.githubusercontent.com/37537232/38238754-d7f5ecfa-3765-11e8-96fd-73f7beb4f355.PNG">

**Comment by Hyejoojjang** [comment]
이름: 방혜주

<img width="882" alt="2018-04-03 6 25 59" src="https://user-images.githubusercontent.com/37541410/38241246-afa78694-376c-11e8-9c48-041414618ffc.png">

**Comment by soonjune** [comment]
이름: 박승준
캡쳐화면
<img width="1200" alt="2018-04-03 7 01 32" src="https://user-images.githubusercontent.com/37537242/38243121-7e986276-3771-11e8-8dc3-852099b1f2d3.png">

**Comment by Hyezzi** [comment]
* 이름 : 원혜진

![image](https://user-images.githubusercontent.com/37537222/38245401-e595dba0-3778-11e8-9d90-4141c1d5b5b2.png)

**Comment by PoSungKim** [comment]
김보성
![_ruby_](https://user-images.githubusercontent.com/37537227/38246990-9ada7084-377e-11e8-9390-51a8c2dcd428.PNG)

**Comment by Jack2ee** [comment]
허재혁
![homework1](https://user-images.githubusercontent.com/37537235/38253974-f7174336-3792-11e8-85da-b7ad6a9a67ea.PNG)

**Comment by jason2133** [comment]
이재승

![2](https://user-images.githubusercontent.com/37537208/38261933-b0919a56-37a6-11e8-89b6-c2e2231344ec.jpg)

**Comment by poongnewga** [comment]
@Cecilia-L 이제 loop - next - break 잘 알겠죠? :)
@Hyejoojjang 너무 예쁘게 잘 만들었어요~ :smile: 
@jamie7060 하얀색 터미널이 인상적...!
@Hyezzi 수업 시간에 했다더니 2개 다 했네 너무 고생했으요~ :+1:

**Comment by sangw0804** [comment]
오상우
![image](https://user-images.githubusercontent.com/37537207/38284647-4e0a5c46-37f7-11e8-8817-14a985a94f5e.png)
![image](https://user-images.githubusercontent.com/37537207/38284681-870df1e2-37f7-11e8-8c24-ba1600d47d2a.png)

**Comment by Cecilia-L** [comment]
1. 이윤비
2. 케이크도 했어요!
<img width="456" alt="default" src="https://user-images.githubusercontent.com/37537232/38286279-84caa968-37ff-11e8-8fdf-c1dbe81f3c4b.PNG">

**Comment by hyunjaeyou** [comment]
1. 유현재
2. 민앱은 과제 끝나구 할게요
![default](https://user-images.githubusercontent.com/37537210/38288177-fcb628e4-3809-11e8-89a6-5c0dab6c9cf6.png)

**Comment by qlqnf16** [comment]
이름: 이정민

<img width="464" alt="3_cake" src="https://user-images.githubusercontent.com/37537216/38288340-382d02de-380b-11e8-866f-812ba387d075.png">

**Comment by kihyunjoo** [comment]
<img width="582" alt="screen shot 2018-04-04 at 4 46 40 pm" src="https://user-images.githubusercontent.com/37537229/38295068-c8f94a72-3827-11e8-9505-7dbffcd669a4.png">

주기현

**Comment by preeminent77** [comment]
![image](https://user-images.githubusercontent.com/37537194/38295327-98c1b384-3828-11e8-83de-d04c773aa52f.png)
전재현

**Comment by ingyuseong** [comment]
이름 : 성인규
![3](https://user-images.githubusercontent.com/37537248/38296957-f475c68e-382d-11e8-8662-c08da1317d57.png)

**Comment by dkor3** [comment]
안성수 과제 ㅋ 
![default](https://user-images.githubusercontent.com/37537204/38300196-26f760b4-3837-11e8-8830-7ac6a0fc2b45.png)

**Comment by ghost** [comment]
<img width="960" alt="cake" src="https://user-images.githubusercontent.com/37537219/38300293-6348f2ee-3837-11e8-9f3b-aa735247c75e.PNG">
장민규 입니다

**Comment by dkor3** [comment]
안성수 삘받아서 재현이도 만들었습니다 ㅋ
![default](https://user-images.githubusercontent.com/37537204/38301613-0bf415ec-383b-11e8-8108-ea324913e766.png)

**Comment by hy970723** [comment]
이름 : 최희윤
<img width="983" alt="2018-04-04 8 49 35" src="https://user-images.githubusercontent.com/37537254/38305980-e22ce0a4-3849-11e8-99fa-5fefb88c3b67.png">

**Comment by X3PY** [comment]
1. 전준표
2. 
![0404](https://user-images.githubusercontent.com/37537209/38307704-91868302-384f-11e8-86a4-c9b8511f4f55.PNG)

**Comment by jiwonny** [comment]
이지원
<img width="948" alt="default" src="https://user-images.githubusercontent.com/37537213/38318822-3e84e97a-386b-11e8-8c32-23d08dc5328f.PNG">
<img width="960" alt="default" src="https://user-images.githubusercontent.com/37537213/38318823-3eb3b480-386b-11e8-82a4-bdc1487dd584.PNG">

**Comment by JIHYUN1110** [comment]
김지현

![_ _1](https://user-images.githubusercontent.com/37537212/38325150-2585318e-387d-11e8-88a3-839ea7c759b9.PNG)

![_ _2](https://user-images.githubusercontent.com/37537212/38325160-29aee6b0-387d-11e8-9c43-730351dda7f4.PNG)

**Comment by YeChan1030** [comment]
드디어!
![2](https://user-images.githubusercontent.com/37537205/38326782-a76f8dee-3881-11e8-8713-20d7bb13d992.PNG)


신예찬

**Comment by seona-yu** [comment]
<img width="944" alt="4 5" src="https://user-images.githubusercontent.com/37537217/38334587-af33693c-3896-11e8-912f-3a1f947074ce.png">

유선아

**Comment by mhbest** [comment]
![image](https://user-images.githubusercontent.com/37537238/38340843-7a86a950-38b0-11e8-921b-7115f0d15e0e.png)
1. 제 vagrant 가 이상해서 bash창이 접속이 안되요
2. 코드를 짜봤는데 맞는지 모르겠어서 일단 할 수 있을 때가지 해보았어요.
3. 이따 수업끝나는 대로 파이빌 가서 질문할게요 ^^

**Comment by jihyuunn** [comment]
![2018-04-05 2 08 36](https://user-images.githubusercontent.com/37537223/38348137-038c93ac-38db-11e8-8b55-55914db3c23d.png)
이지현

**Comment by daisybae** [comment]
![image](https://user-images.githubusercontent.com/37537214/38348763-ac4c60aa-38de-11e8-939f-1069e5274aef.png)
배영현이라는 사람

**Comment by karamie** [comment]
엄가람
![kakaotalk_20180405_153340906](https://user-images.githubusercontent.com/37537206/38350667-482a7464-38e7-11e8-8c7f-66d7ff0a3e26.png)

**Comment by emilyson** [comment]
손지연
<img width="487" alt="default" src="https://user-images.githubusercontent.com/37537203/38351182-64f5e69e-38e9-11e8-905f-950a04cf9fc2.PNG">

**Comment by Yerim2695** [comment]
허예림
호텔은 시간 범위를 어케 해야할지 모르겟네요 ㅜㅜ 
![default](https://user-images.githubusercontent.com/37537200/38351683-92061e72-38eb-11e8-82da-8697e01ad175.jpg)

**Comment by ssng123** [comment]
1. 한승희
2. 뭔가 약간 엉성하지만,, 제출할게요 ^_ㅠ
![image](https://user-images.githubusercontent.com/37537241/38353996-1623b6d6-38f3-11e8-9f51-31a2d0b9841c.png)

**Comment by ashufflepuff** [comment]
1. 유정아
2. files
<img width="453" alt="03" src="https://user-images.githubusercontent.com/37537211/38359402-3cf94ce8-3903-11e8-994e-0969e6b27108.PNG">
<img width="460" alt="04" src="https://user-images.githubusercontent.com/37537211/38359403-3e3b617c-3903-11e8-8fe7-1c5d2972fb2b.PNG">

**Comment by swimmie0** [comment]
![image](https://user-images.githubusercontent.com/37537202/38469367-9cd2bb1c-3b8e-11e8-916f-a68d46feb527.png)
이수영
