### ISSUE TITLE
3주차 과제 - Rails Flow 익히기(4/9 세션전까지)

### ISSUE THREAD

**Issue by poongnewga** [NEXT-LIKELION/Assignment#6]
## Rails 기본 커맨드

```shell
# 새로운 프로젝트 생성
$ rails new practice

# 프로젝트 폴더로 이동
$ cd practice

# 새로운 컨트롤러 및 index 액션 생성
$ rails g controller home index

# 서버 시작(종료는 Ctrl + C)
$ rails s
```

## 과제 안내

1. 새로운 프로젝트를 하나 만들어주세요.
2. home 컨트롤러와 index 액션을 만들어주세요.
3. `http://localhost:3000` 을 입력했을 때, `/home/index` 와 동일한 화면이 나오게끔 `routes.rb`를 수정해주세요.(힌트 : 뿌리)
4. `application_controller.rb` 파일에서 `protect_from_forgery with: :exception` 를 주석처리해주세요.
5. home 컨트롤러 내에 `login` 액션을 만들고 `app/views/home` 안에 login 템플릿(login.html.erb)을 만들어주세요.
6. post 방식으로, 'login'이라는 주소를 요청하면, home 컨트롤러 내에 있는 login 액션이 해당 요청을 처리하게끔 `routes.rb`를 수정해주세요.
7. index 템플릿을 수정합니다. 예쁘게 만들지 않아도 좋습니다. form 태그 내에 텍스트를 입력받을 수 있는 type="text"의 input 태그 1개(name은 "id"로 해주세요), 전송을 할 수 있게 해주는 type="submit"의 input 태그 1개("제출"이라고 쓰여있는 버튼을 만들어주세요.)만 들어가면 됩니다. 단, 제출 버튼을 눌렀을 때, 데이터가 `/login`이라는 주소로, post 방식을 사용해 전달되게끔 코드를 작성해주세요.
8. input 태그는 type, name, value 등의 attribute를 갖습니다. 이 중에서 name 속성이 서버로 전달되는 데이터를 구분해주는 역할을 합니다. 7을 제대로 수행하셨다면 name="id"라는 input 태그에 작성된 데이터가 서버에 전달되고, 레일즈에서는 "id"라는 이름을 통해 이 데이터를 확인할 수 있습니다. home 컨트롤러 내의 login 액션을 다음과 같이 작성해주세요.

```ruby

def login

  @name = "ERROR"

end

```

9. login 템플릿을 다음과 같이 작성합니다.

```

<%= @name %>

```

10. 이제 실제 페이지를 확인해보면 어떤 데이터를 입력하던 `/login`으로 이동하면서 ERROR라는 텍스트가 뜰 것입니다. 수업시간에 다뤘던 것처럼 만약 "id"라는 name 을 가진 input 태그에 적힌 내용이 "HEEHAM"인 경우 SUCCESS 라는 텍스트를 출력하려면 어떻게 해야 할까요? if 문을 사용해서 해결해주세요.

```ruby

def login

  @name = "ERROR"

  # 여기를 수정하여 해결해주세요. 
  # 어떤 조건이 들어가면 전달받은 데이터가 "HEEHAM"인 경우에만 
  # @name 에 "SUCCESS" 라고 저장할까요?
  # if 
  #   @name = "SUCCESS"
  # end

end

```

---

### Sample Views

<img width="239" alt="2018-04-06 8 41 04" src="https://user-images.githubusercontent.com/15710904/38419325-04b3bc00-39db-11e8-83a4-ae7562d964ba.png">
<img width="271" alt="2018-04-06 8 41 23" src="https://user-images.githubusercontent.com/15710904/38419329-052b995a-39db-11e8-801f-ec153c401a5f.png">
<img width="252" alt="2018-04-06 8 41 38" src="https://user-images.githubusercontent.com/15710904/38419328-0503cce0-39db-11e8-9ee2-f5b522bf0327.png">
<img width="282" alt="2018-04-06 8 41 46" src="https://user-images.githubusercontent.com/15710904/38419326-04db317c-39db-11e8-9fbc-c9d3a8cae37a.png">

---

* 이번 과제는 따로 캡쳐나 코드를 받지 않겠습니다. 자유롭게 복습 및 실습을 해주세요. 이 과제는 의도된, 조금 불친절한 과제입니다. 수업시간에 알려드린 각종 용어만을 사용하여 과제를 안내했습니다. 1~10 번 설명 중 모르는 단어가 1개라도 있으면 곤란합니다. `protect_from_forgery with: :exception`는 몰라도 됩니다 :) 위 과제를 수행한 뒤 SUCCESS라는 텍스트를 잘 출력하셨다면, 그리고 모르는 단어가 1개라도 없다면 댓글로 이름 - SUCCESS 라고 달아주시면 과제 끝입니다. 혹여나 예쁘게 만드셨다면 캡쳐로 자랑하셔도 좋습니다. 더 많은 열정을 보여주시는 분들은 제가 그에 상응하는 대우를 해드리겠습니다.

* 필요하다면 수업시간에 복붙했던  https://github.com/poongnewga/week3 의 코드를 참조해주세요. 물론 여기에는 여러분이 이해할 수 없는 코드도 들어있습니다. 

이 과제를 잘 수행하시고 제대로 이해하셨다면 여러분은 Model을 필요로 하지 않는, 간단한 서비스들을 모두 개발하실 수 있는 능력을 갖추시게 됩니다. 일단은 1~10번만 잘 숙지하도록 합시다. 화이팅!

제출 예)
채희재 - SUCCESS

---

- [ ] 김민형
- [x] 김보성
- [x] 김지현
- [x] 박승준
- [x] 방혜주
- [x] 배영현
- [x] 성인규
- [x] 손지연
- [ ] 신예찬
- [x] 신한결
- [x] 안성수
- [x] 오상우
- [x] 원혜진
- [x] 유선아
- [x] 유정아
- [x] 유현재
- [x] 이수영
- [x] 이윤비
- [x] 이재승
- [x] 이정민
- [x] 이지원
- [x] 이지현
- [x] 장민규
- [x] 장영재
- [x] 전재현
- [x] 전준표
- [x] 주기현
- [ ] 최희윤
- [x] 한승희
- [x] 허예림
- [x] 허재혁

28/ 31 명 완료

**Comment by soonjune** [comment]
박승준 - SUCCESS

과제 올라오자마자 했어요!

**Comment by gyeol1212** [comment]
신한결 - SUCCESS
![2018-04-07 12 19 42](https://user-images.githubusercontent.com/37537201/38429481-7c1b2d1e-39f9-11e8-92fd-994589ec14f1.png)

**Comment by norrard148** [comment]
장영재

![default](https://user-images.githubusercontent.com/37537262/38430987-d4863030-39fd-11e8-9e14-1e56759cc39d.PNG)

**Comment by Cecilia-L** [comment]
이윤비
<img width="224" alt="default" src="https://user-images.githubusercontent.com/37537232/38451894-a939fb48-3a73-11e8-8656-a936a2b9e8b8.PNG">

**Comment by jihyuunn** [comment]
이지현
![2018-04-07 4 03 14](https://user-images.githubusercontent.com/37537223/38452338-46b16056-3a7d-11e8-8652-b970bbfb14f4.png)

**Comment by X3PY** [comment]
전준표
![1](https://user-images.githubusercontent.com/37537209/38452647-1eddf43a-3a83-11e8-8701-cc6c8bee678c.PNG)
![2](https://user-images.githubusercontent.com/37537209/38452648-1f03f69e-3a83-11e8-8498-af2695dbeb8c.PNG)

**Comment by ssng123** [comment]
한승희  (포맷은 히재 님이랑 수업 때 썼던 거 재활용 ㅎ.ㅎ)

![image](https://user-images.githubusercontent.com/37537241/38453274-d257804e-3a8d-11e8-8d90-27eed190cad8.png)

**Comment by sangw0804** [comment]
오상우
<img width="219" alt="1" src="https://user-images.githubusercontent.com/37537207/38454710-21375928-3aa7-11e8-9156-1660952ea0f1.png">
<img width="288" alt="2" src="https://user-images.githubusercontent.com/37537207/38454735-791e0b3c-3aa7-11e8-9f8f-b3894a5dbc6f.png">
<img width="223" alt="3" src="https://user-images.githubusercontent.com/37537207/38454714-2526c4e2-3aa7-11e8-8ad7-9a0f1244a866.png">
<img width="224" alt="4" src="https://user-images.githubusercontent.com/37537207/38454716-270fad3c-3aa7-11e8-9da0-e1a441bdce54.png">
<img width="275" alt="5" src="https://user-images.githubusercontent.com/37537207/38454717-28c0387c-3aa7-11e8-833b-b53109137b4d.png">
<img width="263" alt="6" src="https://user-images.githubusercontent.com/37537207/38454722-346de1c4-3aa7-11e8-97fc-66931d4f666e.png">

**Comment by PoSungKim** [comment]
김보성
![_rails 1_](https://user-images.githubusercontent.com/37537227/38456610-4bca694a-3ac1-11e8-9947-107799cb7b11.PNG)
![_rails 2_](https://user-images.githubusercontent.com/37537227/38456611-4d63e290-3ac1-11e8-8ece-c53da2f71b94.PNG)

**Comment by preeminent77** [comment]
![image](https://user-images.githubusercontent.com/37537194/38462310-d793920e-3b1f-11e8-8625-14b987977786.png)
전재현-SUCCESS

**Comment by swimmie0** [comment]
![image](https://user-images.githubusercontent.com/37537202/38464274-e11e3f4c-3b45-11e8-9585-523bf53cf609.png)


이수영

**Comment by poongnewga** [comment]
@gyeol1212 아주 완벽하게 이해했네 :)
@ssng123 귀엽게 잘 만들었어요~
@sangw0804 감자 감성 맘에 든다.
@lsy044 폼 색깔이 올해의 색이네요 :smile:  :+1:

**Comment by ashufflepuff** [comment]
유정아
<img width="302" alt="01" src="https://user-images.githubusercontent.com/37537211/38465969-0d6ea8ae-3b5d-11e8-8bb5-4900f334e360.PNG">
<img width="262" alt="error" src="https://user-images.githubusercontent.com/37537211/38465970-0f37d994-3b5d-11e8-9b2b-b0eb42804bb7.PNG">
<img width="246" alt="heeham" src="https://user-images.githubusercontent.com/37537211/38465976-11877b3c-3b5d-11e8-906a-e07ea79e3450.PNG">
<img width="270" alt="success" src="https://user-images.githubusercontent.com/37537211/38465979-141e8304-3b5d-11e8-84ac-145d0c63bc16.PNG">

**Comment by hyunjaeyou** [comment]
유현재 - SUCCESS

**Comment by daisybae** [comment]
배영현
예쁘게 만든건 아니지만 제가 했다는 사실이 신기해서 올려봅니다..ㅎㅎ
![image](https://user-images.githubusercontent.com/37537214/38466372-1eeca04e-3b63-11e8-92bc-5f3e0e77cc8f.png)
![image](https://user-images.githubusercontent.com/37537214/38466496-fb8ffa86-3b64-11e8-83f6-d71ebe23e696.png)
![image](https://user-images.githubusercontent.com/37537214/38466489-e9d6aa9c-3b64-11e8-9cd0-fce4acffd392.png)

**Comment by JIHYUN1110** [comment]
김지현
아직 어렵지만..ㅎㅎ

![_ _1](https://user-images.githubusercontent.com/37537212/38467556-43d6c2c4-3b75-11e8-9e08-e3971172b78e.PNG)

![_ _2](https://user-images.githubusercontent.com/37537212/38467558-46f5bca8-3b75-11e8-8241-14338836ce64.PNG)

**Comment by seona-yu** [comment]
<img width="215" alt="4 9 1" src="https://user-images.githubusercontent.com/37537217/38468707-d989b060-3b84-11e8-8d13-e018fc2e1467.png">
<img width="228" alt="4 9 2" src="https://user-images.githubusercontent.com/37537217/38468718-ddc32d46-3b84-11e8-9bb5-c913ec5d3677.png">

유선아

**Comment by ingyuseong** [comment]
성인규 입니다ㅏ.
![hw4_1](https://user-images.githubusercontent.com/37537248/38469772-87a71912-3b49-11e8-8aa6-4cb23de3c37b.JPG)
![hw4_2](https://user-images.githubusercontent.com/37537248/38469773-8a7324ba-3b49-11e8-8167-fb63678fb018.JPG)
![hw4_3](https://user-images.githubusercontent.com/37537248/38469774-8c92b4a4-3b49-11e8-813d-6b0d8fc972ad.JPG)
![hw4_4](https://user-images.githubusercontent.com/37537248/38469776-9010fae6-3b49-11e8-9af7-7975f08642a9.JPG)

**Comment by jiwonny** [comment]
이지원
<img width="354" alt="login" src="https://user-images.githubusercontent.com/37537213/38470013-2e128284-3b98-11e8-836d-ee388bc81bf1.PNG">
<img width="225" alt="success" src="https://user-images.githubusercontent.com/37537213/38470014-2e3c4c36-3b98-11e8-9bd8-402dcd56f201.PNG">

**Comment by Hyezzi** [comment]
원혜진
![image](https://user-images.githubusercontent.com/37537222/38470199-38702f04-3b9a-11e8-93dc-cc2000a6ba53.png)

![image](https://user-images.githubusercontent.com/37537222/38470192-1621d434-3b9a-11e8-9dd8-58d0abaccfa5.png)

**Comment by qlqnf16** [comment]
이정민
<img width="332" alt="4" src="https://user-images.githubusercontent.com/37537216/38470770-8f19cfd8-3ba2-11e8-88ee-f99c0763c85f.png">

**Comment by poongnewga** [comment]
@staycozyboy ㅋㅋㅋㅋㅋㅋㅋㅋ 귀엽네요~ 마음에 듭니다
@qlqnf16 오.. 플래시도 활용한 건가요? 아주 잘 만들었네요 ㅎㅎ

**Comment by Hyejoojjang** [comment]
<img width="624" alt="2018-04-09 11 26 09" src="https://user-images.githubusercontent.com/37541410/38476480-f310da40-3be8-11e8-8648-7d370d5bbcaf.png">

<img width="574" alt="2018-04-09 11 26 14" src="https://user-images.githubusercontent.com/37541410/38476481-f6a2e0ea-3be8-11e8-820a-84deea82f367.png">

방혜주- SUCCESS

**Comment by ghost** [comment]
장민규
<img width="949" alt="1" src="https://user-images.githubusercontent.com/37537219/38477006-87998520-3beb-11e8-902a-2958fb8e2858.PNG">
<img width="949" alt="2" src="https://user-images.githubusercontent.com/37537219/38477009-88a23980-3beb-11e8-867f-438b89bf6534.PNG">

**Comment by jason2133** [comment]
![12312312414](https://user-images.githubusercontent.com/37537208/38479237-a96dc794-3bf8-11e8-9601-e33e6d1c91b0.jpg)


![123456](https://user-images.githubusercontent.com/37537208/38479142-35f8c354-3bf8-11e8-8534-94e654fb44da.jpg)

이재승 :)
SUCCESS~

**Comment by Jack2ee** [comment]
허재혁
SUCCESS

**Comment by kihyunjoo** [comment]
![kihyun](https://user-images.githubusercontent.com/37537229/38480892-2857dcb6-3c03-11e8-9fd7-ad23147a700b.jpg)


주기현

**Comment by poongnewga** [comment]
@Hyejoojjang ㅎㅎㅎㅎ 너무 기분 조아요~~~~ 😸 잘했어요 :)

**Comment by emilyson** [comment]
손지연
SUCCESS

**Comment by dkor3** [comment]
안성수 썪세스 ㅋ
![4 5](https://user-images.githubusercontent.com/37537204/38484576-08ad5c74-3c12-11e8-87d5-1ec0b590344f.png)

**Comment by Yerim2695** [comment]
허예림
태엽쓰의 도움으로.. 
SUCCESS~~

**Comment by YeChan1030** [comment]
신예찬
Vagrant 에러로 인해 Ubuntu 설치하느라 제대로 복습하지 못하였습니다 ㅠㅠ
