### ISSUE TITLE
4주차 과제 -  CRUD 복습

### ISSUE THREAD

**Issue by nooheateel** [NEXT-LIKELION/Assignment#7]
여러분 시험보시느라 고생 많으셨습니다. 고생한 여러분들 머리 식히는 겸 쉬어가시라고 지난 주에 배웠던 CRUD 복습 과제를 내드리도록 하겠습니다!

1) 지난 번 수업시간에 실습했던 내용을 바탕으로 나만의 소소한 페이지를 만들어 보세요. 일기장도 좋고 가계부도 괜찮습니다. 너무 화려하거나 많은 내용이 들어갈 필요는 없으나 CRUD를 꼭 활용해서 사이트를 제작해주세요. 완성 후에는 자신의 github repository에 올리신 후 주소를 댓글에 달아주세요. 

2) MVC패턴을 현실의 커피숍과 비교를 했었습니다. 레일즈의 MVC패턴 및 클라이언트가 요청(request)을 하고 응답(respond)를 받는 일련의 과정을 커피숍에서 커피를 주문하고 제공 받는 과정에 빗대어 최대한 상세하게 설명해주세요. 작성 후 이태훈 카카오톡으로 보내주시면 되겠습니다. 

마감 기한: ~4.30(월) 19:00

[Week4_CRUD_2.pdf](https://github.com/NEXT-LIKELION/Assignment/files/1949987/Week4_CRUD_2.pdf)

- [ ] 김민형
- [ ]  김보성
- [ ]  김지현
- [ ]  박승준
- [ ]  방혜주
- [ ]  배영현
- [ ]  성인규
- [ ]  손지연
- [ ]  신예찬
- [ ]  신한결
- [ ]  안성수
- [ ]  오상우
- [ ]  원혜진
- [ ]  유선아
- [ ]  유정아
- [ ]  유현재
- [ ]  이수영
- [ ]  이윤비
- [ ]  이재승
- [ ]  이정민
- [ ]  이지원
- [ ]  이지현
- [ ]  장민규
- [ ]  장영재
- [ ]  전재현
- [ ]  전준표
- [ ]  주기현
- [ ]  최희윤
- [ ]  한승희
- [ ]  허예림
- [ ]  허재혁

**Comment by gyeol1212** [comment]
https://github.com/gyeol1212/crud_review.git

**Comment by sangw0804** [comment]
오상우
https://github.com/sangw0804/budgetManager

**Comment by norrard148** [comment]
장영재
https://github.com/norrard148/likelion_week-

**Comment by jamie7060** [comment]
https://github.com/jamie7060/crud_review

**Comment by soonjune** [comment]
박승준
https://github.com/jamie7060/crud_review

**Comment by ghost** [comment]
장민규
https://github.com/MinkyuJ/likelion_CRUD

**Comment by jason2133** [comment]
이재승
https://github.com/jason2133/crud_diary

**Comment by qlqnf16** [comment]
이정민
https://github.com/qlqnf16/review_crud

**Comment by Hyezzi** [comment]
원혜진
https://github.com/Hyezzi/CRUD

**Comment by jiwonny** [comment]
이지원
https://github.com/jiwonny/crudjw

**Comment by ingyuseong** [comment]
성인규
https://github.com/staycozyboy/crud_review

**Comment by jihyuunn** [comment]
https://github.com/jihyuunn/CRUD

**Comment by swimmie0** [comment]
이수영
https://github.com/lsy044/crud

**Comment by X3PY** [comment]
전준표
https://github.com/X3PY/crud_hw

**Comment by hyunjaeyou** [comment]
유현재입니다
https://github.com/hyunjaeyou/crud

**Comment by Cecilia-L** [comment]
이윤비
https://github.com/Cecilia-L/CRUD

**Comment by Jack2ee** [comment]
허재혁
https://github.com/Jack2ee/HW_CRUD

**Comment by JIHYUN1110** [comment]
김지현
https://github.com/JIHYUN1110/crud_review

**Comment by kihyunjoo** [comment]
주기현 
https://github.com/kihyunjoo/self_reflection.git

**Comment by ssng123** [comment]
한승희
https://github.com/ssng123/20180430.git

**Comment by ashufflepuff** [comment]
유정아
https://github.com/ashufflepuff/likelion_april

**Comment by Yerim2695** [comment]
허예림
https://github.com/Yerim2695/-6.git

**Comment by YeChan1030** [comment]
https://github.com/YeChan1030/CRUD-Review

**Comment by seona-yu** [comment]
https://github.com/seona-yu/crud
유선아

**Comment by daisybae** [comment]
배영현
https://github.com/daisybae/homework7.git
게게게게

**Comment by PoSungKim** [comment]
https://github.com/PoSungKim/crud1
김보성

**Comment by emilyson** [comment]
https://github.com/emilyson/crudhomework.git
손지연

**Comment by mhbest** [comment]
https://github.com/mhbest/homework-3.git
김민형

**Comment by Hyejoojjang** [comment]
https://github.com/Hyejoojjang/Crud_Babo_Hyeju.git
