### ISSUE TITLE
5주차 과제 - Scaffold로 중고나라 게시판 만들기 (~5/3 19:00)

### ISSUE THREAD

**Issue by woonjangahn** [NEXT-LIKELION/Assignment#8]
오늘은 중고나라 게시판을 만들어봅시다.

메인 페이지 (인사말 + '중고거래 게시판'으로 가는 링크를 helper을 이용해 추가할 것)
중고거래 게시판 (Scaffold를 이용해서 만들되, string이나 text뿐 아닌 다른 자료형식도 사용할 것)

그리고, 파일들을 찬찬히 뜯어보며 최대한 **모든 페이지들을 한글화**해주시기 바랍니다.

완성된 과제 샘플 화면을 첨부합니다.
적당하다 생각하는 Column들이 있다면 자유롭게 추가해주시면 됩니다.

완성된 화면을 캡쳐하여 Comment로 올려주세요.

![1](https://user-images.githubusercontent.com/26547475/39505731-5ebcee5e-4e0f-11e8-983c-1c133817de07.PNG)
![2](https://user-images.githubusercontent.com/26547475/39505737-6279159a-4e0f-11e8-991e-f114dab84a1a.PNG)

**Comment by gyeol1212** [comment]
신한결
![2018-05-02 2 25 15](https://user-images.githubusercontent.com/37537201/39506641-ebf28662-4e14-11e8-9765-2ca0a76d0d17.png)
![2018-05-02 2 25 23](https://user-images.githubusercontent.com/37537201/39506637-eaad5426-4e14-11e8-919a-158a69d3d211.png)
![2018-05-02 2 26 11](https://user-images.githubusercontent.com/37537201/39506639-eb34f674-4e14-11e8-9b7d-569f2e7b219f.png)

**Comment by hyunjaeyou** [comment]
유현재입니다
![nara1](https://user-images.githubusercontent.com/37537210/39509415-30a991c2-4e21-11e8-8b58-908e1bda67d5.png)
![nara2](https://user-images.githubusercontent.com/37537210/39509417-32335a64-4e21-11e8-9177-51ef635e600b.png)

**Comment by qlqnf16** [comment]
이정민
<img width="960" alt="2018-05-02 1" src="https://user-images.githubusercontent.com/37537216/39509473-5f829d90-4e21-11e8-899a-4c22c3146887.png">
<img width="960" alt="2018-05-02 2" src="https://user-images.githubusercontent.com/37537216/39509470-5f52d182-4e21-11e8-9d76-091052d8f20f.png">

**Comment by Yerim2695** [comment]
허예림



![0](https://user-images.githubusercontent.com/37537200/39510363-76886530-4e24-11e8-8e29-d774f3125f4d.jpg)
![1](https://user-images.githubusercontent.com/37537200/39510364-76b60eea-4e24-11e8-91cb-b388412393fe.jpg)
![2](https://user-images.githubusercontent.com/37537200/39510367-76e29b22-4e24-11e8-99aa-022bd2407013.jpg)

**Comment by mhbest** [comment]
김민형
![11](https://user-images.githubusercontent.com/37537238/39517549-1b7fb6f4-4e3b-11e8-80fa-fc6fc72478fa.PNG)
![12](https://user-images.githubusercontent.com/37537238/39517552-1d37df3a-4e3b-11e8-8883-93c6439d456d.PNG)
![13](https://user-images.githubusercontent.com/37537238/39517555-1ec21758-4e3b-11e8-9907-7b02323d238a.PNG)

**Comment by Jack2ee** [comment]
허재혁
![home](https://user-images.githubusercontent.com/37537235/39521402-51e87006-4e49-11e8-9984-8b1dd988f91e.PNG)
![index](https://user-images.githubusercontent.com/37537235/39521409-57359e26-4e49-11e8-8487-554e6e00ca69.PNG)

**Comment by Hyezzi** [comment]
원혜진
![image](https://user-images.githubusercontent.com/37537222/39523265-ec2573de-4e4f-11e8-9833-b6e5b9d608a7.png)

**Comment by sangw0804** [comment]
오상우
![image](https://user-images.githubusercontent.com/37537207/39525981-7a47b156-4e58-11e8-8fc9-bf838f07aa8e.png)
![image](https://user-images.githubusercontent.com/37537207/39526063-a89f93e8-4e58-11e8-9d18-f25fc36f30ea.png)
![image](https://user-images.githubusercontent.com/37537207/39526116-ccca911e-4e58-11e8-9d6b-1f623db64ee7.png)

**Comment by ghost** [comment]
장민규 입니다 !
<img width="960" alt="1" src="https://user-images.githubusercontent.com/37537219/39526839-fbd9702c-4e5a-11e8-839e-1aa57af2b3fa.PNG">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/37537219/39526841-fc669fd8-4e5a-11e8-90d8-86cae6345fde.PNG">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/37537219/39526843-fd1b7dfe-4e5a-11e8-9346-152807d3a4f6.PNG">

**Comment by soonjune** [comment]
박승준
<img width="1275" alt="2018-05-02 11 21 17" src="https://user-images.githubusercontent.com/37537242/39529180-098d1448-4e61-11e8-9004-4840a602285d.png">
<img width="1274" alt="2018-05-02 11 26 12" src="https://user-images.githubusercontent.com/37537242/39529192-0e8c76a0-4e61-11e8-8695-1ca236e0ffc9.png">
<img width="1273" alt="2018-05-02 11 21 40" src="https://user-images.githubusercontent.com/37537242/39529197-10904f12-4e61-11e8-9ea9-8943e5d98c38.png">

**Comment by seona-yu** [comment]
유선아
<img width="392" alt="scaffold1" src="https://user-images.githubusercontent.com/37537217/39530080-1f22d9d0-4e63-11e8-94e5-f8d038bd73ff.png">
<img width="960" alt="scaffold22" src="https://user-images.githubusercontent.com/37537217/39530083-2289bd46-4e63-11e8-81ed-190a95569c6d.PNG">
<img width="960" alt="scaffold3" src="https://user-images.githubusercontent.com/37537217/39530091-259c2438-4e63-11e8-83e9-f01d48a48423.PNG">

**Comment by dkor3** [comment]
안성수
<img width="1000" alt="2018-05-03 12 06 31" src="https://user-images.githubusercontent.com/37537204/39531438-1b2ea0fe-4e66-11e8-9614-2002119a9e52.png">
<img width="911" alt="2018-05-03 12 06 41" src="https://user-images.githubusercontent.com/37537204/39531440-1d24fac0-4e66-11e8-8bf4-1fa1cb6e882e.png">
<img width="999" alt="2018-05-03 12 06 18" src="https://user-images.githubusercontent.com/37537204/39531453-22d6c96c-4e66-11e8-81e4-c23e28f7d424.png">

**Comment by norrard148** [comment]
장영재
![1](https://user-images.githubusercontent.com/37537262/39532292-8c23f934-4e67-11e8-8df7-3f066517cf22.PNG)
![122](https://user-images.githubusercontent.com/37537262/39532294-8c535a30-4e67-11e8-9b7f-00726e5b4ead.PNG)

**Comment by X3PY** [comment]
전준표
![default](https://user-images.githubusercontent.com/37537209/39532459-d3c3369c-4e67-11e8-9db2-38a2f1e2da84.PNG)
![1](https://user-images.githubusercontent.com/37537209/39532464-d74a788e-4e67-11e8-8029-41b31e08e593.PNG)
![2](https://user-images.githubusercontent.com/37537209/39566465-a373646e-4ef6-11e8-8bb9-c3f106fd1dff.PNG)
![3](https://user-images.githubusercontent.com/37537209/39566470-a5f5c9a2-4ef6-11e8-83c9-d42b84f429fb.PNG)

**Comment by ssng123** [comment]
한승희
![image](https://user-images.githubusercontent.com/37537241/39535723-9ffe9498-4e6f-11e8-85f7-4caf209c201b.png)
![image](https://user-images.githubusercontent.com/37537241/39535701-8fa54de4-4e6f-11e8-8b75-8b4c952a726b.png)

**Comment by jason2133** [comment]
이재승

![default](https://user-images.githubusercontent.com/37537208/39536329-3c77fe30-4e71-11e8-88a2-97f72bec8172.png)
![123](https://user-images.githubusercontent.com/37537208/39536399-6f3b6096-4e71-11e8-961a-d87db0ea5db6.png)
![adsfasd](https://user-images.githubusercontent.com/37537208/39536405-707847da-4e71-11e8-9fcd-69605450db1b.png)


이재승

**Comment by Hyejoojjang** [comment]
<img width="1280" alt="2018-05-03 1 59 37" src="https://user-images.githubusercontent.com/37541410/39537848-c62f7974-4e75-11e8-91df-ada30b76870f.png">
<img width="1280" alt="2018-05-03 1 59 54" src="https://user-images.githubusercontent.com/37541410/39537850-c6679ed0-4e75-11e8-824d-ba35687d6907.png">
<img width="1280" alt="2018-05-03 1 59 57" src="https://user-images.githubusercontent.com/37541410/39537851-c699b604-4e75-11e8-9f36-9fbce3db9582.png">
<img width="1280" alt="2018-05-03 2 00 04" src="https://user-images.githubusercontent.com/37541410/39537852-c6cd45aa-4e75-11e8-8e38-f0c2c3897992.png">
<img width="1280" alt="2018-05-03 2 00 08" src="https://user-images.githubusercontent.com/37541410/39537854-c7112856-4e75-11e8-827c-0e36f42b2590.png">

**Comment by ingyuseong** [comment]
성인규
![hw_scaffold](https://user-images.githubusercontent.com/37537248/39539758-83b3a1fa-4e7b-11e8-85d1-e74611d5e4ff.JPG)
![hw_scaffold2](https://user-images.githubusercontent.com/37537248/39539763-8b297dba-4e7b-11e8-8c27-5262d1ad13f9.JPG)

**Comment by emilyson** [comment]
<img width="359" alt="1" src="https://user-images.githubusercontent.com/37537203/39558165-562e024c-4ec7-11e8-95d1-1dbb5bd41da8.PNG">
<img width="160" alt="2" src="https://user-images.githubusercontent.com/37537203/39558166-5702a326-4ec7-11e8-87e5-2673e6424bd1.PNG">
<img width="204" alt="3" src="https://user-images.githubusercontent.com/37537203/39558167-59f4a4ee-4ec7-11e8-8b35-08f0ab01130b.PNG">
<img width="351" alt="4" src="https://user-images.githubusercontent.com/37537203/39558172-5f206e8a-4ec7-11e8-9900-ebe7298407bd.PNG">
손지연

**Comment by JIHYUN1110** [comment]
김지현

![_scaffold_1](https://user-images.githubusercontent.com/37537212/39558955-be8c717e-4ecd-11e8-8a83-4f991be3bcfc.PNG)

![_scaffold_2](https://user-images.githubusercontent.com/37537212/39558956-beb753f8-4ecd-11e8-8177-5c28a84d32f5.PNG)

![_scaffold_3](https://user-images.githubusercontent.com/37537212/39558957-bedf8c24-4ecd-11e8-99d8-3274cbb26348.PNG)

**Comment by PoSungKim** [comment]
김보성
![_scaffold 1_](https://user-images.githubusercontent.com/37537227/39559004-09bf0594-4ece-11e8-84d4-5ebb8406efdb.PNG)
![_scaffold21_](https://user-images.githubusercontent.com/37537227/39559006-0bbc299e-4ece-11e8-9d0b-cd99f1e261e7.PNG)

**Comment by Cecilia-L** [comment]
<img width="359" alt="default" src="https://user-images.githubusercontent.com/37537232/39559649-c2994c24-4ed2-11e8-89ba-0c9e9592838e.PNG">
<img width="370" alt="default" src="https://user-images.githubusercontent.com/37537232/39559650-c3157af6-4ed2-11e8-9e5f-24e98c5ad0f9.PNG">
<img width="353" alt="default" src="https://user-images.githubusercontent.com/37537232/39559651-c372cd8c-4ed2-11e8-960a-c4654ec925cb.PNG">
이윤비

**Comment by swimmie0** [comment]
![image](https://user-images.githubusercontent.com/37537202/39560126-63b61120-4ed6-11e8-8036-9af6a628065d.png)
![image](https://user-images.githubusercontent.com/37537202/39560133-689e6fac-4ed6-11e8-86a4-d90bf38c8f09.png)
![image](https://user-images.githubusercontent.com/37537202/39560146-8459659e-4ed6-11e8-8271-753d85b27ecf.png)
이수영

**Comment by ashufflepuff** [comment]
유정아 과제입니다.

<img width="306" alt="hw001" src="https://user-images.githubusercontent.com/37537211/39561213-45d86abe-4edf-11e8-8ebf-2ba7f8650621.PNG">
<img width="418" alt="hw02" src="https://user-images.githubusercontent.com/37537211/39561216-48b5547c-4edf-11e8-8545-67ffce254cfc.PNG">
<img width="293" alt="hw03" src="https://user-images.githubusercontent.com/37537211/39561217-49e336fc-4edf-11e8-9d21-481fd3238dcc.PNG">
<img width="289" alt="hw04" src="https://user-images.githubusercontent.com/37537211/39561218-4b1e68b6-4edf-11e8-88ca-c1eb422651ba.PNG">

**Comment by preeminent77** [comment]
전재현
![image](https://user-images.githubusercontent.com/37537194/39566391-5a048b32-4ef6-11e8-8f90-951d018ff3ed.png)
![image](https://user-images.githubusercontent.com/37537194/39567092-c7655b00-4ef8-11e8-87e7-670fd445bc5d.png)
![image](https://user-images.githubusercontent.com/37537194/39567136-f49a28da-4ef8-11e8-98f8-f3cda0258989.png)

**Comment by jiwonny** [comment]
이지원
![image](https://user-images.githubusercontent.com/37537213/39567368-c6ed427c-4ef9-11e8-83b4-eef5cd27dfb9.png)
![image](https://user-images.githubusercontent.com/37537213/39567401-e19f7c98-4ef9-11e8-8fb7-42c06da4080e.png)
![image](https://user-images.githubusercontent.com/37537213/39567460-1004a5ae-4efa-11e8-9d23-8f02c3628879.png)

**Comment by jihyuunn** [comment]
![2018-05-03 5 53 04](https://user-images.githubusercontent.com/37537223/39567779-0166b18a-4efb-11e8-97e2-3fb6aa72e5e4.png)
![2018-05-03 5 48 06](https://user-images.githubusercontent.com/37537223/39567781-0193a384-4efb-11e8-95a0-0f4b9897ebd7.png)
![2018-05-03 5 41 29](https://user-images.githubusercontent.com/37537223/39567783-01cf0000-4efb-11e8-9007-b6b854497617.png)
링크 자꾸 오류가 나서,,ㅜㅜ

**Comment by kihyunjoo** [comment]
주기현 
<img width="1359" alt="screen shot 2018-05-03 at 6 29 05 pm" src="https://user-images.githubusercontent.com/37537229/39569448-35b4e484-4f00-11e8-8cb2-8ddba5c2288e.png">
<img width="1358" alt="screen shot 2018-05-03 at 6 30 20 pm" src="https://user-images.githubusercontent.com/37537229/39569459-3edd5816-4f00-11e8-9225-6a1715f22c64.png">
<img width="1354" alt="screen shot 2018-05-03 at 6 30 29 pm" src="https://user-images.githubusercontent.com/37537229/39569469-44354058-4f00-11e8-8c22-77a1a4b56bba.png">
<img width="1359" alt="screen shot 2018-05-03 at 6 30 43 pm" src="https://user-images.githubusercontent.com/37537229/39569476-466b9d68-4f00-11e8-915e-7d9a91249c40.png">

**Comment by YeChan1030** [comment]
![1](https://user-images.githubusercontent.com/37537205/39569856-69a7f532-4f01-11e8-86c3-c5e2eb6038b1.PNG)
![2](https://user-images.githubusercontent.com/37537205/39569862-6e8c4148-4f01-11e8-8a1c-0f2efbf51a91.PNG)

**Comment by daisybae** [comment]
배영현(늦게라도 제출합니다 ㅜㅜ)
![image](https://user-images.githubusercontent.com/37537214/39820658-473c4518-53e1-11e8-9d00-dcda8223e428.png)
![image](https://user-images.githubusercontent.com/37537214/39820946-09ec7d08-53e2-11e8-911c-c650aa9b3e1e.png)
![image](https://user-images.githubusercontent.com/37537214/39820971-11e0b042-53e2-11e8-9c8f-48acd01d855f.png)
