### ISSUE TITLE
5주차 과제(2) - 첫번째 외주 프로젝트 (부제: 나 진짜 웹 개발 한번 해보려고!)

### ISSUE THREAD

**Issue by woonjangahn** [NEXT-LIKELION/Assignment#9]
반갑습니다, 여러분.

3월 19일을 시작으로 벌써 10회 가량의 세션을 진행했었네요.

지난번 세션을 보니 다들 개발자로서의 역량이 많이 성장한 것 같아 이번 과제는 다소 어려울 수 있지만 의미있는 과제를 올려드립니다. 예상 소요시간은 2~5시간입니다.

1) 여러분은 NEXT에서 홈페이지 개발 외주를 받게 되었습니다.
2) 운영진은 메인 페이지, 학회 소개 페이지, 그리고 댓글 기능이 있는 자유게시판을 요구했습니다.

**Hint) 
1. 지금까지의 교안
2. https://github.com/twbs/bootstrap-rubygem
3. http://getbootstrap.com/docs/4.1/getting-started/introduction/**
4. 굳이 bootstrap을 안 쓰고 css만으로 꾸미셔도 상관은 없지만, 추천하진 않습니다.
5. rails에 bootstrap을 적용하는 법, helper에 css나 class를 입히는 법 등은 직접 검색하세요.
6. 운영진들에게 마음껏 물어보세요!

샘플 스크린샷을 첨부합니다.

5월 10일 19시까지 issue의 댓글로 화면 스크린샷을 올려주시면 됩니다.
샘플 스크린샷과 완전히 같을 필요 없으며, 최대한 창의적으로 외주를 맡아주시면 됩니다.

![01](https://user-images.githubusercontent.com/26547475/39617782-ffbd1222-4fbb-11e8-8541-e349f4636011.PNG)
![02](https://user-images.githubusercontent.com/26547475/39617784-ffe94432-4fbb-11e8-93c3-e8a94f31a7ab.PNG)
![03](https://user-images.githubusercontent.com/26547475/39617785-0026d6bc-4fbc-11e8-95d1-449379b109c1.PNG)
![04](https://user-images.githubusercontent.com/26547475/39617786-004f71c6-4fbc-11e8-984c-63711a7afcb6.PNG)
![05](https://user-images.githubusercontent.com/26547475/39617788-0083edc0-4fbc-11e8-848a-04176ef9b8f4.PNG)

**Comment by sangw0804** [comment]
오상우
<img width="1280" alt="2018-05-05 2 20 54" src="https://user-images.githubusercontent.com/37537207/39659959-c0d42992-506f-11e8-9ce2-e9a06887c416.png">
<img width="1280" alt="2018-05-05 2 21 00" src="https://user-images.githubusercontent.com/37537207/39659960-c325ce94-506f-11e8-87c8-a4d3ac27459c.png">
<img width="1280" alt="2018-05-05 2 21 06" src="https://user-images.githubusercontent.com/37537207/39659962-cf89fd40-506f-11e8-818b-9f5b28f3c3fb.png">
<img width="1280" alt="2018-05-05 2 21 11" src="https://user-images.githubusercontent.com/37537207/39659963-d44abdce-506f-11e8-9491-644d21725fbc.png">
<img width="1280" alt="2018-05-05 2 21 18" src="https://user-images.githubusercontent.com/37537207/39659964-db968f72-506f-11e8-899b-3a13f827e5aa.png">
<img width="1280" alt="2018-05-05 2 21 29" src="https://user-images.githubusercontent.com/37537207/39659966-e4975854-506f-11e8-93bf-4a7ad2b14f37.png">

**Comment by gyeol1212** [comment]
신한결
![2018-05-10 5 13 34](https://user-images.githubusercontent.com/37537201/39859793-0d8dda8a-5476-11e8-9dff-c2805c49e758.png)
![2018-05-10 5 13 43](https://user-images.githubusercontent.com/37537201/39859796-0f06ef50-5476-11e8-8f57-3ee08add4d1d.png)
![2018-05-10 5 13 46](https://user-images.githubusercontent.com/37537201/39859799-1001cb3c-5476-11e8-82e9-653846437753.png)
![2018-05-10 5 14 06](https://user-images.githubusercontent.com/37537201/39859803-12d1e7ca-5476-11e8-9fb5-17ae66d9fc91.png)
![2018-05-10 5 14 30](https://user-images.githubusercontent.com/37537201/39859817-1f3ba47e-5476-11e8-92af-7e99ac8b4827.png)
![2018-05-10 5 14 54](https://user-images.githubusercontent.com/37537201/39859821-21c04362-5476-11e8-8c33-c4b0e5cb9f18.png)

**Comment by seona-yu** [comment]
유선아

<img width="634" alt="1" src="https://user-images.githubusercontent.com/37537217/39669990-8ef90724-5134-11e8-8e38-f4edfddd9841.png">
<img width="769" alt="122" src="https://user-images.githubusercontent.com/37537217/39695667-5ebec3bc-5226-11e8-8383-8d1c88699b60.png">

<img width="690" alt="3" src="https://user-images.githubusercontent.com/37537217/39669992-9242d400-5134-11e8-9ebf-bb7f927cdc1a.png">
<img width="750" alt="4" src="https://user-images.githubusercontent.com/37537217/39669993-9431e486-5134-11e8-8656-68bf358d5c9e.png">

**Comment by norrard148** [comment]
![1](https://user-images.githubusercontent.com/37537262/39676032-64b99662-519e-11e8-97e5-bc95a62613eb.PNG)
![2](https://user-images.githubusercontent.com/37537262/39676035-68e4a2ea-519e-11e8-9065-f556100f225c.PNG)
![3](https://user-images.githubusercontent.com/37537262/39676037-6c0c6278-519e-11e8-9441-4f3d90499e58.PNG)
![4](https://user-images.githubusercontent.com/37537262/39676038-6f1ef3fe-519e-11e8-8ddb-57cc356ad818.PNG)

**Comment by ingyuseong** [comment]
성인규
![hw_next](https://user-images.githubusercontent.com/37537248/39685745-8ff2d8f0-51ff-11e8-9207-c6406b04ed8a.JPG)
![hw_next2](https://user-images.githubusercontent.com/37537248/39685751-937b153c-51ff-11e8-9c48-bc085d02d782.JPG)
![hw_next3](https://user-images.githubusercontent.com/37537248/39685752-969b9174-51ff-11e8-8842-3950b10106e9.JPG)
![hw_next4](https://user-images.githubusercontent.com/37537248/39685755-9b236424-51ff-11e8-9cc5-74e94f2794fa.JPG)
![hw_next5](https://user-images.githubusercontent.com/37537248/39685759-a217e296-51ff-11e8-8981-f9a1a959882c.JPG)
![hw_next6](https://user-images.githubusercontent.com/37537248/39685761-a54380f6-51ff-11e8-9034-1d9cf152623b.JPG)
![hw_next7](https://user-images.githubusercontent.com/37537248/39685762-a88f3b6a-51ff-11e8-9800-6ef57a0e58bd.JPG)
![hw_next8](https://user-images.githubusercontent.com/37537248/39685764-abac0968-51ff-11e8-9692-1cf8f0c84afa.JPG)
![hw_next9](https://user-images.githubusercontent.com/37537248/39685765-ae98251c-51ff-11e8-882d-aadb4a6f06b8.JPG)

**Comment by JIHYUN1110** [comment]
김지현

![_ _1](https://user-images.githubusercontent.com/37537212/39688341-3c6a3c7e-520d-11e8-936d-ac9e0b69efb3.PNG)


![_ _2](https://user-images.githubusercontent.com/37537212/39688346-42b2a0ee-520d-11e8-9fd6-979e76a3881c.PNG)


![_ _3](https://user-images.githubusercontent.com/37537212/39688350-488408fa-520d-11e8-9c53-4c368eac4f02.PNG)


![_ _4](https://user-images.githubusercontent.com/37537212/39688358-4d61b94e-520d-11e8-8740-478f923f6145.PNG)


![_ _3 5](https://user-images.githubusercontent.com/37537212/39688402-8b57fec0-520d-11e8-9140-2ec1d3d43782.PNG)

**Comment by soonjune** [comment]
박승준
<img width="1273" alt="2018-05-07 5 21 58" src="https://user-images.githubusercontent.com/37537242/39692278-5d9f10fa-521b-11e8-95f7-6e2884019d56.png">
<img width="1274" alt="2018-05-07 5 22 08" src="https://user-images.githubusercontent.com/37537242/39692280-5f5b0d0e-521b-11e8-98f4-43739fd13714.png">
<img width="1277" alt="2018-05-07 5 22 15" src="https://user-images.githubusercontent.com/37537242/39692286-63ea60d6-521b-11e8-923e-1d35e713bd35.png">
<img width="1280" alt="2018-05-07 5 22 25" src="https://user-images.githubusercontent.com/37537242/39692288-6536da64-521b-11e8-93b6-e50d36c3ad3d.png">

**Comment by norrard148** [comment]
장영재
![1](https://user-images.githubusercontent.com/37537262/39851616-de1a3cc6-5452-11e8-801b-55662ed3beb1.PNG)
![2](https://user-images.githubusercontent.com/37537262/39851618-df0ec2be-5452-11e8-8521-1a59b120286e.PNG)
![111](https://user-images.githubusercontent.com/37537262/39852708-f27f971e-5458-11e8-8fe8-8e592f861cd6.PNG)
![33](https://user-images.githubusercontent.com/37537262/39852782-646a117e-5459-11e8-82f1-f450f6fd7519.PNG)

![222222](https://user-images.githubusercontent.com/37537262/39852743-2a0b59de-5459-11e8-869e-a6b8906bd880.PNG)
![2222](https://user-images.githubusercontent.com/37537262/39852695-e068e30a-5458-11e8-8fb1-6269d31ec5ae.PNG)

**Comment by jason2133** [comment]
이재승
![1](https://user-images.githubusercontent.com/37537208/39754212-6cb9f1c2-52fc-11e8-8ca7-c5239181b275.png)
![2](https://user-images.githubusercontent.com/37537208/39754213-6dd54b24-52fc-11e8-8dc1-199badd8ceb2.png)
![3](https://user-images.githubusercontent.com/37537208/39754215-6ed55a14-52fc-11e8-9e31-c06b892ff342.png)
![4](https://user-images.githubusercontent.com/37537208/39754218-6fdbe6b2-52fc-11e8-841d-f206b0ff44c4.png)
![5](https://user-images.githubusercontent.com/37537208/39754219-70d0411c-52fc-11e8-8413-658d43e1fef5.png)


일단 만들었는데, 여러모로 많이 부족합니다ㅠㅠ 열심히 공부할게요ㅠ

이재승

**Comment by jihyuunn** [comment]
![2018-05-09 8 17 26](https://user-images.githubusercontent.com/37537223/39812058-15c5bd86-53c6-11e8-8369-893b0612126c.png)
![2018-05-09 8 17 33](https://user-images.githubusercontent.com/37537223/39812059-16ba5314-53c6-11e8-82a0-cd263f260400.png)
![2018-05-09 8 17 35](https://user-images.githubusercontent.com/37537223/39812061-17f1efbc-53c6-11e8-8612-6c83325ce7a6.png)
![2018-05-09 8 17 44](https://user-images.githubusercontent.com/37537223/39812063-193a2ef2-53c6-11e8-86cd-7a204db3f4b1.png)
![2018-05-09 8 17 48](https://user-images.githubusercontent.com/37537223/39812065-1abd02c2-53c6-11e8-9d1f-bdcb4f5f167c.png)
![2018-05-09 8 18 01](https://user-images.githubusercontent.com/37537223/39812067-1be04858-53c6-11e8-8511-7fa9be4b119c.png)

이지현 
근데 댓글 밑에 정보?같은게 왜 뜨는건지 모르겠어요,,,

**Comment by hy970723** [comment]
<img width="1436" alt="2018-05-09 10 00 29" src="https://user-images.githubusercontent.com/37537254/39815956-b2bde7e0-53d4-11e8-8151-672b23468c02.png">
<img width="1436" alt="2018-05-09 10 00 41" src="https://user-images.githubusercontent.com/37537254/39815959-b5cb7d58-53d4-11e8-8b47-c198f1cf05ac.png">
<img width="1438" alt="2018-05-09 10 00 50" src="https://user-images.githubusercontent.com/37537254/39815960-b646c9f4-53d4-11e8-9ce7-14881ea99633.png">
<img width="1434" alt="2018-05-09 10 00 58" src="https://user-images.githubusercontent.com/37537254/39815965-b81da838-53d4-11e8-91a0-6b43ba93a041.png">

**Comment by Yerim2695** [comment]
허예림
![noname01](https://user-images.githubusercontent.com/37537200/39821372-0b7ed3ea-53e3-11e8-8650-868214334d83.jpg)
![2](https://user-images.githubusercontent.com/37537200/39821368-0acfd188-53e3-11e8-81e8-01304f361fcc.jpg)
![3](https://user-images.githubusercontent.com/37537200/39821369-0afd2c50-53e3-11e8-8b4a-84db2e876871.jpg)
![4](https://user-images.githubusercontent.com/37537200/39821370-0b27c6c2-53e3-11e8-9458-8c67d75c8c1d.jpg)
![5](https://user-images.githubusercontent.com/37537200/39821371-0b53a2f6-53e3-11e8-94b1-b7b83baff8fe.jpg)

**Comment by ghost** [comment]
장민규입니다 !
<img width="960" alt="1" src="https://user-images.githubusercontent.com/37537219/39827951-677414b0-53f4-11e8-8225-f81d79471616.PNG">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/37537219/39827952-684708b6-53f4-11e8-81b1-edc6f839c33e.PNG">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/37537219/39827955-690410e6-53f4-11e8-8d81-0603e3063742.PNG">
<img width="960" alt="5" src="https://user-images.githubusercontent.com/37537219/39827957-69f57fe4-53f4-11e8-93d6-ee548e3ef64a.PNG">
<img width="960" alt="6" src="https://user-images.githubusercontent.com/37537219/39827958-6ae4b67c-53f4-11e8-81ac-3fe9a6c9f7da.PNG">

**Comment by qlqnf16** [comment]
이정민

<img width="960" alt="2018-05-10" src="https://user-images.githubusercontent.com/37537216/39831451-7f531d82-53ff-11e8-9a96-d7194a94ed48.png">
<img width="960" alt="2018-05-10 1" src="https://user-images.githubusercontent.com/37537216/39831452-7f838bac-53ff-11e8-9a39-78abc697df23.png">
<img width="960" alt="2018-05-10 2" src="https://user-images.githubusercontent.com/37537216/39831453-7faeb7f0-53ff-11e8-8797-d93114f15ba8.png">

**Comment by Jack2ee** [comment]
허재혁
github: https://github.com/Jack2ee/page.git
![1](https://user-images.githubusercontent.com/37537235/39850268-541432fe-544b-11e8-8e4b-d5f9ffc7a814.PNG)
![2](https://user-images.githubusercontent.com/37537235/39850269-5444fb14-544b-11e8-8c5b-727292f4edf2.PNG)
![3](https://user-images.githubusercontent.com/37537235/39850270-548bfca8-544b-11e8-82aa-dbab412229e2.PNG)

**Comment by ssng123** [comment]
한승희  (시간 부족 & 능력 부족으로 디자인도 많이 못 입혔고 일단 한 화면에 다 담았어요 제송,, ^_ㅠ)
![image](https://user-images.githubusercontent.com/37537241/39851184-8878c708-5450-11e8-8979-2c2285ad43bc.png)
![image](https://user-images.githubusercontent.com/37537241/39851192-8e9345d2-5450-11e8-8323-24070f6f75e6.png)
![image](https://user-images.githubusercontent.com/37537241/39851210-a7117174-5450-11e8-9527-533670fcdbbc.png)

**Comment by YeChan1030** [comment]
![1](https://user-images.githubusercontent.com/37537205/39854564-28af9ee2-5463-11e8-9cff-01b95c78c148.PNG)

![2](https://user-images.githubusercontent.com/37537205/39854565-28daf61e-5463-11e8-8414-ed7dee9cfd75.PNG)

![3](https://user-images.githubusercontent.com/37537205/39854566-290e6bb6-5463-11e8-8334-d61612f9bb39.PNG)

![4](https://user-images.githubusercontent.com/37537205/39854567-2941a7b0-5463-11e8-827a-7a8d87a1c40b.PNG)






해본다고 했는데, bootstrap이 안되네요.... 더 하려다가 시간이 없어서 일단 과제 제출합니다 ㅠㅠ

**Comment by mhbest** [comment]
![111](https://user-images.githubusercontent.com/37537238/39855751-2bb3142a-5468-11e8-9b5c-989e94f24bcd.PNG)
![222](https://user-images.githubusercontent.com/37537238/39855752-2bdc04e8-5468-11e8-8e1d-4237eb02b4b8.PNG)
![333](https://user-images.githubusercontent.com/37537238/39855753-2c03c686-5468-11e8-9d28-e0df03df1d37.PNG)
![4444](https://user-images.githubusercontent.com/37537238/39855754-2c2b3f22-5468-11e8-84eb-1dfa50bde2f8.PNG)
![5555](https://user-images.githubusercontent.com/37537238/39855755-2c5442be-5468-11e8-8b41-c992ce384ba9.PNG)
![6666](https://user-images.githubusercontent.com/37537238/39855756-2c853504-5468-11e8-89e1-9bf5b47a7ce8.PNG)
많이 허접하지만 계속 보완해나가겠습니당~

**Comment by jiwonny** [comment]
이지원
![image](https://user-images.githubusercontent.com/37537213/39857023-e38a0244-546c-11e8-9190-f05d17ce8564.png)
![image](https://user-images.githubusercontent.com/37537213/39857054-fb18a5f0-546c-11e8-91c2-f12d32d6e23b.png)
![image](https://user-images.githubusercontent.com/37537213/39857076-0ba1b27c-546d-11e8-928c-d1abbc3d7695.png)
![image](https://user-images.githubusercontent.com/37537213/39857093-191cab0a-546d-11e8-880d-e2024cde4179.png)
![image](https://user-images.githubusercontent.com/37537213/39857116-2940cd36-546d-11e8-8299-49f9b6c20457.png)
![image](https://user-images.githubusercontent.com/37537213/39857163-4ff86858-546d-11e8-8afd-a8ca3bde780e.png)

**Comment by dkor3** [comment]
![5](https://user-images.githubusercontent.com/37537204/39857405-34da5602-546e-11e8-91a6-fb2c71d71276.png)
![1](https://user-images.githubusercontent.com/37537204/39857406-35128752-546e-11e8-8d5e-73a2cb12b644.png)
![2](https://user-images.githubusercontent.com/37537204/39857407-35620598-546e-11e8-8a47-2b2219ca5082.png)
![3](https://user-images.githubusercontent.com/37537204/39857408-358ad7ca-546e-11e8-8b52-9741c7a85a06.png)
![4](https://user-images.githubusercontent.com/37537204/39857409-35b18c30-546e-11e8-8c1c-eb06e472b725.png)

**Comment by X3PY** [comment]
전준표
![1](https://user-images.githubusercontent.com/37537209/39858511-c86bbcdc-5471-11e8-80d4-c27cabab5c0a.PNG)
![2](https://user-images.githubusercontent.com/37537209/39858512-c8900a24-5471-11e8-8828-d4c354872872.PNG)
![3](https://user-images.githubusercontent.com/37537209/39858513-c8b8b67c-5471-11e8-9f68-0e437f437570.PNG)
![4](https://user-images.githubusercontent.com/37537209/39858514-c8ddd470-5471-11e8-8287-61f168c2de95.PNG)
![5](https://user-images.githubusercontent.com/37537209/39858515-c90615ca-5471-11e8-956a-baf871430c71.PNG)

**Comment by Hyejoojjang** [comment]
(현재 부트스트랩 공부하는 중 ㅎㅅㅎ 응원해주세요!)


![Uploading 스크린샷 2018-05-10 오후 2.44.49.png…]()
![Uploading 스크린샷 2018-05-10 오후 2.44.52.png…]()
![Uploading 스크린샷 2018-05-10 오후 2.44.55.png…]()
![Uploading 스크린샷 2018-05-10 오후 5.03.43.png…]()
![Uploading 스크린샷 2018-05-10 오후 5.03.45.png…]()
![Uploading 스크린샷 2018-05-10 오후 5.03.49.png…]()
![Uploading 스크린샷 2018-05-10 오후 5.03.52.png…]()

**Comment by swimmie0** [comment]
![image](https://user-images.githubusercontent.com/37537202/39861317-2feb41bc-547b-11e8-81d3-f4ca03f16469.png)
![image](https://user-images.githubusercontent.com/37537202/39861325-3a3e132e-547b-11e8-897f-3ca759b7d65b.png)

![image](https://user-images.githubusercontent.com/37537202/39861340-45b4f1a0-547b-11e8-9873-f46415f096b7.png)
![image](https://user-images.githubusercontent.com/37537202/39861851-e47781a8-547c-11e8-86e9-e6e0a6e925ce.png)
이수영

**Comment by Cecilia-L** [comment]
이윤비
<img width="960" alt="next_" src="https://user-images.githubusercontent.com/37537232/39861679-4b7e919e-547c-11e8-9f54-4564af750b94.PNG">
<img width="960" alt="next_edit" src="https://user-images.githubusercontent.com/37537232/39861674-4a93e25c-547c-11e8-9b30-76d7b271fe16.PNG">
<img width="960" alt="next_new" src="https://user-images.githubusercontent.com/37537232/39861675-4ac1dbf8-547c-11e8-98bc-c471ccbb3788.PNG">
<img width="960" alt="next_show" src="https://user-images.githubusercontent.com/37537232/39861676-4af2da3c-547c-11e8-8aa7-88d1a3e8bf76.PNG">
<img width="960" alt="next_" src="https://user-images.githubusercontent.com/37537232/39861677-4b22b054-547c-11e8-8f95-7081f3587fbd.PNG">
<img width="960" alt="next_" src="https://user-images.githubusercontent.com/37537232/39861678-4b4fb522-547c-11e8-872f-ad777b5946c2.PNG">

**Comment by ashufflepuff** [comment]
유정아

부트스트랩으로옷입히기를못햇네여ㅠㅠ 부트스트랩배우고다시할게요!!!

<img width="869" alt="home_index" src="https://user-images.githubusercontent.com/37537211/39862286-4fb3a720-547e-11e8-9753-7daa079ac9de.PNG">
<img width="915" alt="posts_index" src="https://user-images.githubusercontent.com/37537211/39862287-506f045c-547e-11e8-97ed-ee67c33e90b3.PNG">
<img width="786" alt="default" src="https://user-images.githubusercontent.com/37537211/39862288-511cbe80-547e-11e8-8d6e-ac9aebee5dab.PNG">
<img width="613" alt="next" src="https://user-images.githubusercontent.com/37537211/39862290-51ce637e-547e-11e8-9352-23aca1d6e77c.PNG">

**Comment by daisybae** [comment]
배영현
![image](https://user-images.githubusercontent.com/37537214/39986181-e7b1cd34-579b-11e8-83e8-8d5724f88161.png)
![image](https://user-images.githubusercontent.com/37537214/39986229-06496766-579c-11e8-976e-2f5eb2633839.png)
![image](https://user-images.githubusercontent.com/37537214/39986201-f58c8084-579b-11e8-96db-c428f1171fe9.png)

**Comment by hyunjaeyou** [comment]
유현재입니다
https://github.com/hyunjaeyou/next.git

**Comment by PoSungKim** [comment]
김보성 (죄송합니다)
![_website_](https://user-images.githubusercontent.com/37537227/39863342-54f897ec-5481-11e8-8041-5ec50bd6f7b7.PNG)

**Comment by preeminent77** [comment]
https://github.com/preeminent77/hahaa.git

**Comment by emilyson** [comment]
![image](https://user-images.githubusercontent.com/37537203/39863954-29caf608-5483-11e8-8388-4ce9100f0a7f.png)

![image](https://user-images.githubusercontent.com/37537203/39863945-1fad6aa2-5483-11e8-8adf-f951cfd09bc0.png)
이번 과제는 정말 혼자 해결해보고 싶어서 헬프세션도 안갔던 저의 무지함을 탓합니다ㅠㅠ rails까지는 하고
9번째 엎었는데도 bootstrap적용이 잘 안되네용,,
결국 맨 처음에 했던 거 올립니당ㅠㅠ 각성하고 진짜 열심히 하겠습니다!!!ㅜㅜ

**Comment by Hyezzi** [comment]
![image](https://user-images.githubusercontent.com/37537222/39864198-db36ced0-5483-11e8-8237-7705631e8e9f.png)
![image](https://user-images.githubusercontent.com/37537222/39864201-dff5ee38-5483-11e8-99a4-8ba19d591f77.png)
![image](https://user-images.githubusercontent.com/37537222/39864209-e3e64498-5483-11e8-9616-12856412cd1f.png)


원혜진
